// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Scaffolding.Metadata
// Assembly: Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { Annotatable, Annotation, IAnnotatable, IAnnotation, IReadOnlyAnnotatable } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Internal from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { IMutableAnnotatable, ValueGenerated } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { ReferentialAction } from "../../Microsoft.EntityFrameworkCore.Migrations/internal/index.js";
import type { IEnumerable, IList, IReadOnlyDictionary } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Boolean as ClrBoolean, Func, Int32, Int64, Nullable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";

export abstract class DatabaseColumn$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseColumn$instance extends DatabaseColumn$protected, Annotatable {
    get Collation(): string | undefined;
    set Collation(value: string);
    get Comment(): string | undefined;
    set Comment(value: string);
    get ComputedColumnSql(): string | undefined;
    set ComputedColumnSql(value: string);
    get DefaultValue(): unknown | undefined;
    set DefaultValue(value: unknown);
    get DefaultValueSql(): string | undefined;
    set DefaultValueSql(value: string);
    IsNullable: boolean;
    IsStored: Nullable<System_Internal.Boolean>;
    Name: string;
    StoreType: string;
    Table: DatabaseTable;
    ValueGenerated: Nullable<ValueGenerated>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabaseColumn: {
    new(): DatabaseColumn;
};


export interface __DatabaseColumn$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseColumn = DatabaseColumn$instance & __DatabaseColumn$views;


export abstract class DatabaseForeignKey$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseForeignKey$instance extends DatabaseForeignKey$protected, Annotatable {
    readonly Columns: IList<DatabaseColumn>;
    Name: string;
    OnDelete: Nullable<ReferentialAction>;
    readonly PrincipalColumns: IList<DatabaseColumn>;
    PrincipalTable: DatabaseTable;
    Table: DatabaseTable;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabaseForeignKey: {
    new(): DatabaseForeignKey;
};


export interface __DatabaseForeignKey$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseForeignKey = DatabaseForeignKey$instance & __DatabaseForeignKey$views;


export abstract class DatabaseIndex$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseIndex$instance extends DatabaseIndex$protected, Annotatable {
    readonly Columns: IList<DatabaseColumn>;
    get Filter(): string | undefined;
    set Filter(value: string);
    IsDescending: IList<System_Internal.Boolean>;
    IsUnique: boolean;
    Name: string;
    Table: DatabaseTable;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabaseIndex: {
    new(): DatabaseIndex;
};


export interface __DatabaseIndex$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseIndex = DatabaseIndex$instance & __DatabaseIndex$views;


export abstract class DatabaseModel$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseModel$instance extends DatabaseModel$protected, Annotatable {
    get Collation(): string | undefined;
    set Collation(value: string);
    get DatabaseName(): string | undefined;
    set DatabaseName(value: string);
    get DefaultSchema(): string | undefined;
    set DefaultSchema(value: string);
    readonly Sequences: IList<DatabaseSequence>;
    readonly Tables: IList<DatabaseTable>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DatabaseModel: {
    new(): DatabaseModel;
};


export interface __DatabaseModel$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseModel = DatabaseModel$instance & __DatabaseModel$views;


export abstract class DatabasePrimaryKey$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabasePrimaryKey$instance extends DatabasePrimaryKey$protected, Annotatable {
    readonly Columns: IList<DatabaseColumn>;
    Name: string;
    Table: DatabaseTable;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabasePrimaryKey: {
    new(): DatabasePrimaryKey;
};


export interface __DatabasePrimaryKey$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabasePrimaryKey = DatabasePrimaryKey$instance & __DatabasePrimaryKey$views;


export abstract class DatabaseSequence$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseSequence$instance extends DatabaseSequence$protected, Annotatable {
    Database: DatabaseModel;
    IncrementBy: Nullable<System_Internal.Int32>;
    IsCyclic: Nullable<System_Internal.Boolean>;
    MaxValue: Nullable<System_Internal.Int64>;
    MinValue: Nullable<System_Internal.Int64>;
    Name: string;
    Schema: string;
    StartValue: Nullable<System_Internal.Int64>;
    StoreType: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabaseSequence: {
    new(): DatabaseSequence;
};


export interface __DatabaseSequence$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseSequence = DatabaseSequence$instance & __DatabaseSequence$views;


export abstract class DatabaseTable$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseTable$instance extends DatabaseTable$protected, Annotatable {
    readonly Columns: IList<DatabaseColumn>;
    get Comment(): string | undefined;
    set Comment(value: string);
    Database: DatabaseModel;
    readonly ForeignKeys: IList<DatabaseForeignKey>;
    readonly Indexes: IList<DatabaseIndex>;
    Name: string;
    get PrimaryKey(): DatabasePrimaryKey | undefined;
    set PrimaryKey(value: DatabasePrimaryKey);
    Schema: string;
    readonly Triggers: IList<DatabaseTrigger>;
    readonly UniqueConstraints: IList<DatabaseUniqueConstraint>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabaseTable: {
    new(): DatabaseTable;
};


export interface __DatabaseTable$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseTable = DatabaseTable$instance & __DatabaseTable$views;


export abstract class DatabaseTrigger$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseTrigger$instance extends DatabaseTrigger$protected, Annotatable {
    Name: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DatabaseTrigger: {
    new(): DatabaseTrigger;
};


export interface __DatabaseTrigger$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseTrigger = DatabaseTrigger$instance & __DatabaseTrigger$views;


export abstract class DatabaseUniqueConstraint$protected {
    protected AddAnnotation5(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation5(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation3(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseUniqueConstraint$instance extends DatabaseUniqueConstraint$protected, Annotatable {
    readonly Columns: IList<DatabaseColumn>;
    Name: string;
    Table: DatabaseTable;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
    ToString(): string;
}


export const DatabaseUniqueConstraint: {
    new(): DatabaseUniqueConstraint;
};


export interface __DatabaseUniqueConstraint$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseUniqueConstraint = DatabaseUniqueConstraint$instance & __DatabaseUniqueConstraint$views;


export abstract class DatabaseView$protected {
    protected AddAnnotation7(name: string, annotation: Annotation): Annotation;
    protected AddRuntimeAnnotation7(name: string, annotation: Annotation): Annotation;
    protected SetAnnotation4(name: string, annotation: Annotation, oldAnnotation: Annotation): Annotation | undefined;
}


export interface DatabaseView$instance extends DatabaseView$protected, DatabaseTable$instance {
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DatabaseView: {
    new(): DatabaseView;
};


export interface __DatabaseView$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseView = DatabaseView$instance & __DatabaseView$views;


