// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Design
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Relational

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { QualifiedName } from "../../Microsoft.EntityFrameworkCore.Design.Internal/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { EntityFrameworkServicesBuilder, IAnnotatable, IAnnotation, ServiceCharacteristics, ServiceCollectionMap } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { ICheckConstraint, IComplexProperty, IComplexType, IEntityType, IEntityTypeMappingFragment, IForeignKey, IIndex, IKey, IModel, INavigation, IProperty, IRelationalPropertyOverrides, ISequence, ISkipNavigation, ITrigger } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { IRelationalTypeMappingSource } from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbContext } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import type { Dictionary_2, ICollection_1, IDictionary_2, IEnumerable_1, IReadOnlyDictionary_2, IReadOnlyList_1, ISet_1, List_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions/internal/index.js";
import type { BigInteger } from "@tsonic/dotnet/System.Numerics/internal/index.js";
import type { MemberInfo, MethodInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Attribute, Boolean as ClrBoolean, Byte, Char, DateOnly, DateTime, DateTimeOffset, Decimal, Double, Enum, Func_2, Guid, IEquatable_1, Int16, Int32, Int64, IServiceProvider, Nullable_1, Object as ClrObject, SByte, Single, String as ClrString, TimeOnly, TimeSpan, Type, UInt16, UInt32, UInt64, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";

export interface IAnnotationCodeGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IAnnotationCodeGenerator: never;

    FilterIgnoredAnnotations(annotations: IEnumerable_1<IAnnotation>): IEnumerable_1<IAnnotation>;
    GenerateFluentApiCalls(annotatable: IAnnotatable, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(checkConstraint: ICheckConstraint, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexProperty: IComplexProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexType: IComplexType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(entityType: IEntityType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(fragment: IEntityTypeMappingFragment, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(foreignKey: IForeignKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(index: IIndex, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(key: IKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(model: IModel, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: INavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(property: IProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(overrides: IRelationalPropertyOverrides, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(sequence: ISequence, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: ISkipNavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(trigger: ITrigger, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    RemoveAnnotationsHandledByConventions(annotatable: IAnnotatable, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(checkConstraint: ICheckConstraint, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexProperty: IComplexProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexType: IComplexType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(entityType: IEntityType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(fragment: IEntityTypeMappingFragment, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(foreignKey: IForeignKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(index: IIndex, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(key: IKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(model: IModel, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: INavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(property: IProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(overrides: IRelationalPropertyOverrides, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(sequence: ISequence, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: ISkipNavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(trigger: ITrigger, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
}


export type IAnnotationCodeGenerator = IAnnotationCodeGenerator$instance;

export interface ICSharpHelper$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_ICSharpHelper: never;

    Arguments(values: IEnumerable_1<unknown>): string;
    Fragment(fragment: AttributeCodeFragment): string;
    Fragment(fragment: IMethodCallCodeFragment | null, indent?: int): string;
    Fragment(fragment: IMethodCallCodeFragment, instanceIdentifier: string | null, typeQualified: boolean): string;
    Fragment(fragment: NestedClosureCodeFragment, indent?: int): string;
    Fragment(fragment: PropertyAccessorCodeFragment): string;
    GetRequiredUsings(type: Type): IEnumerable_1<System_Internal.String>;
    Identifier(name: string, scope?: ICollection_1<System_Internal.String> | null, capitalize?: Nullable_1<System_Internal.Boolean>): string;
    Identifier<T extends unknown>(name: string, value: T, scope: IDictionary_2<System_Internal.String, T>, capitalize?: Nullable_1<System_Internal.Boolean>): string;
    Lambda(properties: IEnumerable_1<IProperty>, lambdaIdentifier?: string | null): string;
    Lambda(properties: IReadOnlyList_1<System_Internal.String>, lambdaIdentifier?: string | null): string;
    Literal<TKey extends unknown, TValue extends unknown>(values: Dictionary_2<TKey, TValue>, vertical?: boolean): string;
    Literal<T extends unknown>(values: List_1<T>, vertical?: boolean): string;
    Literal<T extends NonNullable<unknown>>(value: Nullable_1<T>): string;
    Literal(value: boolean): string;
    Literal(value: byte): string;
    Literal(value: char): string;
    Literal(value: DateOnly): string;
    Literal(value: DateTime): string;
    Literal(value: DateTimeOffset): string;
    Literal(value: decimal): string;
    Literal(value: double): string;
    Literal(value: number, fullName?: boolean): string;
    Literal(value: Guid): string;
    Literal(value: short): string;
    Literal(value: int): string;
    Literal(value: long): string;
    Literal(value: BigInteger): string;
    Literal(values: Array<Array<(unknown | null)>>): string;
    Literal(value: sbyte): string;
    Literal(value: float): string;
    Literal(value: string | null): string;
    Literal(value: TimeOnly): string;
    Literal(value: TimeSpan): string;
    Literal(value: Type, fullName?: Nullable_1<System_Internal.Boolean>): string;
    Literal(value: ushort): string;
    Literal(value: uint): string;
    Literal(value: ulong): string;
    Literal<T extends unknown>(values: T[], vertical?: boolean): string;
    Namespace(...name: string[]): string;
    Statement(node: Expression, collectedNamespaces: ISet_1<System_Internal.String>, unsafeAccessors: ISet_1<System_Internal.String>, constantReplacements?: IReadOnlyDictionary_2<unknown, System_Internal.String> | null, memberAccessReplacements?: IReadOnlyDictionary_2<MemberInfo, QualifiedName> | null): string;
    UnknownLiteral(value: unknown | null): string;
    XmlComment(comment: string, indent?: int): string;
}


export type ICSharpHelper = ICSharpHelper$instance;

export interface IDesignTimeDbContextFactory_1$instance<TContext extends unknown & DbContext> {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IDesignTimeDbContextFactory_1: never;

    CreateDbContext(args: string[]): TContext;
}


export type IDesignTimeDbContextFactory_1<TContext extends unknown & DbContext> = IDesignTimeDbContextFactory_1$instance<TContext>;

export interface IDesignTimeServices$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IDesignTimeServices: never;

    ConfigureDesignTimeServices(serviceCollection: IServiceCollection): void;
}


export type IDesignTimeServices = IDesignTimeServices$instance;

export interface IMethodCallCodeFragment$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IMethodCallCodeFragment: never;

    readonly DeclaringType: string | null;
    readonly Method: string;
    readonly TypeArguments: IEnumerable_1<System_Internal.String>;
    readonly Arguments: IEnumerable_1<unknown | null>;
    readonly ChainedCall: IMethodCallCodeFragment | null;
}


export type IMethodCallCodeFragment = IMethodCallCodeFragment$instance;

export interface AnnotationCodeGenerator$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_AnnotationCodeGenerator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IAnnotationCodeGenerator: never;

    readonly Dependencies: AnnotationCodeGeneratorDependencies;
    FilterIgnoredAnnotations(annotations: IEnumerable_1<IAnnotation>): IEnumerable_1<IAnnotation>;
    GenerateDataAnnotation(entityType: IEntityType, annotation: IAnnotation): AttributeCodeFragment | null;
    GenerateDataAnnotation(property: IProperty, annotation: IAnnotation): AttributeCodeFragment | null;
    GenerateDataAnnotationAttributes(entityType: IEntityType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<AttributeCodeFragment>;
    GenerateDataAnnotationAttributes(property: IProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<AttributeCodeFragment>;
    GenerateDataAnnotationAttributes(annotatable: IAnnotatable, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<AttributeCodeFragment>;
    GenerateFluentApi(model: IModel, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(entityType: IEntityType, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(complexType: IComplexType, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(fragment: IEntityTypeMappingFragment, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(key: IKey, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(property: IProperty, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(complexProperty: IComplexProperty, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(foreignKey: IForeignKey, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(navigation: INavigation, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(navigation: ISkipNavigation, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(index: IIndex, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(checkConstraint: ICheckConstraint, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(trigger: ITrigger, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(overrides: IRelationalPropertyOverrides, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApi(sequence: ISequence, annotation: IAnnotation): MethodCallCodeFragment | null;
    GenerateFluentApiCalls(model: IModel, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(entityType: IEntityType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexType: IComplexType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(fragment: IEntityTypeMappingFragment, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(property: IProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexProperty: IComplexProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(key: IKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(foreignKey: IForeignKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: INavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: ISkipNavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(index: IIndex, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(checkConstraint: ICheckConstraint, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(trigger: ITrigger, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(overrides: IRelationalPropertyOverrides, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(sequence: ISequence, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    GenerateFluentApiCalls(annotatable: IAnnotatable, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    IsHandledByConvention(model: IModel, annotation: IAnnotation): boolean;
    IsHandledByConvention(entityType: IEntityType, annotation: IAnnotation): boolean;
    IsHandledByConvention(complexType: IComplexType, annotation: IAnnotation): boolean;
    IsHandledByConvention(fragment: IEntityTypeMappingFragment, annotation: IAnnotation): boolean;
    IsHandledByConvention(key: IKey, annotation: IAnnotation): boolean;
    IsHandledByConvention(property: IProperty, annotation: IAnnotation): boolean;
    IsHandledByConvention(complexProperty: IComplexProperty, annotation: IAnnotation): boolean;
    IsHandledByConvention(foreignKey: IForeignKey, annotation: IAnnotation): boolean;
    IsHandledByConvention(navigation: INavigation, annotation: IAnnotation): boolean;
    IsHandledByConvention(navigation: ISkipNavigation, annotation: IAnnotation): boolean;
    IsHandledByConvention(index: IIndex, annotation: IAnnotation): boolean;
    IsHandledByConvention(checkConstraint: ICheckConstraint, annotation: IAnnotation): boolean;
    IsHandledByConvention(trigger: ITrigger, annotation: IAnnotation): boolean;
    IsHandledByConvention(overrides: IRelationalPropertyOverrides, annotation: IAnnotation): boolean;
    IsHandledByConvention(sequence: ISequence, annotation: IAnnotation): boolean;
    RemoveAnnotationsHandledByConventions(model: IModel, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(entityType: IEntityType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexType: IComplexType, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(fragment: IEntityTypeMappingFragment, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(property: IProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexProperty: IComplexProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(key: IKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(foreignKey: IForeignKey, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: INavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: ISkipNavigation, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(index: IIndex, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(checkConstraint: ICheckConstraint, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(trigger: ITrigger, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(overrides: IRelationalPropertyOverrides, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(sequence: ISequence, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(annotatable: IAnnotatable, annotations: IDictionary_2<System_Internal.String, IAnnotation>): void;
}


export const AnnotationCodeGenerator: {
    new(dependencies: AnnotationCodeGeneratorDependencies): AnnotationCodeGenerator;
};


export interface __AnnotationCodeGenerator$views {
    As_IAnnotationCodeGenerator(): IAnnotationCodeGenerator$instance;
}

export type AnnotationCodeGenerator = AnnotationCodeGenerator$instance & __AnnotationCodeGenerator$views;


export interface AnnotationCodeGeneratorDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_AnnotationCodeGeneratorDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    RelationalTypeMappingSource: IRelationalTypeMappingSource;
    _Clone_$(): AnnotationCodeGeneratorDependencies;
    Equals(obj: unknown | null): boolean;
    Equals(other: AnnotationCodeGeneratorDependencies | null): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const AnnotationCodeGeneratorDependencies: {
    new(relationalTypeMappingSource: IRelationalTypeMappingSource): AnnotationCodeGeneratorDependencies;
};


export type AnnotationCodeGeneratorDependencies = AnnotationCodeGeneratorDependencies$instance;

export interface AttributeCodeFragment$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_AttributeCodeFragment: never;

    readonly Arguments: IReadOnlyList_1<unknown | null>;
    readonly NamedArguments: IReadOnlyDictionary_2<System_Internal.String, unknown | null>;
    readonly Type: Type;
}


export const AttributeCodeFragment: {
    new(type: Type, arguments: (unknown | null)[]): AttributeCodeFragment;
    new(type: Type, arguments: IEnumerable_1<unknown | null>, namedArguments: IDictionary_2<System_Internal.String, unknown | null>): AttributeCodeFragment;
};


export type AttributeCodeFragment = AttributeCodeFragment$instance;

export interface DesignTimeProviderServicesAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_DesignTimeProviderServicesAttribute: never;

    readonly TypeName: string;
}


export const DesignTimeProviderServicesAttribute: {
    new(typeName: string): DesignTimeProviderServicesAttribute;
};


export type DesignTimeProviderServicesAttribute = DesignTimeProviderServicesAttribute$instance;

export interface DesignTimeServicesReferenceAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_DesignTimeServicesReferenceAttribute: never;

    readonly ForProvider: string | null;
    readonly TypeName: string;
}


export const DesignTimeServicesReferenceAttribute: {
    new(typeName: string): DesignTimeServicesReferenceAttribute;
    new(typeName: string, forProvider: string | null): DesignTimeServicesReferenceAttribute;
};


export type DesignTimeServicesReferenceAttribute = DesignTimeServicesReferenceAttribute$instance;

export interface EntityFrameworkDesignServicesBuilder$instance extends EntityFrameworkServicesBuilder {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_EntityFrameworkDesignServicesBuilder: never;

    TryAddCoreServices(): EntityFrameworkServicesBuilder;
    TryGetServiceCharacteristics(serviceType: Type): Nullable_1<ServiceCharacteristics>;
}


export const EntityFrameworkDesignServicesBuilder: {
    new(serviceCollection: IServiceCollection): EntityFrameworkDesignServicesBuilder;
    readonly Services: IDictionary_2<Type, ServiceCharacteristics>;
};


export type EntityFrameworkDesignServicesBuilder = EntityFrameworkDesignServicesBuilder$instance;

export interface EntityFrameworkRelationalDesignServicesBuilder$instance extends EntityFrameworkDesignServicesBuilder {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_EntityFrameworkRelationalDesignServicesBuilder: never;

    TryAddCoreServices(): EntityFrameworkServicesBuilder;
    TryGetServiceCharacteristics(serviceType: Type): Nullable_1<ServiceCharacteristics>;
}


export const EntityFrameworkRelationalDesignServicesBuilder: {
    new(serviceCollection: IServiceCollection): EntityFrameworkRelationalDesignServicesBuilder;
    readonly RelationalServices: IDictionary_2<Type, ServiceCharacteristics>;
};


export type EntityFrameworkRelationalDesignServicesBuilder = EntityFrameworkRelationalDesignServicesBuilder$instance;

export interface MethodCallCodeFragment$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_MethodCallCodeFragment: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IMethodCallCodeFragment: never;

    readonly Arguments: IReadOnlyList_1<unknown | null>;
    readonly ChainedCall: MethodCallCodeFragment | null;
    readonly DeclaringType: string | null;
    readonly Method: string;
    readonly MethodInfo: MethodInfo | null;
    readonly Namespace: string | null;
    Chain(methodInfo: MethodInfo, ...arguments: (unknown | null)[]): MethodCallCodeFragment;
    Chain(method: string, ...arguments: (unknown | null)[]): MethodCallCodeFragment;
    Chain(call: MethodCallCodeFragment): MethodCallCodeFragment;
}


export const MethodCallCodeFragment: {
    new(methodInfo: MethodInfo, arguments: (unknown | null)[]): MethodCallCodeFragment;
    new(method: string, arguments: (unknown | null)[]): MethodCallCodeFragment;
};


export interface __MethodCallCodeFragment$views {
    As_IMethodCallCodeFragment(): IMethodCallCodeFragment$instance;
}

export type MethodCallCodeFragment = MethodCallCodeFragment$instance & __MethodCallCodeFragment$views;


export interface NestedClosureCodeFragment$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_NestedClosureCodeFragment: never;

    readonly MethodCalls: IReadOnlyList_1<MethodCallCodeFragment>;
    readonly Parameter: string;
}


export const NestedClosureCodeFragment: {
    new(parameter: string, methodCall: MethodCallCodeFragment): NestedClosureCodeFragment;
    new(parameter: string, methodCalls: IReadOnlyList_1<MethodCallCodeFragment>): NestedClosureCodeFragment;
};


export type NestedClosureCodeFragment = NestedClosureCodeFragment$instance;

export interface PropertyAccessorCodeFragment$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_PropertyAccessorCodeFragment: never;

    readonly Parameter: string;
    readonly Properties: IReadOnlyList_1<System_Internal.String>;
}


export const PropertyAccessorCodeFragment: {
    new(parameter: string, properties: IReadOnlyList_1<System_Internal.String>): PropertyAccessorCodeFragment;
};


export type PropertyAccessorCodeFragment = PropertyAccessorCodeFragment$instance;
