// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Design
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { QualifiedName } from "../../Microsoft.EntityFrameworkCore.Design.Internal/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { EntityFrameworkServicesBuilder, IAnnotatable, IAnnotation, ServiceCharacteristics, ServiceCollectionMap } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { ICheckConstraint, IComplexProperty, IComplexType, IEntityType, IEntityTypeMappingFragment, IForeignKey, IIndex, IKey, IModel, INavigation, IProperty, IRelationalPropertyOverrides, ISequence, ISkipNavigation, ITrigger } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { IRelationalTypeMappingSource } from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbContext } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import type { Dictionary, ICollection, IDictionary, IEnumerable, IReadOnlyDictionary, IReadOnlyList, ISet, List } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Attribute, Boolean as ClrBoolean, Byte, Char, DateOnly, DateTime, DateTimeOffset, Decimal, Double, Enum, Func, Guid, IEquatable, Int16, Int32, Int64, IServiceProvider, Nullable, Object as ClrObject, SByte, Single, String as ClrString, TimeOnly, TimeSpan, Type, UInt16, UInt32, UInt64, ValueType, Void } from "@tsonic/dotnet/System.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { BigInteger } from "@tsonic/dotnet/System.Numerics.js";
import type { MemberInfo, MethodInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js";

export interface IAnnotationCodeGenerator$instance {
    FilterIgnoredAnnotations(annotations: IEnumerable<IAnnotation>): IEnumerable<IAnnotation>;
    GenerateFluentApiCalls(annotatable: IAnnotatable, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(checkConstraint: ICheckConstraint, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexProperty: IComplexProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexType: IComplexType, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(entityType: IEntityType, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(fragment: IEntityTypeMappingFragment, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(foreignKey: IForeignKey, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(index: IIndex, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(key: IKey, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(model: IModel, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: INavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(property: IProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(overrides: IRelationalPropertyOverrides, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(sequence: ISequence, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: ISkipNavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(trigger: ITrigger, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    RemoveAnnotationsHandledByConventions(annotatable: IAnnotatable, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(checkConstraint: ICheckConstraint, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexProperty: IComplexProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexType: IComplexType, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(entityType: IEntityType, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(fragment: IEntityTypeMappingFragment, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(foreignKey: IForeignKey, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(index: IIndex, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(key: IKey, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(model: IModel, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: INavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(property: IProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(overrides: IRelationalPropertyOverrides, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(sequence: ISequence, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: ISkipNavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(trigger: ITrigger, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
}


export type IAnnotationCodeGenerator = IAnnotationCodeGenerator$instance;

export interface ICSharpHelper$instance {
    Arguments(values: IEnumerable<unknown>): string;
    Fragment(fragment: AttributeCodeFragment): string;
    Fragment(fragment: IMethodCallCodeFragment, indent?: int): string;
    Fragment(fragment: IMethodCallCodeFragment, instanceIdentifier: string, typeQualified: boolean): string;
    Fragment(fragment: NestedClosureCodeFragment, indent?: int): string;
    Fragment(fragment: PropertyAccessorCodeFragment): string;
    GetRequiredUsings(type: Type): IEnumerable<System_Internal.String>;
    Identifier(name: string, scope?: ICollection<System_Internal.String>, capitalize?: Nullable<System_Internal.Boolean>): string;
    Identifier<T>(name: string, value: T, scope: IDictionary<System_Internal.String, T>, capitalize?: Nullable<System_Internal.Boolean>): string;
    Lambda(properties: IEnumerable<IProperty>, lambdaIdentifier?: string): string;
    Lambda(properties: IReadOnlyList<System_Internal.String>, lambdaIdentifier?: string): string;
    Literal<TKey, TValue>(values: Dictionary<TKey, TValue>, vertical?: boolean): string;
    Literal<T>(values: List<T>, vertical?: boolean): string;
    Literal<T extends unknown>(value: Nullable<T>): string;
    Literal(value: boolean): string;
    Literal(value: byte): string;
    Literal(value: char): string;
    Literal(value: DateOnly): string;
    Literal(value: DateTime): string;
    Literal(value: DateTimeOffset): string;
    Literal(value: decimal): string;
    Literal(value: double): string;
    Literal(value: number, fullName?: boolean): string;
    Literal(value: Guid): string;
    Literal(value: short): string;
    Literal(value: int): string;
    Literal(value: long): string;
    Literal(value: BigInteger): string;
    Literal(values: Array<Array<unknown>>): string;
    Literal(value: sbyte): string;
    Literal(value: float): string;
    Literal(value: string): string;
    Literal(value: TimeOnly): string;
    Literal(value: TimeSpan): string;
    Literal(value: Type, fullName?: Nullable<System_Internal.Boolean>): string;
    Literal(value: ushort): string;
    Literal(value: uint): string;
    Literal(value: ulong): string;
    Literal<T>(values: T[], vertical?: boolean): string;
    Namespace(...name: string[]): string;
    Statement(node: Expression, collectedNamespaces: ISet<System_Internal.String>, unsafeAccessors: ISet<System_Internal.String>, constantReplacements?: IReadOnlyDictionary<unknown, System_Internal.String>, memberAccessReplacements?: IReadOnlyDictionary<MemberInfo, QualifiedName>): string;
    UnknownLiteral(value: unknown): string;
    XmlComment(comment: string, indent?: int): string;
}


export type ICSharpHelper = ICSharpHelper$instance;

export interface IDesignTimeDbContextFactory_1$instance<TContext extends DbContext> {
    CreateDbContext(args: string[]): TContext;
}


export type IDesignTimeDbContextFactory_1<TContext extends DbContext> = IDesignTimeDbContextFactory_1$instance<TContext>;

export interface IDesignTimeServices$instance {
    ConfigureDesignTimeServices(serviceCollection: IServiceCollection): void;
}


export type IDesignTimeServices = IDesignTimeServices$instance;

export interface IMethodCallCodeFragment$instance {
    readonly DeclaringType: string;
    readonly Method: string;
    readonly TypeArguments: IEnumerable<System_Internal.String>;
    readonly Arguments: IEnumerable<unknown | undefined>;
    readonly ChainedCall: IMethodCallCodeFragment | undefined;
}


export type IMethodCallCodeFragment = IMethodCallCodeFragment$instance;

export interface AnnotationCodeGenerator$instance {
    FilterIgnoredAnnotations(annotations: IEnumerable<IAnnotation>): IEnumerable<IAnnotation>;
    GenerateDataAnnotationAttributes(entityType: IEntityType, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<AttributeCodeFragment>;
    GenerateDataAnnotationAttributes(property: IProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<AttributeCodeFragment>;
    GenerateDataAnnotationAttributes(annotatable: IAnnotatable, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<AttributeCodeFragment>;
    GenerateFluentApiCalls(model: IModel, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(entityType: IEntityType, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexType: IComplexType, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(fragment: IEntityTypeMappingFragment, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(property: IProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(complexProperty: IComplexProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(key: IKey, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(foreignKey: IForeignKey, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: INavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(navigation: ISkipNavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(index: IIndex, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(checkConstraint: ICheckConstraint, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(trigger: ITrigger, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(overrides: IRelationalPropertyOverrides, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(sequence: ISequence, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(annotatable: IAnnotatable, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    RemoveAnnotationsHandledByConventions(model: IModel, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(entityType: IEntityType, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexType: IComplexType, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(fragment: IEntityTypeMappingFragment, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(property: IProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(complexProperty: IComplexProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(key: IKey, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(foreignKey: IForeignKey, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: INavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(navigation: ISkipNavigation, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(index: IIndex, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(checkConstraint: ICheckConstraint, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(trigger: ITrigger, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(overrides: IRelationalPropertyOverrides, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(sequence: ISequence, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
    RemoveAnnotationsHandledByConventions(annotatable: IAnnotatable, annotations: IDictionary<System_Internal.String, IAnnotation>): void;
}


export const AnnotationCodeGenerator: {
    new(dependencies: AnnotationCodeGeneratorDependencies): AnnotationCodeGenerator;
};


export interface __AnnotationCodeGenerator$views {
    As_IAnnotationCodeGenerator(): IAnnotationCodeGenerator$instance;
}

export type AnnotationCodeGenerator = AnnotationCodeGenerator$instance & __AnnotationCodeGenerator$views;


export interface AnnotationCodeGeneratorDependencies$instance {
    RelationalTypeMappingSource: IRelationalTypeMappingSource;
    _Clone_$(): AnnotationCodeGeneratorDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: AnnotationCodeGeneratorDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const AnnotationCodeGeneratorDependencies: {
    new(relationalTypeMappingSource: IRelationalTypeMappingSource): AnnotationCodeGeneratorDependencies;
};


export type AnnotationCodeGeneratorDependencies = AnnotationCodeGeneratorDependencies$instance;

export interface AttributeCodeFragment$instance {
    readonly Arguments: IReadOnlyList<unknown | undefined>;
    readonly NamedArguments: IReadOnlyDictionary<System_Internal.String, unknown | undefined>;
    readonly Type: Type;
}


export const AttributeCodeFragment: {
    new(type: Type, arguments: unknown[]): AttributeCodeFragment;
    new(type: Type, arguments: IEnumerable<unknown>, namedArguments: IDictionary<System_Internal.String, unknown>): AttributeCodeFragment;
};


export type AttributeCodeFragment = AttributeCodeFragment$instance;

export interface DesignTimeProviderServicesAttribute$instance extends Attribute {
    readonly TypeName: string;
}


export const DesignTimeProviderServicesAttribute: {
    new(typeName: string): DesignTimeProviderServicesAttribute;
};


export type DesignTimeProviderServicesAttribute = DesignTimeProviderServicesAttribute$instance;

export interface DesignTimeServicesReferenceAttribute$instance extends Attribute {
    readonly ForProvider: string | undefined;
    readonly TypeName: string;
}


export const DesignTimeServicesReferenceAttribute: {
    new(typeName: string): DesignTimeServicesReferenceAttribute;
    new(typeName: string, forProvider: string): DesignTimeServicesReferenceAttribute;
};


export type DesignTimeServicesReferenceAttribute = DesignTimeServicesReferenceAttribute$instance;

export interface EntityFrameworkDesignServicesBuilder$instance extends EntityFrameworkServicesBuilder {
    TryAddCoreServices(): EntityFrameworkServicesBuilder;
}


export const EntityFrameworkDesignServicesBuilder: {
    new(serviceCollection: IServiceCollection): EntityFrameworkDesignServicesBuilder;
    readonly Services: IDictionary<Type, ServiceCharacteristics>;
};


export type EntityFrameworkDesignServicesBuilder = EntityFrameworkDesignServicesBuilder$instance;

export interface EntityFrameworkRelationalDesignServicesBuilder$instance extends EntityFrameworkDesignServicesBuilder {
    TryAddCoreServices(): EntityFrameworkServicesBuilder;
}


export const EntityFrameworkRelationalDesignServicesBuilder: {
    new(serviceCollection: IServiceCollection): EntityFrameworkRelationalDesignServicesBuilder;
    readonly RelationalServices: IDictionary<Type, ServiceCharacteristics>;
};


export type EntityFrameworkRelationalDesignServicesBuilder = EntityFrameworkRelationalDesignServicesBuilder$instance;

export interface MethodCallCodeFragment$instance {
    readonly Arguments: IReadOnlyList<unknown | undefined>;
    readonly ChainedCall: MethodCallCodeFragment | undefined;
    readonly DeclaringType: string;
    readonly Method: string;
    readonly MethodInfo: MethodInfo | undefined;
    readonly Namespace: string;
    Chain(methodInfo: MethodInfo, ...arguments: unknown[]): MethodCallCodeFragment;
    Chain(method: string, ...arguments: unknown[]): MethodCallCodeFragment;
    Chain(call: MethodCallCodeFragment): MethodCallCodeFragment;
}


export const MethodCallCodeFragment: {
    new(methodInfo: MethodInfo, arguments: unknown[]): MethodCallCodeFragment;
    new(method: string, arguments: unknown[]): MethodCallCodeFragment;
};


export interface __MethodCallCodeFragment$views {
    As_IMethodCallCodeFragment(): IMethodCallCodeFragment$instance;
}

export type MethodCallCodeFragment = MethodCallCodeFragment$instance & __MethodCallCodeFragment$views;


export interface NestedClosureCodeFragment$instance {
    readonly MethodCalls: IReadOnlyList<MethodCallCodeFragment>;
    readonly Parameter: string;
}


export const NestedClosureCodeFragment: {
    new(parameter: string, methodCall: MethodCallCodeFragment): NestedClosureCodeFragment;
    new(parameter: string, methodCalls: IReadOnlyList<MethodCallCodeFragment>): NestedClosureCodeFragment;
};


export type NestedClosureCodeFragment = NestedClosureCodeFragment$instance;

export interface PropertyAccessorCodeFragment$instance {
    readonly Parameter: string;
    readonly Properties: IReadOnlyList<System_Internal.String>;
}


export const PropertyAccessorCodeFragment: {
    new(parameter: string, properties: IReadOnlyList<System_Internal.String>): PropertyAccessorCodeFragment;
};


export type PropertyAccessorCodeFragment = PropertyAccessorCodeFragment$instance;

