// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Storage.Internal
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { ValueComparer } from "../../Microsoft.EntityFrameworkCore.ChangeTracking/internal/index.js";
import type { IDiagnosticsLogger_1, IRelationalCommandDiagnosticsLogger } from "../../Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { IConcurrencyDetector, ICoreSingletonOptions, IDbContextOptions } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IAdHocMapper, IEntityType, IModel, IProperty } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { IAsyncQueryProvider } from "../../Microsoft.EntityFrameworkCore.Query/internal/index.js";
import type { JsonValueReaderWriter } from "../../Microsoft.EntityFrameworkCore.Storage.Json/internal/index.js";
import type { ValueConverter } from "../../Microsoft.EntityFrameworkCore.Storage.ValueConversion/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { CoreTypeMapping, ExecutionStrategyDependencies, IDatabaseCreator, IDatabaseFacadeDependencies, IDatabaseProvider, IDbContextTransactionManager, IExceptionDetector, IExecutionStrategy, IExecutionStrategyFactory, IParameterNameGeneratorFactory, IRawSqlCommandBuilder, IRelationalCommand, IRelationalCommandBuilderFactory, IRelationalConnection, IRelationalDatabaseFacadeDependencies, IRelationalParameter, IRelationalTypeMappingSource, ISqlGenerationHelper, ITypeMappingSource, RawSqlCommand, RelationalTypeMapping, RelationalTypeMappingInfo, StoreTypePostfix, TypeMappingInfo } from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { ValueGenerator } from "../../Microsoft.EntityFrameworkCore.ValueGeneration/internal/index.js";
import type { DbLoggerCategory_Database_Command } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import type { IEnumerable, IReadOnlyDictionary, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { DbCommand, DbParameter, DbParameterCollection } from "@tsonic/dotnet/System.Data.Common.js";
import type { DbType, ParameterDirection } from "@tsonic/dotnet/System.Data.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Byte, Exception, Func, IEquatable, Int32, Nullable, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";

export interface ICompositeJsonValueReaderWriter$instance {
    readonly innerReaderWriter: JsonValueReaderWriter;
}


export type ICompositeJsonValueReaderWriter = ICompositeJsonValueReaderWriter$instance;

export interface IJsonConvertedValueReaderWriter$instance extends ICompositeJsonValueReaderWriter {
    readonly converter: ValueConverter;
    readonly innerReaderWriter: JsonValueReaderWriter;
}


export interface IJsonConvertedValueReaderWriter$instance extends ICompositeJsonValueReaderWriter$instance {}

export type IJsonConvertedValueReaderWriter = IJsonConvertedValueReaderWriter$instance;

export interface INamedConnectionStringResolver$instance {
    resolveConnectionString(connectionString: string): string;
}


export type INamedConnectionStringResolver = INamedConnectionStringResolver$instance;

export interface CompositeRelationalParameter$instance extends RelationalParameterBase$instance {
    readonly relationalParameters: IReadOnlyList<IRelationalParameter>;
    addDbParameter(command: DbCommand, value: unknown): void;
    addDbParameter(command: DbCommand, parameterValues: IReadOnlyDictionary<System_Internal.String, unknown>): void;
}


export const CompositeRelationalParameter: {
    new(invariantName: string, relationalParameters: IReadOnlyList<IRelationalParameter>): CompositeRelationalParameter;
};


export interface __CompositeRelationalParameter$views {
    As_IRelationalParameter(): Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalParameter$instance;
}

export type CompositeRelationalParameter = CompositeRelationalParameter$instance & __CompositeRelationalParameter$views;


export interface DatabaseFacadeDependencies$instance {
    readonly adHocMapper: IAdHocMapper;
    readonly commandLogger: IDiagnosticsLogger_1<DbLoggerCategory_Database_Command>;
    readonly concurrencyDetector: IConcurrencyDetector;
    readonly coreOptions: ICoreSingletonOptions;
    readonly databaseCreator: IDatabaseCreator;
    readonly databaseProviders: IEnumerable<IDatabaseProvider>;
    readonly executionStrategy: IExecutionStrategy;
    readonly executionStrategyFactory: IExecutionStrategyFactory;
    readonly queryProvider: IAsyncQueryProvider;
    readonly transactionManager: IDbContextTransactionManager;
    readonly typeMappingSource: ITypeMappingSource;
    _Clone_$(): DatabaseFacadeDependencies;
    equals(obj: unknown): boolean;
    equals(other: DatabaseFacadeDependencies): boolean;
    getHashCode(): int;
    toString(): string;
}


export const DatabaseFacadeDependencies: {
    new(transactionManager: IDbContextTransactionManager, databaseCreator: IDatabaseCreator, executionStrategy: IExecutionStrategy, executionStrategyFactory: IExecutionStrategyFactory, databaseProviders: IEnumerable<IDatabaseProvider>, commandLogger: IDiagnosticsLogger_1<DbLoggerCategory_Database_Command>, concurrencyDetector: IConcurrencyDetector, coreOptions: ICoreSingletonOptions, queryProvider: IAsyncQueryProvider, adHocMapper: IAdHocMapper, typeMappingSource: ITypeMappingSource): DatabaseFacadeDependencies;
};


export interface __DatabaseFacadeDependencies$views {
    As_IDatabaseFacadeDependencies(): Microsoft_EntityFrameworkCore_Storage_Internal.IDatabaseFacadeDependencies$instance;
}

export interface DatabaseFacadeDependencies$instance extends Microsoft_EntityFrameworkCore_Storage_Internal.IDatabaseFacadeDependencies$instance {}

export type DatabaseFacadeDependencies = DatabaseFacadeDependencies$instance & __DatabaseFacadeDependencies$views;


export interface ExceptionDetector$instance {
    isCancellation(exception: Exception, cancellationToken: CancellationToken): boolean;
}


export const ExceptionDetector: {
    new(): ExceptionDetector;
};


export interface __ExceptionDetector$views {
    As_IExceptionDetector(): Microsoft_EntityFrameworkCore_Storage_Internal.IExceptionDetector$instance;
}

export type ExceptionDetector = ExceptionDetector$instance & __ExceptionDetector$views;


export interface ExecutionStrategyFactory$instance {
    create(): IExecutionStrategy;
}


export const ExecutionStrategyFactory: {
    new(dependencies: ExecutionStrategyDependencies): ExecutionStrategyFactory;
};


export interface __ExecutionStrategyFactory$views {
    As_IExecutionStrategyFactory(): Microsoft_EntityFrameworkCore_Storage_Internal.IExecutionStrategyFactory$instance;
}

export interface ExecutionStrategyFactory$instance extends Microsoft_EntityFrameworkCore_Storage_Internal.IExecutionStrategyFactory$instance {}

export type ExecutionStrategyFactory = ExecutionStrategyFactory$instance & __ExecutionStrategyFactory$views;


export interface NamedConnectionStringResolver$instance extends NamedConnectionStringResolverBase {
    resolveConnectionString(connectionString: string): string;
}


export const NamedConnectionStringResolver: {
    new(options: IDbContextOptions): NamedConnectionStringResolver;
};


export interface __NamedConnectionStringResolver$views {
    As_INamedConnectionStringResolver(): INamedConnectionStringResolver$instance;
}

export type NamedConnectionStringResolver = NamedConnectionStringResolver$instance & __NamedConnectionStringResolver$views;


export interface NamedConnectionStringResolverBase$instance {
    resolveConnectionString(connectionString: string): string;
}


export const NamedConnectionStringResolverBase: {
};


export type NamedConnectionStringResolverBase = NamedConnectionStringResolverBase$instance;

export interface NullTypeMapping$instance extends RelationalTypeMapping {
}


export const NullTypeMapping: {
    new(storeType: string): NullTypeMapping;
    readonly default_: NullTypeMapping;
};


export type NullTypeMapping = NullTypeMapping$instance;

export interface RawRelationalParameter$instance extends RelationalParameterBase$instance {
    addDbParameter(command: DbCommand, parameterValues: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    addDbParameter(command: DbCommand, value: unknown): void;
    addDbParameter(command: DbCommand, parameterValues: IReadOnlyDictionary<System_Internal.String, unknown>): void;
}


export const RawRelationalParameter: {
    new(invariantName: string, parameter: DbParameter): RawRelationalParameter;
};


export interface __RawRelationalParameter$views {
    As_IRelationalParameter(): Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalParameter$instance;
}

export type RawRelationalParameter = RawRelationalParameter$instance & __RawRelationalParameter$views;


export interface RawSqlCommandBuilder$instance {
    build(sql: string): IRelationalCommand;
    build(sql: string, parameters: IEnumerable<unknown>): RawSqlCommand;
    build(sql: string, parameters: IEnumerable<unknown>, model: IModel): RawSqlCommand;
}


export const RawSqlCommandBuilder: {
    new(relationalCommandBuilderFactory: IRelationalCommandBuilderFactory, sqlGenerationHelper: ISqlGenerationHelper, parameterNameGeneratorFactory: IParameterNameGeneratorFactory, typeMappingSource: IRelationalTypeMappingSource): RawSqlCommandBuilder;
};


export interface __RawSqlCommandBuilder$views {
    As_IRawSqlCommandBuilder(): Microsoft_EntityFrameworkCore_Storage_Internal.IRawSqlCommandBuilder$instance;
}

export interface RawSqlCommandBuilder$instance extends Microsoft_EntityFrameworkCore_Storage_Internal.IRawSqlCommandBuilder$instance {}

export type RawSqlCommandBuilder = RawSqlCommandBuilder$instance & __RawSqlCommandBuilder$views;


export interface RelationalDatabaseFacadeDependencies$instance {
    readonly adHocMapper: IAdHocMapper;
    readonly commandLogger: IRelationalCommandDiagnosticsLogger;
    readonly concurrencyDetector: IConcurrencyDetector;
    readonly coreOptions: ICoreSingletonOptions;
    readonly databaseCreator: IDatabaseCreator;
    readonly databaseProviders: IEnumerable<IDatabaseProvider>;
    readonly executionStrategy: IExecutionStrategy;
    readonly executionStrategyFactory: IExecutionStrategyFactory;
    readonly queryProvider: IAsyncQueryProvider;
    readonly rawSqlCommandBuilder: IRawSqlCommandBuilder;
    readonly relationalConnection: IRelationalConnection;
    readonly transactionManager: IDbContextTransactionManager;
    readonly typeMappingSource: ITypeMappingSource;
    _Clone_$(): RelationalDatabaseFacadeDependencies;
    equals(obj: unknown): boolean;
    equals(other: RelationalDatabaseFacadeDependencies): boolean;
    getHashCode(): int;
    toString(): string;
}


export const RelationalDatabaseFacadeDependencies: {
    new(transactionManager: IDbContextTransactionManager, databaseCreator: IDatabaseCreator, executionStrategy: IExecutionStrategy, executionStrategyFactory: IExecutionStrategyFactory, databaseProviders: IEnumerable<IDatabaseProvider>, commandLogger: IRelationalCommandDiagnosticsLogger, concurrencyDetector: IConcurrencyDetector, relationalConnection: IRelationalConnection, rawSqlCommandBuilder: IRawSqlCommandBuilder, coreOptions: ICoreSingletonOptions, queryProvider: IAsyncQueryProvider, adHocMapper: IAdHocMapper, relationalTypeMappingSource: IRelationalTypeMappingSource): RelationalDatabaseFacadeDependencies;
};


export interface __RelationalDatabaseFacadeDependencies$views {
    As_IDatabaseFacadeDependencies(): Microsoft_EntityFrameworkCore_Storage_Internal.IDatabaseFacadeDependencies$instance;
    As_IRelationalDatabaseFacadeDependencies(): Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalDatabaseFacadeDependencies$instance;
}

export interface RelationalDatabaseFacadeDependencies$instance extends Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalDatabaseFacadeDependencies$instance {}

export type RelationalDatabaseFacadeDependencies = RelationalDatabaseFacadeDependencies$instance & __RelationalDatabaseFacadeDependencies$views;


export interface RelationalParameterBase$instance {
    readonly invariantName: string;
    addDbParameter(command: DbCommand, value: unknown): void;
    addDbParameter(command: DbCommand, parameterValues: IReadOnlyDictionary<System_Internal.String, unknown>): void;
}


export const RelationalParameterBase: {
};


export interface __RelationalParameterBase$views {
    As_IRelationalParameter(): Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalParameter$instance;
}

export type RelationalParameterBase = RelationalParameterBase$instance & __RelationalParameterBase$views;


export interface TypeMappedRelationalParameter$instance extends RelationalParameterBase$instance {
    readonly direction: ParameterDirection;
    readonly name: string;
    addDbParameter(command: DbCommand, value: unknown): void;
    addDbParameter(command: DbCommand, parameterValues: IReadOnlyDictionary<System_Internal.String, unknown>): void;
}


export const TypeMappedRelationalParameter: {
    new(invariantName: string, name: string, relationalTypeMapping: RelationalTypeMapping, nullable: Nullable<System_Internal.Boolean>, direction: ParameterDirection): TypeMappedRelationalParameter;
};


export interface __TypeMappedRelationalParameter$views {
    As_IRelationalParameter(): Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalParameter$instance;
}

export type TypeMappedRelationalParameter = TypeMappedRelationalParameter$instance & __TypeMappedRelationalParameter$views;


export abstract class DbParameterCollectionExtensions$instance {
    static formatParameter(parameter: DbParameter, logParameterValues: boolean): string;
    static formatParameter(name: string, value: unknown, hasValue: boolean, direction: ParameterDirection, dbType: DbType, nullable: boolean, size: int, precision: byte, scale: byte): string;
    static formatParameters(parameters: DbParameterCollection, logParameterValues: boolean): string;
}


export type DbParameterCollectionExtensions = DbParameterCollectionExtensions$instance;

