// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Migrations.Operations
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';

// Cross-namespace type imports for constraints
import type { Annotatable, Annotation, IAnnotatable, IAnnotation, IReadOnlyAnnotatable } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
import type { ICheckConstraint, IForeignKeyConstraint, IMutableAnnotatable, IPrimaryKeyConstraint, ITableIndex, IUniqueConstraint } from './Microsoft.EntityFrameworkCore.Metadata/internal/index.js';
import type { ReferentialAction } from './Microsoft.EntityFrameworkCore.Migrations/internal/index.js';
import type { IEnumerable, IReadOnlyDictionary, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, Func, Int32, Int64, Nullable, Object as ClrObject, String as ClrString, Type, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { AddCheckConstraintOperation as AddCheckConstraintOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AddColumnOperation as AddColumnOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AddForeignKeyOperation as AddForeignKeyOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AddPrimaryKeyOperation as AddPrimaryKeyOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AddUniqueConstraintOperation as AddUniqueConstraintOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AlterColumnOperation as AlterColumnOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AlterDatabaseOperation as AlterDatabaseOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AlterSequenceOperation as AlterSequenceOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { AlterTableOperation as AlterTableOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { ColumnOperation as ColumnOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { CreateIndexOperation as CreateIndexOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { CreateSequenceOperation as CreateSequenceOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { CreateTableOperation as CreateTableOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DatabaseOperation as DatabaseOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DeleteDataOperation as DeleteDataOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropCheckConstraintOperation as DropCheckConstraintOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropColumnOperation as DropColumnOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropForeignKeyOperation as DropForeignKeyOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropIndexOperation as DropIndexOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropPrimaryKeyOperation as DropPrimaryKeyOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropSchemaOperation as DropSchemaOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropSequenceOperation as DropSequenceOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropTableOperation as DropTableOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { DropUniqueConstraintOperation as DropUniqueConstraintOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { EnsureSchemaOperation as EnsureSchemaOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export type IAlterMigrationOperation = Internal.IAlterMigrationOperation;
export { InsertDataOperation as InsertDataOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export type ITableMigrationOperation = Internal.ITableMigrationOperation;
export { MigrationOperation as MigrationOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { RenameColumnOperation as RenameColumnOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { RenameIndexOperation as RenameIndexOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { RenameSequenceOperation as RenameSequenceOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { RenameTableOperation as RenameTableOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { RestartSequenceOperation as RestartSequenceOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { SequenceOperation as SequenceOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { SqlOperation as SqlOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { TableOperation as TableOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
export { UpdateDataOperation as UpdateDataOperation } from './Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js';
