// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Storage
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';

// Cross-namespace type imports for constraints
import type { ValueComparer } from './Microsoft.EntityFrameworkCore.ChangeTracking/internal/index.js';
import type { CommandSource, DbCommandMethod, IDiagnosticsLogger_1, ILoggingOptions, IRelationalCommandDiagnosticsLogger, IRelationalConnectionDiagnosticsLogger } from './Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js';
import type { IConcurrencyDetector, ICoreSingletonOptions, ICurrentDbContext, IDbContextOptions, IDbContextOptionsExtension, IInfrastructure_1, IResettableService } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
import type { IAdHocMapper, IElementType, IEntityType, IModel, IProperty, IPropertyBase, ITypeMappingConfiguration } from './Microsoft.EntityFrameworkCore.Metadata/internal/index.js';
import type { IMigrationCommandExecutor, IMigrationsModelDiffer, IMigrationsSqlGenerator, MigrationCommand, MigrationsSqlGenerationOptions } from './Microsoft.EntityFrameworkCore.Migrations/internal/index.js';
import type { IAsyncQueryProvider, IQueryCompilationContextFactory, QueryContext } from './Microsoft.EntityFrameworkCore.Query/internal/index.js';
import type { INamedConnectionStringResolver } from './Microsoft.EntityFrameworkCore.Storage.Internal/internal/index.js';
import type { IJsonValueReaderWriterSource, JsonValueReaderWriter } from './Microsoft.EntityFrameworkCore.Storage.Json/internal/index.js';
import type { IValueConverterSelector, ValueConverter, ValueConverter_2, ValueConverterInfo } from './Microsoft.EntityFrameworkCore.Storage.ValueConversion/internal/index.js';
import type { IBatchExecutor, ICommandBatchPreparer, IUpdateAdapterFactory, IUpdateEntry } from './Microsoft.EntityFrameworkCore.Update/internal/index.js';
import type { ValueGenerator } from './Microsoft.EntityFrameworkCore.ValueGeneration/internal/index.js';
import type { DbContext, DbLoggerCategory_Database_Command, DbLoggerCategory_Database_Transaction, DbLoggerCategory_Infrastructure, DbLoggerCategory_Update } from './Microsoft.EntityFrameworkCore/internal/index.js';
import type { IEnumerable, IList, IReadOnlyDictionary, IReadOnlyList, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { DbCommand, DbConnection, DbDataReader, DbParameter, DbTransaction } from '@tsonic/dotnet/System.Data.Common.js';
import type { DbType, IsolationLevel, ParameterDirection } from '@tsonic/dotnet/System.Data.js';
import type { Action, Boolean as ClrBoolean, Enum, Exception, FormattableString, Func, Guid, IAsyncDisposable, IComparable, IConvertible, IDisposable, IEquatable, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, Random, String as ClrString, TimeSpan, Type, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { Expression, LambdaExpression } from '@tsonic/dotnet/System.Linq.Expressions.js';
import type { ConstructorInfo, MemberInfo, MethodInfo } from '@tsonic/dotnet/System.Reflection.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { StringBuilder } from '@tsonic/dotnet/System.Text.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { Transaction } from '@tsonic/dotnet/System.Transactions.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CoreTypeMapping as CoreTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { Database as Database } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DatabaseDependencies as DatabaseDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DatabaseProvider_1 as DatabaseProvider } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DatabaseProviderDependencies as DatabaseProviderDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ExecutionResult_1 as ExecutionResult } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ExecutionStrategy as ExecutionStrategy } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ExecutionStrategyDependencies as ExecutionStrategyDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export type IDatabase = Internal.IDatabase;
export type IDatabaseCreator = Internal.IDatabaseCreator;
export type IDatabaseFacadeDependencies = Internal.IDatabaseFacadeDependencies;
export type IDatabaseFacadeDependenciesAccessor = Internal.IDatabaseFacadeDependenciesAccessor;
export type IDatabaseProvider = Internal.IDatabaseProvider;
export type IDbContextTransaction = Internal.IDbContextTransaction;
export type IDbContextTransactionManager = Internal.IDbContextTransactionManager;
export type IExceptionDetector = Internal.IExceptionDetector;
export type IExecutionStrategy = Internal.IExecutionStrategy;
export type IExecutionStrategyFactory = Internal.IExecutionStrategyFactory;
export type ITransactionEnlistmentManager = Internal.ITransactionEnlistmentManager;
export type ITypeMappingSource = Internal.ITypeMappingSource;
export type ITypeMappingSourcePlugin = Internal.ITypeMappingSourcePlugin;
export { MaterializationContext as MaterializationContext } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { NonRetryingExecutionStrategy as NonRetryingExecutionStrategy } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RetryLimitExceededException as RetryLimitExceededException } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TypeMappingInfo as TypeMappingInfo } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TypeMappingSource as TypeMappingSource } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TypeMappingSourceBase as TypeMappingSourceBase } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TypeMappingSourceDependencies as TypeMappingSourceDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ValueBuffer as ValueBuffer } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { BoolTypeMapping as BoolTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ByteArrayTypeMapping as ByteArrayTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ByteTypeMapping as ByteTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { CharTypeMapping as CharTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DateOnlyTypeMapping as DateOnlyTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DateTimeOffsetTypeMapping as DateTimeOffsetTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DateTimeTypeMapping as DateTimeTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DbContextTransactionExtensions$instance as DbContextTransactionExtensions } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DecimalTypeMapping as DecimalTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { DoubleTypeMapping as DoubleTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { FloatTypeMapping as FloatTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { GuidTypeMapping as GuidTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { IntTypeMapping as IntTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export type IParameterNameGeneratorFactory = Internal.IParameterNameGeneratorFactory;
export type IRawSqlCommandBuilder = Internal.IRawSqlCommandBuilder;
export type IRelationalCommand = Internal.IRelationalCommand;
export type IRelationalCommandBuilder = Internal.IRelationalCommandBuilder;
export type IRelationalCommandBuilderFactory = Internal.IRelationalCommandBuilderFactory;
export type IRelationalCommandTemplate = Internal.IRelationalCommandTemplate;
export type IRelationalConnection = Internal.IRelationalConnection;
export type IRelationalDatabaseCreator = Internal.IRelationalDatabaseCreator;
export type IRelationalDatabaseFacadeDependencies = Internal.IRelationalDatabaseFacadeDependencies;
export type IRelationalParameter = Internal.IRelationalParameter;
export type IRelationalTransactionFactory = Internal.IRelationalTransactionFactory;
export type IRelationalTransactionManager = Internal.IRelationalTransactionManager;
export type IRelationalTypeMappingSource = Internal.IRelationalTypeMappingSource;
export type IRelationalTypeMappingSourcePlugin = Internal.IRelationalTypeMappingSourcePlugin;
export type ISqlGenerationHelper = Internal.ISqlGenerationHelper;
export { JsonTypeMapping as JsonTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { JsonTypePlaceholder as JsonTypePlaceholder } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { LongTypeMapping as LongTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ParameterNameGenerator as ParameterNameGenerator } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ParameterNameGeneratorDependencies as ParameterNameGeneratorDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ParameterNameGeneratorFactory as ParameterNameGeneratorFactory } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RawSqlCommand as RawSqlCommand } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalCommand as RelationalCommand } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalCommandBuilder as RelationalCommandBuilder } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalCommandBuilderDependencies as RelationalCommandBuilderDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalCommandBuilderExtensions$instance as RelationalCommandBuilderExtensions } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalCommandBuilderFactory as RelationalCommandBuilderFactory } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalCommandParameterObject as RelationalCommandParameterObject } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalConnection as RelationalConnection } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalConnectionDependencies as RelationalConnectionDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalDatabase as RelationalDatabase } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalDatabaseCreator as RelationalDatabaseCreator } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalDatabaseCreatorDependencies as RelationalDatabaseCreatorDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalDatabaseDependencies as RelationalDatabaseDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalDataReader as RelationalDataReader } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalExecutionStrategyExtensions$instance as RelationalExecutionStrategyExtensions } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalExecutionStrategyFactory as RelationalExecutionStrategyFactory } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalGeometryTypeMapping_2 as RelationalGeometryTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalSqlGenerationHelper as RelationalSqlGenerationHelper } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalSqlGenerationHelperDependencies as RelationalSqlGenerationHelperDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTransaction as RelationalTransaction } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTransactionFactory as RelationalTransactionFactory } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTransactionFactoryDependencies as RelationalTransactionFactoryDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTypeMapping as RelationalTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTypeMappingInfo as RelationalTypeMappingInfo } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTypeMappingSource as RelationalTypeMappingSource } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTypeMappingSourceDependencies as RelationalTypeMappingSourceDependencies } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { RelationalTypeMappingSourceExtensions$instance as RelationalTypeMappingSourceExtensions } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { SByteTypeMapping as SByteTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ShortTypeMapping as ShortTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { StoreTypePostfix as StoreTypePostfix } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { StringTypeMapping as StringTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TimeOnlyTypeMapping as TimeOnlyTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TimeSpanTypeMapping as TimeSpanTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { TypeMaterializationInfo as TypeMaterializationInfo } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { UIntTypeMapping as UIntTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { ULongTypeMapping as ULongTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';
export { UShortTypeMapping as UShortTypeMapping } from './Microsoft.EntityFrameworkCore.Storage/internal/index.js';

// Multi-arity family value exports (arity-0 constructors/static namespaces)
export const ReaderColumn: typeof Internal.ReaderColumn;

// Multi-arity family sentinel (detects unspecified type parameters)
declare const __unspecified: unique symbol;
export type __ = typeof __unspecified;

export type ReaderColumn<
  T1 = __,
> =
  [T1] extends [__] ? Internal.ReaderColumn :
  Internal.ReaderColumn_1<T1>;

// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_EntityFrameworkCore_Storage as ExtensionMethods } from './__internal/extensions/index.js';

