// Generated by tsbindgen - Architecture
// Namespace: System.Transactions
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Transactions/internal/index.js';

// Cross-namespace type imports for constraints
import type { DatabaseFacade } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
import type { Object as ClrObject, Void } from '@tsonic/dotnet/System.js';
import type { Transaction } from '@tsonic/dotnet/System.Transactions.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { TransactionsDatabaseFacadeExtensions$instance as TransactionsDatabaseFacadeExtensions } from './System.Transactions/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_System_Transactions as ExtensionMethods } from './__internal/extensions/index.js';

