// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Migrations.Internal
// Assembly: Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { IDiagnosticsLogger_1, IRelationalCommandDiagnosticsLogger } from "../../Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { IAnnotation, ICurrentDbContext, IDbContextOptions, IModelRuntimeInitializer, ModelSnapshot } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { ICheckConstraint, IColumn, IDesignTimeModel, IForeignKeyConstraint, IRelationalAnnotationProvider, IRelationalModel, ISequence, ITable, ITableIndex, IUniqueConstraint } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { MigrationOperation } from "../../Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Internal from "../../Microsoft.EntityFrameworkCore.Migrations/internal/index.js";
import type { IHistoryRepository, IMigrationCommandExecutor, IMigrationsAnnotationProvider, IMigrationsAssembly, IMigrationsIdGenerator, IMigrationsModelDiffer, IMigrationsSqlGenerator, IMigrator, Migration, MigrationCommand, MigrationExecutionState, MigrationsSqlGenerationOptions } from "../../Microsoft.EntityFrameworkCore.Migrations/internal/index.js";
import type { IDatabaseCreator, IDatabaseProvider, IExecutionStrategy, IRawSqlCommandBuilder, IRelationalConnection, IRelationalTypeMappingSource, ISqlGenerationHelper } from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { CommandBatchPreparerDependencies, IRowIdentityMapFactory } from "../../Microsoft.EntityFrameworkCore.Update.Internal/internal/index.js";
import type { DbLoggerCategory_Migrations } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import type { IEnumerable_1, IReadOnlyDictionary_2, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IsolationLevel } from "@tsonic/dotnet/System.Data/internal/index.js";
import type { Assembly, TypeInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import type { Task, Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Func_3, Func_4, Int32, Nullable_1, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface MigrationCommandExecutor$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationCommandExecutor: never;

    ExecuteNonQuery(migrationCommands: IEnumerable_1<MigrationCommand>, connection: IRelationalConnection): void;
    ExecuteNonQuery(migrationCommands: IReadOnlyList_1<MigrationCommand>, connection: IRelationalConnection, executionState: MigrationExecutionState, commitTransaction: boolean, isolationLevel?: Nullable_1<IsolationLevel>): int;
    ExecuteNonQueryAsync(migrationCommands: IEnumerable_1<MigrationCommand>, connection: IRelationalConnection, cancellationToken?: CancellationToken): Task;
    ExecuteNonQueryAsync(migrationCommands: IReadOnlyList_1<MigrationCommand>, connection: IRelationalConnection, executionState: MigrationExecutionState, commitTransaction: boolean, isolationLevel?: Nullable_1<IsolationLevel>, cancellationToken?: CancellationToken): Task_1<System_Internal.Int32>;
}


export const MigrationCommandExecutor: {
    new(executionStrategy: IExecutionStrategy): MigrationCommandExecutor;
};


export interface __MigrationCommandExecutor$views {
    As_IMigrationCommandExecutor(): Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationCommandExecutor$instance;
}

export interface MigrationCommandExecutor$instance extends Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationCommandExecutor {}

export type MigrationCommandExecutor = MigrationCommandExecutor$instance & __MigrationCommandExecutor$views;


export interface MigrationsAssembly$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsAssembly: never;

    readonly Assembly: Assembly;
    readonly Migrations: IReadOnlyDictionary_2<System_Internal.String, TypeInfo>;
    readonly ModelSnapshot: ModelSnapshot | undefined;
    CreateMigration(migrationClass: TypeInfo, activeProvider: string): Migration;
    FindMigrationId(nameOrId: string): string | undefined;
}


export const MigrationsAssembly: {
    new(currentContext: ICurrentDbContext, options: IDbContextOptions, idGenerator: IMigrationsIdGenerator, logger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>): MigrationsAssembly;
};


export interface __MigrationsAssembly$views {
    As_IMigrationsAssembly(): Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationsAssembly$instance;
}

export interface MigrationsAssembly$instance extends Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationsAssembly {}

export type MigrationsAssembly = MigrationsAssembly$instance & __MigrationsAssembly$views;


export interface MigrationsIdGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsIdGenerator: never;

    GenerateId(name: string): string;
    GetName(id: string): string;
    IsValidId(value: string): boolean;
}


export const MigrationsIdGenerator: {
    new(): MigrationsIdGenerator;
};


export interface __MigrationsIdGenerator$views {
    As_IMigrationsIdGenerator(): Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationsIdGenerator$instance;
}

export interface MigrationsIdGenerator$instance extends Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationsIdGenerator {}

export type MigrationsIdGenerator = MigrationsIdGenerator$instance & __MigrationsIdGenerator$views;


export interface MigrationsModelDiffer$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsModelDiffer: never;

    readonly CommandBatchPreparerDependencies: CommandBatchPreparerDependencies;
    readonly MigrationsAnnotationProvider: IMigrationsAnnotationProvider;
    readonly RelationalAnnotationProvider: IRelationalAnnotationProvider;
    readonly RowIdentityMapFactory: IRowIdentityMapFactory;
    readonly TypeMappingSource: IRelationalTypeMappingSource;
    Add(target: IRelationalModel, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: string, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: ITable, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: IColumn, diffContext: unknown, inline?: boolean): IEnumerable_1<MigrationOperation>;
    Add(target: IUniqueConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: IForeignKeyConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: ITableIndex, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: ICheckConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Add(target: ISequence, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IRelationalModel, target: IRelationalModel, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<System_Internal.String>, target: IEnumerable_1<System_Internal.String>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: string, target: string, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<ITable>, target: IEnumerable_1<ITable>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: ITable, target: ITable, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<IColumn>, target: IEnumerable_1<IColumn>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IColumn, target: IColumn, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<IUniqueConstraint>, target: IEnumerable_1<IUniqueConstraint>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IUniqueConstraint, target: IUniqueConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<IForeignKeyConstraint>, target: IEnumerable_1<IForeignKeyConstraint>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IForeignKeyConstraint, target: IForeignKeyConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<ITableIndex>, target: IEnumerable_1<ITableIndex>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: ITableIndex, target: ITableIndex, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<ICheckConstraint>, target: IEnumerable_1<ICheckConstraint>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: ICheckConstraint, target: ICheckConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: IEnumerable_1<ISequence>, target: IEnumerable_1<ISequence>, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Diff(source: ISequence, target: ISequence, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    DiffCollection<T>(sources: IEnumerable_1<T>, targets: IEnumerable_1<T>, diffContext: unknown, diff: Func_4<T, T, unknown, IEnumerable_1<MigrationOperation>>, add: Func_3<T, unknown, IEnumerable_1<MigrationOperation>>, remove: Func_3<T, unknown, IEnumerable_1<MigrationOperation>>, ...predicates: Func_4<T, T, unknown, System_Internal.Boolean>[]): IEnumerable_1<MigrationOperation>;
    DiffData(source: IRelationalModel, target: IRelationalModel, diffContext: unknown): void;
    GetDataOperations(source: IRelationalModel, target: IRelationalModel, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    GetDefaultValue(type: Type): unknown | undefined;
    GetDifferences(source: IRelationalModel, target: IRelationalModel): IReadOnlyList_1<MigrationOperation>;
    GetSchemas(model: IRelationalModel): IEnumerable_1<System_Internal.String>;
    HasDifferences(source: IRelationalModel, target: IRelationalModel): boolean;
    HasDifferences(source: IEnumerable_1<IAnnotation>, target: IEnumerable_1<IAnnotation>): boolean;
    Remove(source: IRelationalModel, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: string, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: ITable, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: IColumn, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: IUniqueConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: IForeignKeyConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: ITableIndex, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: ICheckConstraint, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Remove(source: ISequence, diffContext: unknown): IEnumerable_1<MigrationOperation>;
    Sort(operations: IEnumerable_1<MigrationOperation>, diffContext: unknown): IReadOnlyList_1<MigrationOperation>;
    TrackData(source: IRelationalModel, target: IRelationalModel, diffContext: unknown): void;
}


export const MigrationsModelDiffer: {
    new(typeMappingSource: IRelationalTypeMappingSource, migrationsAnnotationProvider: IMigrationsAnnotationProvider, relationalAnnotationProvider: IRelationalAnnotationProvider, rowIdentityMapFactory: IRowIdentityMapFactory, commandBatchPreparerDependencies: CommandBatchPreparerDependencies): MigrationsModelDiffer;
};


export interface __MigrationsModelDiffer$views {
    As_IMigrationsModelDiffer(): Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationsModelDiffer$instance;
}

export interface MigrationsModelDiffer$instance extends Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrationsModelDiffer {}

export type MigrationsModelDiffer = MigrationsModelDiffer$instance & __MigrationsModelDiffer$views;


export interface Migrator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrator: never;

    readonly MigrationTransactionIsolationLevel: Nullable_1<IsolationLevel>;
    GenerateDownSql(migration: Migration, previousMigration: Migration, options?: MigrationsSqlGenerationOptions): IReadOnlyList_1<MigrationCommand>;
    GenerateScript(fromMigration?: string, toMigration?: string, options?: MigrationsSqlGenerationOptions): string;
    GenerateUpSql(migration: Migration, options?: MigrationsSqlGenerationOptions): IReadOnlyList_1<MigrationCommand>;
    HasPendingModelChanges(): boolean;
    Migrate(targetMigration: string): void;
    MigrateAsync(targetMigration: string, cancellationToken?: CancellationToken): Task;
    PopulateMigrations(appliedMigrationEntries: IEnumerable_1<System_Internal.String>, targetMigration: string, parameters: MigratorData): void;
    VerifyMigrationSucceeded(targetMigration: string, state: MigrationExecutionState): boolean;
    VerifyMigrationSucceededAsync(targetMigration: string, state: MigrationExecutionState, cancellationToken: CancellationToken): Task_1<System_Internal.Boolean>;
}


export const Migrator: {
    new(migrationsAssembly: IMigrationsAssembly, historyRepository: IHistoryRepository, databaseCreator: IDatabaseCreator, migrationsSqlGenerator: IMigrationsSqlGenerator, rawSqlCommandBuilder: IRawSqlCommandBuilder, migrationCommandExecutor: IMigrationCommandExecutor, connection: IRelationalConnection, sqlGenerationHelper: ISqlGenerationHelper, currentContext: ICurrentDbContext, modelRuntimeInitializer: IModelRuntimeInitializer, logger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>, commandLogger: IRelationalCommandDiagnosticsLogger, databaseProvider: IDatabaseProvider, migrationsModelDiffer: IMigrationsModelDiffer, designTimeModel: IDesignTimeModel, contextOptions: IDbContextOptions, executionStrategy: IExecutionStrategy): Migrator;
};


export interface __Migrator$views {
    As_IMigrator(): Microsoft_EntityFrameworkCore_Migrations_Internal.IMigrator$instance;
}

export type Migrator = Migrator$instance & __Migrator$views;


export interface MigratorData$instance {
    readonly AppliedMigrations: IReadOnlyList_1<Migration>;
    readonly RevertedMigrations: IReadOnlyList_1<Migration>;
    readonly TargetMigration: Migration | undefined;
}


export const MigratorData: {
    new(appliedMigrations: IReadOnlyList_1<Migration>, revertedMigrations: IReadOnlyList_1<Migration>, targetMigration: Migration): MigratorData;
};


export type MigratorData = MigratorData$instance;

export abstract class MigrationExtensions$instance {
    static GetId(migration: Migration): string;
}


export type MigrationExtensions = MigrationExtensions$instance;

