// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Design.Internal
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { ValueComparer } from "../../Microsoft.EntityFrameworkCore.ChangeTracking/internal/index.js";
import type { ICSharpHelper } from "../../Microsoft.EntityFrameworkCore.Design/internal/index.js";
import type { IndentedStringBuilder } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { ICheckConstraint, IColumn, IColumnBase, IComplexProperty, IComplexType, IDbFunction, IDbFunctionParameter, IElementType, IEntityType, IEntityTypeMappingFragment, IForeignKey, IForeignKeyConstraint, IFunctionColumn, IFunctionMapping, IIndex, IKey, IModel, INavigation, IProperty, IRelationalModel, IRelationalPropertyOverrides, ISequence, IServiceProperty, ISkipNavigation, ISqlQuery, ISqlQueryColumn, ISqlQueryMapping, IStoredProcedure, IStoredProcedureMapping, IStoredProcedureParameter, IStoredProcedureResultColumn, IStoreFunction, IStoreFunctionParameter, IStoreStoredProcedure, IStoreStoredProcedureParameter, IStoreStoredProcedureResultColumn, ITable, ITableBase, ITableIndex, ITableMapping, ITableMappingBase, ITrigger, ITypeBase, ITypeMappingConfiguration, IUniqueConstraint, IView, IViewColumn, IViewMapping } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { JsonValueReaderWriter } from "../../Microsoft.EntityFrameworkCore.Storage.Json/internal/index.js";
import type { ValueConverter } from "../../Microsoft.EntityFrameworkCore.Storage.ValueConversion/internal/index.js";
import type { CoreTypeMapping } from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { Dictionary_2, IDictionary_2, IReadOnlyDictionary_2, ISet_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, IEquatable_1, Int32, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface ICSharpRuntimeAnnotationCodeGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_Internal_ICSharpRuntimeAnnotationCodeGenerator: never;

    Create(comparer: ValueComparer, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Create(typeMapping: CoreTypeMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, valueComparer?: ValueComparer, keyValueComparer?: ValueComparer, providerValueComparer?: ValueComparer): boolean;
    Create(typeMapping: CoreTypeMapping, property: IProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): boolean;
    Create(converter: ValueConverter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(complexProperty: IComplexProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(complexType: IComplexType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(elementType: IElementType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(entityType: IEntityType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(foreignKey: IForeignKey, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(index: IIndex, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(key: IKey, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(model: IModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(navigation: INavigation, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IServiceProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(navigation: ISkipNavigation, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(trigger: ITrigger, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(typeConfiguration: ITypeMappingConfiguration, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
}


export type ICSharpRuntimeAnnotationCodeGenerator = ICSharpRuntimeAnnotationCodeGenerator$instance;

export interface QualifiedName$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_Internal_QualifiedName: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    Name: string;
    Namespace: string;
    Deconstruct(Name: string, Namespace: string): void;
    Equals(obj: unknown): boolean;
    Equals(other: QualifiedName): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const QualifiedName: {
    new(Name: string, Namespace: string): QualifiedName;
};


export type QualifiedName = QualifiedName$instance;

export interface CSharpRuntimeAnnotationCodeGenerator$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_Internal_CSharpRuntimeAnnotationCodeGenerator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_Internal_ICSharpRuntimeAnnotationCodeGenerator: never;

    readonly Dependencies: CSharpRuntimeAnnotationCodeGeneratorDependencies;
    Create(converter: ValueConverter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Create(comparer: ValueComparer, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Create(typeMapping: CoreTypeMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, valueComparer?: ValueComparer, keyValueComparer?: ValueComparer, providerValueComparer?: ValueComparer): boolean;
    CreateDefaultTypeMapping(typeMapping: CoreTypeMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): CoreTypeMapping | undefined;
    Generate(model: IModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(entityType: IEntityType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(complexProperty: IComplexProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(complexType: IComplexType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IServiceProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(elementType: IElementType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(key: IKey, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(foreignKey: IForeignKey, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(navigation: INavigation, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(navigation: ISkipNavigation, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(index: IIndex, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(trigger: ITrigger, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(typeConfiguration: ITypeMappingConfiguration, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    GenerateSimpleAnnotation(annotationName: string, valueString: string, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    GenerateSimpleAnnotations(parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
}


export const CSharpRuntimeAnnotationCodeGenerator: {
    new(dependencies: CSharpRuntimeAnnotationCodeGeneratorDependencies): CSharpRuntimeAnnotationCodeGenerator;
    AddNamespace(type: Type, namespaces: ISet_1<System_Internal.String>): void;
    Create(comparer: ValueComparer, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, codeHelper: ICSharpHelper): void;
    Create(converter: ValueConverter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, codeHelper: ICSharpHelper): void;
    CreateJsonValueReaderWriter(jsonValueReaderWriter: JsonValueReaderWriter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, codeHelper: ICSharpHelper): void;
    CreateJsonValueReaderWriter(jsonValueReaderWriterType: Type, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, codeHelper: ICSharpHelper): void;
};


export interface __CSharpRuntimeAnnotationCodeGenerator$views {
    As_ICSharpRuntimeAnnotationCodeGenerator(): ICSharpRuntimeAnnotationCodeGenerator$instance;
}

export type CSharpRuntimeAnnotationCodeGenerator = CSharpRuntimeAnnotationCodeGenerator$instance & __CSharpRuntimeAnnotationCodeGenerator$views;


export interface CSharpRuntimeAnnotationCodeGeneratorDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_Internal_CSharpRuntimeAnnotationCodeGeneratorDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    CSharpHelper: ICSharpHelper;
    _Clone_$(): CSharpRuntimeAnnotationCodeGeneratorDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: CSharpRuntimeAnnotationCodeGeneratorDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const CSharpRuntimeAnnotationCodeGeneratorDependencies: {
    new(cSharpHelper: ICSharpHelper): CSharpRuntimeAnnotationCodeGeneratorDependencies;
};


export type CSharpRuntimeAnnotationCodeGeneratorDependencies = CSharpRuntimeAnnotationCodeGeneratorDependencies$instance;

export interface CSharpRuntimeAnnotationCodeGeneratorParameters$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_Internal_CSharpRuntimeAnnotationCodeGeneratorParameters: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    Annotations: IDictionary_2<System_Internal.String, unknown | undefined>;
    ClassName: string;
    ConfigurationClassNames: IReadOnlyDictionary_2<ITypeBase, System_Internal.String>;
    ForNativeAot: boolean;
    IsRuntime: boolean;
    MainBuilder: IndentedStringBuilder;
    MethodBuilder: IndentedStringBuilder;
    Namespace: string;
    Namespaces: ISet_1<System_Internal.String>;
    ScopeObjects: IDictionary_2<System_Internal.String, unknown>;
    ScopeVariables: IDictionary_2<unknown, System_Internal.String>;
    TargetName: string;
    UseNullableReferenceTypes: boolean;
    _Clone_$(): CSharpRuntimeAnnotationCodeGeneratorParameters;
    Equals(obj: unknown): boolean;
    Equals(other: CSharpRuntimeAnnotationCodeGeneratorParameters): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const CSharpRuntimeAnnotationCodeGeneratorParameters: {
    new(targetName: string, className: string, namespace: string, mainBuilder: IndentedStringBuilder, methodBuilder: IndentedStringBuilder, namespaces: ISet_1<System_Internal.String>, scopeObjects: IDictionary_2<System_Internal.String, unknown>, scopeVariables: IDictionary_2<unknown, System_Internal.String>, configurationClassNames: Dictionary_2<ITypeBase, System_Internal.String>, nullable: boolean, nativeAot: boolean): CSharpRuntimeAnnotationCodeGeneratorParameters;
};


export type CSharpRuntimeAnnotationCodeGeneratorParameters = CSharpRuntimeAnnotationCodeGeneratorParameters$instance;

export interface RelationalCSharpRuntimeAnnotationCodeGenerator$instance extends CSharpRuntimeAnnotationCodeGenerator$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_Internal_RelationalCSharpRuntimeAnnotationCodeGenerator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_Internal_ICSharpRuntimeAnnotationCodeGenerator: never;

    readonly RelationalDependencies: RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies;
    Create(typeMapping: CoreTypeMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, valueComparer?: ValueComparer, keyValueComparer?: ValueComparer, providerValueComparer?: ValueComparer): boolean;
    Generate(model: IModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(model: IRelationalModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(table: ITableBase, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(table: ITable, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(view: IView, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(sqlQuery: ISqlQuery, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(function_: IStoreFunction, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(storedProcedure: IStoreStoredProcedure, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IColumnBase, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IViewColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: ISqlQueryColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IFunctionColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(parameter: IStoreFunctionParameter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IStoreStoredProcedureResultColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(parameter: IStoreStoredProcedureParameter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(uniqueConstraint: IUniqueConstraint, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(index: ITableIndex, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(foreignKey: IForeignKeyConstraint, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(tableMapping: ITableMappingBase, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(tableMapping: ITableMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(viewMapping: IViewMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(sqlQueryMapping: ISqlQueryMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(functionMapping: IFunctionMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(sprocMapping: IStoredProcedureMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(function_: IDbFunction, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(functionParameter: IDbFunctionParameter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(sequence: ISequence, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(entityType: IEntityType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(complexType: IComplexType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(fragment: IEntityTypeMappingFragment, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(storedProcedure: IStoredProcedure, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(storedProcedure: IStoredProcedureParameter, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(storedProcedure: IStoredProcedureResultColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(overrides: IRelationalPropertyOverrides, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(key: IKey, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(foreignKey: IForeignKey, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(index: IIndex, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
}


export const RelationalCSharpRuntimeAnnotationCodeGenerator: {
    new(dependencies: CSharpRuntimeAnnotationCodeGeneratorDependencies, relationalDependencies: RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies): RelationalCSharpRuntimeAnnotationCodeGenerator;
};


export interface __RelationalCSharpRuntimeAnnotationCodeGenerator$views {
    As_ICSharpRuntimeAnnotationCodeGenerator(): ICSharpRuntimeAnnotationCodeGenerator$instance;
}

export type RelationalCSharpRuntimeAnnotationCodeGenerator = RelationalCSharpRuntimeAnnotationCodeGenerator$instance & __RelationalCSharpRuntimeAnnotationCodeGenerator$views;


export interface RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Design_Internal_RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    _Clone_$(): RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies: {
    new(): RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies;
};


export type RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies = RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies$instance;

