// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Migrations
// Assembly: Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { IDiagnosticsLogger_1, ILoggingOptions, IRelationalCommandDiagnosticsLogger } from "../../Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { IAnnotation, ICurrentDbContext, IDbContextOptions, IModelRuntimeInitializer, ModelDependencies, ModelSnapshot } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { EntityTypeBuilder_1 } from "../../Microsoft.EntityFrameworkCore.Metadata.Builders/internal/index.js";
import type { IConventionSetBuilder } from "../../Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure/internal/index.js";
import type { ICheckConstraint, IColumn, IForeignKeyConstraint, IModel, IRelationalModel, ISequence, ITable, ITableIndex, IUniqueConstraint, IView, IViewColumn } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { AlterOperationBuilder_1, ColumnsBuilder, CreateTableBuilder_1, OperationBuilder_1 } from "../../Microsoft.EntityFrameworkCore.Migrations.Operations.Builders/internal/index.js";
import type { AddCheckConstraintOperation, AddColumnOperation, AddForeignKeyOperation, AddPrimaryKeyOperation, AddUniqueConstraintOperation, AlterColumnOperation, AlterDatabaseOperation, AlterSequenceOperation, AlterTableOperation, ColumnOperation, CreateIndexOperation, CreateSequenceOperation, CreateTableOperation, DeleteDataOperation, DropCheckConstraintOperation, DropColumnOperation, DropForeignKeyOperation, DropIndexOperation, DropPrimaryKeyOperation, DropSchemaOperation, DropSequenceOperation, DropTableOperation, DropUniqueConstraintOperation, EnsureSchemaOperation, InsertDataOperation, MigrationOperation, RenameColumnOperation, RenameIndexOperation, RenameSequenceOperation, RenameTableOperation, RestartSequenceOperation, SequenceOperation, SqlOperation, UpdateDataOperation } from "../../Microsoft.EntityFrameworkCore.Migrations.Operations/internal/index.js";
import type { IDbContextTransaction, IRawSqlCommandBuilder, IRelationalCommand, IRelationalCommandBuilderFactory, IRelationalConnection, IRelationalDatabaseCreator, IRelationalTypeMappingSource, ISqlGenerationHelper } from "../../Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { IModificationCommandFactory, IReadOnlyModificationCommand, IUpdateSqlGenerator } from "../../Microsoft.EntityFrameworkCore.Update/internal/index.js";
import type { DbContext, DbLoggerCategory_Migrations, ModelBuilder } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import type { IComparer_1, IEnumerable_1, IReadOnlyDictionary_2, IReadOnlyList_1, List_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IsolationLevel } from "@tsonic/dotnet/System.Data/internal/index.js";
import type { Assembly, TypeInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import type { Task, Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Attribute, Boolean as ClrBoolean, Enum, FormattableString, Func_2, IAsyncDisposable, IComparable, IConvertible, IDisposable, IEquatable_1, IFormattable, Int32, Int64, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System/internal/index.js";

export enum LockReleaseBehavior {
    Transaction = 0,
    Connection = 1,
    Explicit = 2
}


export enum MigrationsSqlGenerationOptions {
    Default = 0,
    Script = 1,
    Idempotent = 2,
    NoTransactions = 4
}


export enum ReferentialAction {
    NoAction = 0,
    Restrict = 1,
    Cascade = 2,
    SetNull = 3,
    SetDefault = 4
}


export interface IHistoryRepository$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IHistoryRepository: never;

    readonly LockReleaseBehavior: LockReleaseBehavior;
    AcquireDatabaseLock(): IMigrationsDatabaseLock;
    Create(): void;
    CreateAsync(cancellationToken?: CancellationToken): Task;
    Exists(): boolean;
    ExistsAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
    GetAppliedMigrations(): IReadOnlyList_1<HistoryRow>;
    GetCreateScript(): string;
    GetDeleteScript(migrationId: string): string;
    GetInsertScript(row: HistoryRow): string;
}


export type IHistoryRepository = IHistoryRepository$instance;

export interface IMigrationCommandExecutor$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationCommandExecutor: never;

    ExecuteNonQuery(migrationCommands: IEnumerable_1<MigrationCommand>, connection: IRelationalConnection): void;
    ExecuteNonQuery(migrationCommands: IReadOnlyList_1<MigrationCommand>, connection: IRelationalConnection, executionState: MigrationExecutionState, commitTransaction: boolean, isolationLevel?: Nullable_1<IsolationLevel>): int;
    ExecuteNonQueryAsync(migrationCommands: IEnumerable_1<MigrationCommand>, connection: IRelationalConnection, cancellationToken?: CancellationToken): Task;
    ExecuteNonQueryAsync(migrationCommands: IReadOnlyList_1<MigrationCommand>, connection: IRelationalConnection, executionState: MigrationExecutionState, commitTransaction: boolean, isolationLevel?: Nullable_1<IsolationLevel>, cancellationToken?: CancellationToken): Task_1<System_Internal.Int32>;
}


export type IMigrationCommandExecutor = IMigrationCommandExecutor$instance;

export interface IMigrationsAnnotationProvider$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsAnnotationProvider: never;

    ForRemove(checkConstraint: ICheckConstraint): IEnumerable_1<IAnnotation>;
    ForRemove(column: IColumn): IEnumerable_1<IAnnotation>;
    ForRemove(foreignKey: IForeignKeyConstraint): IEnumerable_1<IAnnotation>;
    ForRemove(model: IRelationalModel): IEnumerable_1<IAnnotation>;
    ForRemove(sequence: ISequence): IEnumerable_1<IAnnotation>;
    ForRemove(table: ITable): IEnumerable_1<IAnnotation>;
    ForRemove(index: ITableIndex): IEnumerable_1<IAnnotation>;
    ForRemove(constraint: IUniqueConstraint): IEnumerable_1<IAnnotation>;
    ForRemove(view: IView): IEnumerable_1<IAnnotation>;
    ForRemove(column: IViewColumn): IEnumerable_1<IAnnotation>;
}


export type IMigrationsAnnotationProvider = IMigrationsAnnotationProvider$instance;

export interface IMigrationsAssembly$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsAssembly: never;

    readonly Migrations: IReadOnlyDictionary_2<System_Internal.String, TypeInfo>;
    readonly ModelSnapshot: ModelSnapshot | undefined;
    readonly Assembly: Assembly;
    CreateMigration(migrationClass: TypeInfo, activeProvider: string): Migration;
    FindMigrationId(nameOrId: string): string | undefined;
}


export type IMigrationsAssembly = IMigrationsAssembly$instance;

export interface IMigrationsDatabaseLock$instance extends IDisposable, IAsyncDisposable {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsDatabaseLock: never;

    readonly HistoryRepository: IHistoryRepository;
    ReacquireIfNeeded(connectionReopened: boolean, transactionRestarted: Nullable_1<System_Internal.Boolean>): IMigrationsDatabaseLock;
    ReacquireIfNeededAsync(connectionReopened: boolean, transactionRestarted: Nullable_1<System_Internal.Boolean>, cancellationToken?: CancellationToken): Task_1<IMigrationsDatabaseLock>;
}


export interface IMigrationsDatabaseLock$instance extends System_Internal.IAsyncDisposable, System_Internal.IDisposable {}

export type IMigrationsDatabaseLock = IMigrationsDatabaseLock$instance;

export interface IMigrationsIdGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsIdGenerator: never;

    GenerateId(name: string): string;
    IsValidId(value: string): boolean;
}


export type IMigrationsIdGenerator = IMigrationsIdGenerator$instance;

export interface IMigrationsModelDiffer$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsModelDiffer: never;

    GetDifferences(source: IRelationalModel, target: IRelationalModel): IReadOnlyList_1<MigrationOperation>;
    HasDifferences(source: IRelationalModel, target: IRelationalModel): boolean;
}


export type IMigrationsModelDiffer = IMigrationsModelDiffer$instance;

export interface IMigrationsSqlGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsSqlGenerator: never;

    Generate(operations: IReadOnlyList_1<MigrationOperation>, model?: IModel, options?: MigrationsSqlGenerationOptions): IReadOnlyList_1<MigrationCommand>;
}


export type IMigrationsSqlGenerator = IMigrationsSqlGenerator$instance;

export interface IMigrator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrator: never;

    GenerateScript(fromMigration?: string, toMigration?: string, options?: MigrationsSqlGenerationOptions): string;
    HasPendingModelChanges(): boolean;
    Migrate(targetMigration?: string): void;
    MigrateAsync(targetMigration?: string, cancellationToken?: CancellationToken): Task;
}


export type IMigrator = IMigrator$instance;

export interface HistoryRepository$instance extends IHistoryRepository$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_HistoryRepository: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IHistoryRepository: never;

    readonly Dependencies: HistoryRepositoryDependencies;
    readonly ExistsSql: string;
    readonly GetAppliedMigrationsSql: string;
    readonly LockReleaseBehavior: LockReleaseBehavior;
    readonly MigrationIdColumnName: string;
    readonly ProductVersionColumnName: string;
    readonly SqlGenerationHelper: ISqlGenerationHelper;
    readonly TableName: string;
    readonly TableSchema: string | undefined;
    AcquireDatabaseLock(): IMigrationsDatabaseLock;
    AcquireDatabaseLockAsync(cancellationToken?: CancellationToken): Task_1<IMigrationsDatabaseLock>;
    ConfigureTable(history: EntityTypeBuilder_1<HistoryRow>): void;
    Create(): void;
    CreateAsync(cancellationToken?: CancellationToken): Task;
    Exists(): boolean;
    ExistsAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
    GetAppliedMigrations(): IReadOnlyList_1<HistoryRow>;
    GetAppliedMigrationsAsync(cancellationToken?: CancellationToken): Task_1<IReadOnlyList_1<HistoryRow>>;
    GetBeginIfExistsScript(migrationId: string): string;
    GetBeginIfNotExistsScript(migrationId: string): string;
    GetCreateCommands(): IReadOnlyList_1<MigrationCommand>;
    GetCreateIfNotExistsScript(): string;
    GetCreateScript(): string;
    GetDeleteScript(migrationId: string): string;
    GetEndIfScript(): string;
    GetInsertScript(row: HistoryRow): string;
    InterpretExistsResult(value: unknown): boolean;
}


export const HistoryRepository: (abstract new(dependencies: HistoryRepositoryDependencies) => HistoryRepository) & {
    readonly DefaultTableName: string;
};


export interface __HistoryRepository$views {
    As_IHistoryRepository(): IHistoryRepository$instance;
}

export type HistoryRepository = HistoryRepository$instance & __HistoryRepository$views;


export interface HistoryRepositoryDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_HistoryRepositoryDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    CommandLogger: IRelationalCommandDiagnosticsLogger;
    Connection: IRelationalConnection;
    ConventionSetBuilder: IConventionSetBuilder;
    CurrentContext: ICurrentDbContext;
    DatabaseCreator: IRelationalDatabaseCreator;
    MigrationCommandExecutor: IMigrationCommandExecutor;
    MigrationsLogger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>;
    MigrationsSqlGenerator: IMigrationsSqlGenerator;
    ModelDependencies: ModelDependencies;
    ModelDiffer: IMigrationsModelDiffer;
    ModelRuntimeInitializer: IModelRuntimeInitializer;
    Options: IDbContextOptions;
    RawSqlCommandBuilder: IRawSqlCommandBuilder;
    SqlGenerationHelper: ISqlGenerationHelper;
    TypeMappingSource: IRelationalTypeMappingSource;
    _Clone_$(): HistoryRepositoryDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: HistoryRepositoryDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const HistoryRepositoryDependencies: {
    new(databaseCreator: IRelationalDatabaseCreator, rawSqlCommandBuilder: IRawSqlCommandBuilder, connection: IRelationalConnection, options: IDbContextOptions, modelDiffer: IMigrationsModelDiffer, migrationsSqlGenerator: IMigrationsSqlGenerator, migrationCommandExecutor: IMigrationCommandExecutor, sqlGenerationHelper: ISqlGenerationHelper, conventionSetBuilder: IConventionSetBuilder, modelDependencies: ModelDependencies, typeMappingSource: IRelationalTypeMappingSource, currentContext: ICurrentDbContext, modelRuntimeInitializer: IModelRuntimeInitializer, commandLogger: IRelationalCommandDiagnosticsLogger, migrationsLogger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>): HistoryRepositoryDependencies;
};


export type HistoryRepositoryDependencies = HistoryRepositoryDependencies$instance;

export interface HistoryRow$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_HistoryRow: never;

    readonly MigrationId: string;
    readonly ProductVersion: string;
}


export const HistoryRow: {
    new(migrationId: string, productVersion: string): HistoryRow;
};


export type HistoryRow = HistoryRow$instance;

export interface Migration$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_Migration: never;

    get ActiveProvider(): string | undefined;
    set ActiveProvider(value: string | undefined);
    readonly DownOperations: IReadOnlyList_1<MigrationOperation>;
    readonly TargetModel: IModel;
    readonly UpOperations: IReadOnlyList_1<MigrationOperation>;
    BuildTargetModel(modelBuilder: ModelBuilder): void;
    Down(migrationBuilder: MigrationBuilder): void;
    Up(migrationBuilder: MigrationBuilder): void;
}


export const Migration: (abstract new() => Migration) & {
    readonly InitialDatabase: string;
};


export type Migration = Migration$instance;

export interface MigrationAttribute$instance extends Attribute {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationAttribute: never;

    readonly Id: string;
}


export const MigrationAttribute: {
    new(id: string): MigrationAttribute;
};


export type MigrationAttribute = MigrationAttribute$instance;

export interface MigrationBuilder$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationBuilder: never;

    readonly ActiveProvider: string | undefined;
    readonly Operations: List_1<MigrationOperation>;
    AddCheckConstraint(name: string, table: string, sql: string, schema?: string): OperationBuilder_1<AddCheckConstraintOperation>;
    AddColumn<T>(name: string, table: string, type?: string, unicode?: Nullable_1<System_Internal.Boolean>, maxLength?: Nullable_1<System_Internal.Int32>, rowVersion?: boolean, schema?: string, nullable?: boolean, defaultValue?: unknown, defaultValueSql?: string, computedColumnSql?: string, fixedLength?: Nullable_1<System_Internal.Boolean>, comment?: string, collation?: string, precision?: Nullable_1<System_Internal.Int32>, scale?: Nullable_1<System_Internal.Int32>, stored?: Nullable_1<System_Internal.Boolean>): OperationBuilder_1<AddColumnOperation>;
    AddForeignKey(name: string, table: string, column: string, principalTable: string, schema?: string, principalSchema?: string, principalColumn?: string, onUpdate?: ReferentialAction, onDelete?: ReferentialAction): OperationBuilder_1<AddForeignKeyOperation>;
    AddForeignKey(name: string, table: string, columns: string[], principalTable: string, schema?: string, principalSchema?: string, principalColumns?: string[], onUpdate?: ReferentialAction, onDelete?: ReferentialAction): OperationBuilder_1<AddForeignKeyOperation>;
    AddPrimaryKey(name: string, table: string, column: string, schema?: string): OperationBuilder_1<AddPrimaryKeyOperation>;
    AddPrimaryKey(name: string, table: string, columns: string[], schema?: string): OperationBuilder_1<AddPrimaryKeyOperation>;
    AddUniqueConstraint(name: string, table: string, column: string, schema?: string): OperationBuilder_1<AddUniqueConstraintOperation>;
    AddUniqueConstraint(name: string, table: string, columns: string[], schema?: string): OperationBuilder_1<AddUniqueConstraintOperation>;
    AlterColumn<T>(name: string, table: string, type?: string, unicode?: Nullable_1<System_Internal.Boolean>, maxLength?: Nullable_1<System_Internal.Int32>, rowVersion?: boolean, schema?: string, nullable?: boolean, defaultValue?: unknown, defaultValueSql?: string, computedColumnSql?: string, oldClrType?: Type, oldType?: string, oldUnicode?: Nullable_1<System_Internal.Boolean>, oldMaxLength?: Nullable_1<System_Internal.Int32>, oldRowVersion?: boolean, oldNullable?: boolean, oldDefaultValue?: unknown, oldDefaultValueSql?: string, oldComputedColumnSql?: string, fixedLength?: Nullable_1<System_Internal.Boolean>, oldFixedLength?: Nullable_1<System_Internal.Boolean>, comment?: string, oldComment?: string, collation?: string, oldCollation?: string, precision?: Nullable_1<System_Internal.Int32>, oldPrecision?: Nullable_1<System_Internal.Int32>, scale?: Nullable_1<System_Internal.Int32>, oldScale?: Nullable_1<System_Internal.Int32>, stored?: Nullable_1<System_Internal.Boolean>, oldStored?: Nullable_1<System_Internal.Boolean>): AlterOperationBuilder_1<AlterColumnOperation>;
    AlterDatabase(collation?: string, oldCollation?: string): AlterOperationBuilder_1<AlterDatabaseOperation>;
    AlterSequence(name: string, schema?: string, incrementBy?: int, minValue?: Nullable_1<System_Internal.Int64>, maxValue?: Nullable_1<System_Internal.Int64>, cyclic?: boolean, oldIncrementBy?: int, oldMinValue?: Nullable_1<System_Internal.Int64>, oldMaxValue?: Nullable_1<System_Internal.Int64>, oldCyclic?: boolean): AlterOperationBuilder_1<AlterSequenceOperation>;
    AlterTable(name: string, schema?: string, comment?: string, oldComment?: string): AlterOperationBuilder_1<AlterTableOperation>;
    CreateCheckConstraint(name: string, table: string, sql: string, schema?: string): OperationBuilder_1<AddCheckConstraintOperation>;
    CreateIndex(name: string, table: string, column: string, schema?: string, unique?: boolean, filter?: string, descending?: boolean[]): OperationBuilder_1<CreateIndexOperation>;
    CreateIndex(name: string, table: string, columns: string[], schema?: string, unique?: boolean, filter?: string, descending?: boolean[]): OperationBuilder_1<CreateIndexOperation>;
    CreateSequence(name: string, schema?: string, startValue?: long, incrementBy?: int, minValue?: Nullable_1<System_Internal.Int64>, maxValue?: Nullable_1<System_Internal.Int64>, cyclic?: boolean): OperationBuilder_1<CreateSequenceOperation>;
    CreateTable<TColumns>(name: string, columns: Func_2<ColumnsBuilder, TColumns>, schema?: string, constraints?: Action_1<CreateTableBuilder_1<TColumns>>, comment?: string): CreateTableBuilder_1<TColumns>;
    DeleteData(table: string, keyColumn: string, keyValue: unknown, schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumn: string, keyColumnType: string, keyValue: unknown, schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumns: string[], keyValues: unknown[], schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumns: string[], keyColumnTypes: string[], keyValues: unknown[], schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumn: string, keyValues: unknown[], schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumn: string, keyColumnType: string, keyValues: unknown[], schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumns: string[], keyValues: Array<Array<unknown>>, schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DeleteData(table: string, keyColumns: string[], keyColumnTypes: string[], keyValues: Array<Array<unknown>>, schema?: string): OperationBuilder_1<DeleteDataOperation>;
    DropCheckConstraint(name: string, table: string, schema?: string): OperationBuilder_1<DropCheckConstraintOperation>;
    DropColumn(name: string, table: string, schema?: string): OperationBuilder_1<DropColumnOperation>;
    DropForeignKey(name: string, table: string, schema?: string): OperationBuilder_1<DropForeignKeyOperation>;
    DropIndex(name: string, table?: string, schema?: string): OperationBuilder_1<DropIndexOperation>;
    DropPrimaryKey(name: string, table: string, schema?: string): OperationBuilder_1<DropPrimaryKeyOperation>;
    DropSchema(name: string): OperationBuilder_1<DropSchemaOperation>;
    DropSequence(name: string, schema?: string): OperationBuilder_1<DropSequenceOperation>;
    DropTable(name: string, schema?: string): OperationBuilder_1<DropTableOperation>;
    DropUniqueConstraint(name: string, table: string, schema?: string): OperationBuilder_1<DropUniqueConstraintOperation>;
    EnsureSchema(name: string): OperationBuilder_1<EnsureSchemaOperation>;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    InsertData(table: string, column: string, value: unknown, schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, column: string, columnType: string, value: unknown, schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, columns: string[], values: unknown[], schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, columns: string[], columnTypes: string[], values: unknown[], schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, column: string, values: unknown[], schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, column: string, columnType: string, values: unknown[], schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, columns: string[], values: Array<Array<unknown>>, schema?: string): OperationBuilder_1<InsertDataOperation>;
    InsertData(table: string, columns: string[], columnTypes: string[], values: Array<Array<unknown>>, schema?: string): OperationBuilder_1<InsertDataOperation>;
    RenameColumn(name: string, table: string, newName: string, schema?: string): OperationBuilder_1<RenameColumnOperation>;
    RenameIndex(name: string, newName: string, table?: string, schema?: string): OperationBuilder_1<RenameIndexOperation>;
    RenameSequence(name: string, schema?: string, newName?: string, newSchema?: string): OperationBuilder_1<RenameSequenceOperation>;
    RenameTable(name: string, schema?: string, newName?: string, newSchema?: string): OperationBuilder_1<RenameTableOperation>;
    RestartSequence(name: string, startValue?: Nullable_1<System_Internal.Int64>, schema?: string): OperationBuilder_1<RestartSequenceOperation>;
    Sql(sql: string, suppressTransaction?: boolean): OperationBuilder_1<SqlOperation>;
    ToString(): string;
    UpdateData(table: string, keyColumn: string, keyValue: unknown, column: string, value: unknown, schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumn: string, keyValue: unknown, columns: string[], values: unknown[], schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumns: string[], keyValues: unknown[], column: string, value: unknown, schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumns: string[], keyValues: unknown[], columns: string[], values: unknown[], schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumns: string[], keyColumnTypes: string[], keyValues: unknown[], columns: string[], columnTypes: string[], values: unknown[], schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumn: string, keyValues: unknown[], column: string, values: unknown[], schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumn: string, keyValues: unknown[], columns: string[], values: Array<Array<unknown>>, schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumns: string[], keyValues: Array<Array<unknown>>, column: string, values: unknown[], schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumns: string[], keyValues: Array<Array<unknown>>, columns: string[], values: Array<Array<unknown>>, schema?: string): OperationBuilder_1<UpdateDataOperation>;
    UpdateData(table: string, keyColumns: string[], keyColumnTypes: string[], keyValues: Array<Array<unknown>>, columns: string[], columnTypes: string[], values: Array<Array<unknown>>, schema?: string): OperationBuilder_1<UpdateDataOperation>;
}


export const MigrationBuilder: {
    new(activeProvider: string): MigrationBuilder;
};


export type MigrationBuilder = MigrationBuilder$instance;

export interface MigrationCommand$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationCommand: never;

    readonly CommandLogger: IRelationalCommandDiagnosticsLogger;
    readonly CommandText: string;
    readonly TransactionSuppressed: boolean;
    ExecuteNonQuery(connection: IRelationalConnection, parameterValues?: IReadOnlyDictionary_2<System_Internal.String, unknown>): int;
    ExecuteNonQueryAsync(connection: IRelationalConnection, parameterValues?: IReadOnlyDictionary_2<System_Internal.String, unknown>, cancellationToken?: CancellationToken): Task_1<System_Internal.Int32>;
}


export const MigrationCommand: {
    new(relationalCommand: IRelationalCommand, context: DbContext, logger: IRelationalCommandDiagnosticsLogger, transactionSuppressed: boolean): MigrationCommand;
};


export type MigrationCommand = MigrationCommand$instance;

export interface MigrationCommandListBuilder$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationCommandListBuilder: never;

    readonly Dependencies: MigrationsSqlGeneratorDependencies;
    Append(o: string): MigrationCommandListBuilder;
    AppendLine(): MigrationCommandListBuilder;
    AppendLine(value: string): MigrationCommandListBuilder;
    AppendLine(value: FormattableString): MigrationCommandListBuilder;
    AppendLines(value: string): MigrationCommandListBuilder;
    DecrementIndent(): MigrationCommandListBuilder;
    EndCommand(suppressTransaction?: boolean): MigrationCommandListBuilder;
    GetCommandList(): IReadOnlyList_1<MigrationCommand>;
    IncrementIndent(): MigrationCommandListBuilder;
    Indent(): IDisposable;
}


export const MigrationCommandListBuilder: {
    new(dependencies: MigrationsSqlGeneratorDependencies): MigrationCommandListBuilder;
};


export type MigrationCommandListBuilder = MigrationCommandListBuilder$instance;

export interface MigrationExecutionState$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationExecutionState: never;

    AnyOperationPerformed: boolean;
    get CurrentMigrationId(): string | undefined;
    set CurrentMigrationId(value: string | undefined);
    get DatabaseLock(): IMigrationsDatabaseLock | undefined;
    set DatabaseLock(value: IMigrationsDatabaseLock | undefined);
    LastCommittedCommandIndex: int;
    get Transaction(): IDbContextTransaction | undefined;
    set Transaction(value: IDbContextTransaction | undefined);
}


export const MigrationExecutionState: {
    new(): MigrationExecutionState;
};


export type MigrationExecutionState = MigrationExecutionState$instance;

export interface MigrationsAnnotationProvider$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationsAnnotationProvider: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsAnnotationProvider: never;

    readonly Dependencies: MigrationsAnnotationProviderDependencies;
    ForRemove(model: IRelationalModel): IEnumerable_1<IAnnotation>;
    ForRemove(table: ITable): IEnumerable_1<IAnnotation>;
    ForRemove(column: IColumn): IEnumerable_1<IAnnotation>;
    ForRemove(view: IView): IEnumerable_1<IAnnotation>;
    ForRemove(column: IViewColumn): IEnumerable_1<IAnnotation>;
    ForRemove(constraint: IUniqueConstraint): IEnumerable_1<IAnnotation>;
    ForRemove(index: ITableIndex): IEnumerable_1<IAnnotation>;
    ForRemove(foreignKey: IForeignKeyConstraint): IEnumerable_1<IAnnotation>;
    ForRemove(sequence: ISequence): IEnumerable_1<IAnnotation>;
    ForRemove(checkConstraint: ICheckConstraint): IEnumerable_1<IAnnotation>;
    ForRename(table: ITable): IEnumerable_1<IAnnotation>;
    ForRename(column: IColumn): IEnumerable_1<IAnnotation>;
    ForRename(index: ITableIndex): IEnumerable_1<IAnnotation>;
    ForRename(sequence: ISequence): IEnumerable_1<IAnnotation>;
}


export const MigrationsAnnotationProvider: {
    new(dependencies: MigrationsAnnotationProviderDependencies): MigrationsAnnotationProvider;
};


export interface __MigrationsAnnotationProvider$views {
    As_IMigrationsAnnotationProvider(): IMigrationsAnnotationProvider$instance;
}

export type MigrationsAnnotationProvider = MigrationsAnnotationProvider$instance & __MigrationsAnnotationProvider$views;


export interface MigrationsAnnotationProviderDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationsAnnotationProviderDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    _Clone_$(): MigrationsAnnotationProviderDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: MigrationsAnnotationProviderDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const MigrationsAnnotationProviderDependencies: {
    new(): MigrationsAnnotationProviderDependencies;
};


export type MigrationsAnnotationProviderDependencies = MigrationsAnnotationProviderDependencies$instance;

export interface MigrationsSqlGenerator$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationsSqlGenerator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrationsSqlGenerator: never;

    readonly Dependencies: MigrationsSqlGeneratorDependencies;
    Options: MigrationsSqlGenerationOptions;
    readonly SqlGenerator: IUpdateSqlGenerator;
    readonly VersionComparer: IComparer_1<System_Internal.String>;
    CheckConstraint(operation: AddCheckConstraintOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    ColumnDefinition(operation: AddColumnOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    ColumnDefinition(schema: string, table: string, name: string, operation: ColumnOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    ColumnList(columns: string[]): string;
    ComputedColumnDefinition(schema: string, table: string, name: string, operation: ColumnOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    CreateTableCheckConstraints(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    CreateTableColumns(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    CreateTableConstraints(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    CreateTableForeignKeys(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    CreateTablePrimaryKeyConstraint(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    CreateTableUniqueConstraints(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    DefaultValue(defaultValue: unknown, defaultValueSql: string, columnType: string, builder: MigrationCommandListBuilder): void;
    EndStatement(builder: MigrationCommandListBuilder, suppressTransaction?: boolean): void;
    ForeignKeyAction(referentialAction: ReferentialAction, builder: MigrationCommandListBuilder): void;
    ForeignKeyConstraint(operation: AddForeignKeyOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operations: IReadOnlyList_1<MigrationOperation>, model?: IModel, options?: MigrationsSqlGenerationOptions): IReadOnlyList_1<MigrationCommand>;
    Generate(operation: MigrationOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: AddColumnOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: AddForeignKeyOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: AddPrimaryKeyOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: AddUniqueConstraintOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: AddCheckConstraintOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: AlterColumnOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: AlterDatabaseOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: RenameIndexOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: AlterSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: AlterTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: RenameTableOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: CreateIndexOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: EnsureSchemaOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: CreateSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: CreateTableOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DropColumnOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DropForeignKeyOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DropIndexOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DropPrimaryKeyOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DropSchemaOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: DropSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: DropTableOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DropUniqueConstraintOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: DropCheckConstraintOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: RenameColumnOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: RenameSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: RestartSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: SqlOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: InsertDataOperation, model: IModel, builder: MigrationCommandListBuilder, terminate?: boolean): void;
    Generate(operation: DeleteDataOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    Generate(operation: UpdateDataOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    GenerateIndexColumnList(operation: CreateIndexOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    GenerateModificationCommands(operation: InsertDataOperation, model: IModel): IEnumerable_1<IReadOnlyModificationCommand>;
    GenerateModificationCommands(operation: DeleteDataOperation, model: IModel): IEnumerable_1<IReadOnlyModificationCommand>;
    GenerateModificationCommands(operation: UpdateDataOperation, model: IModel): IEnumerable_1<IReadOnlyModificationCommand>;
    GetColumnType(schema: string, tableName: string, name: string, operation: ColumnOperation, model: IModel): string;
    HasLegacyRenameOperations(model: IModel): boolean;
    IndexOptions(operation: MigrationOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    IndexTraits(operation: MigrationOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    IsOldColumnSupported(model: IModel): boolean;
    PrimaryKeyConstraint(operation: AddPrimaryKeyOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    SequenceOptions(operation: AlterSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    SequenceOptions(operation: CreateSequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    SequenceOptions(schema: string, name: string, operation: SequenceOperation, model: IModel, builder: MigrationCommandListBuilder): void;
    SequenceOptions(schema: string, name: string, operation: SequenceOperation, model: IModel, builder: MigrationCommandListBuilder, forAlter: boolean): void;
    TryGetVersion(model: IModel, version: string): boolean;
    UniqueConstraint(operation: AddUniqueConstraintOperation, model: IModel, builder: MigrationCommandListBuilder): void;
}


export const MigrationsSqlGenerator: {
    new(dependencies: MigrationsSqlGeneratorDependencies): MigrationsSqlGenerator;
};


export interface __MigrationsSqlGenerator$views {
    As_IMigrationsSqlGenerator(): IMigrationsSqlGenerator$instance;
}

export type MigrationsSqlGenerator = MigrationsSqlGenerator$instance & __MigrationsSqlGenerator$views;


export interface MigrationsSqlGeneratorDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_MigrationsSqlGeneratorDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    CommandBuilderFactory: IRelationalCommandBuilderFactory;
    CurrentContext: ICurrentDbContext;
    Logger: IRelationalCommandDiagnosticsLogger;
    LoggingOptions: ILoggingOptions;
    MigrationsLogger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>;
    ModificationCommandFactory: IModificationCommandFactory;
    SqlGenerationHelper: ISqlGenerationHelper;
    TypeMappingSource: IRelationalTypeMappingSource;
    UpdateSqlGenerator: IUpdateSqlGenerator;
    _Clone_$(): MigrationsSqlGeneratorDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: MigrationsSqlGeneratorDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const MigrationsSqlGeneratorDependencies: {
    new(commandBuilderFactory: IRelationalCommandBuilderFactory, updateSqlGenerator: IUpdateSqlGenerator, sqlGenerationHelper: ISqlGenerationHelper, typeMappingSource: IRelationalTypeMappingSource, currentContext: ICurrentDbContext, modificationCommandFactory: IModificationCommandFactory, loggingOptions: ILoggingOptions, logger: IRelationalCommandDiagnosticsLogger, migrationsLogger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>): MigrationsSqlGeneratorDependencies;
};


export type MigrationsSqlGeneratorDependencies = MigrationsSqlGeneratorDependencies$instance;

export abstract class MigrationsAssemblyExtensions$instance {
    static GetMigrationId(assembly: IMigrationsAssembly, nameOrId: string): string;
}


export type MigrationsAssemblyExtensions = MigrationsAssemblyExtensions$instance;

