// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Scaffolding
// Assembly: Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { MethodCallCodeFragment } from "../../Microsoft.EntityFrameworkCore.Design/internal/index.js";
import type { DatabaseModel } from "../../Microsoft.EntityFrameworkCore.Scaffolding.Metadata/internal/index.js";
import type { IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, IEquatable_1, Int32, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";

export interface IDatabaseModelFactory$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IDatabaseModelFactory: never;

    Create(connection: DbConnection, options: DatabaseModelFactoryOptions): DatabaseModel;
    Create(connectionString: string, options: DatabaseModelFactoryOptions): DatabaseModel;
}


export type IDatabaseModelFactory = IDatabaseModelFactory$instance;

export interface IProviderCodeGeneratorPlugin$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IProviderCodeGeneratorPlugin: never;

    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
}


export type IProviderCodeGeneratorPlugin = IProviderCodeGeneratorPlugin$instance;

export interface IProviderConfigurationCodeGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IProviderConfigurationCodeGenerator: never;

    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
    GenerateUseProvider(connectionString: string, providerOptions: MethodCallCodeFragment): MethodCallCodeFragment;
    GenerateUseProvider(connectionString: string): MethodCallCodeFragment;
}


export type IProviderConfigurationCodeGenerator = IProviderConfigurationCodeGenerator$instance;

export interface DatabaseModelFactory$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IDatabaseModelFactory: never;

    Create(connectionString: string, options: DatabaseModelFactoryOptions): DatabaseModel;
    Create(connection: DbConnection, options: DatabaseModelFactoryOptions): DatabaseModel;
}


export const DatabaseModelFactory: (abstract new() => DatabaseModelFactory) & {
};


export interface __DatabaseModelFactory$views {
    As_IDatabaseModelFactory(): IDatabaseModelFactory$instance;
}

export type DatabaseModelFactory = DatabaseModelFactory$instance & __DatabaseModelFactory$views;


export interface DatabaseModelFactoryOptions$instance {
    readonly Schemas: IEnumerable_1<System_Internal.String>;
    readonly Tables: IEnumerable_1<System_Internal.String>;
}


export const DatabaseModelFactoryOptions: {
    new(tables: IEnumerable_1<System_Internal.String>, schemas: IEnumerable_1<System_Internal.String>): DatabaseModelFactoryOptions;
};


export type DatabaseModelFactoryOptions = DatabaseModelFactoryOptions$instance;

export interface ProviderCodeGenerator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IProviderConfigurationCodeGenerator: never;

    readonly Dependencies: ProviderCodeGeneratorDependencies;
    GenerateContextOptions(): MethodCallCodeFragment | undefined;
    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
    GenerateUseProvider(connectionString: string, providerOptions: MethodCallCodeFragment): MethodCallCodeFragment;
    GenerateUseProvider(connectionString: string): MethodCallCodeFragment;
}


export const ProviderCodeGenerator: (abstract new(dependencies: ProviderCodeGeneratorDependencies) => ProviderCodeGenerator) & {
};


export interface __ProviderCodeGenerator$views {
    As_IProviderConfigurationCodeGenerator(): IProviderConfigurationCodeGenerator$instance;
}

export interface ProviderCodeGenerator$instance extends IProviderConfigurationCodeGenerator$instance {}

export type ProviderCodeGenerator = ProviderCodeGenerator$instance & __ProviderCodeGenerator$views;


export interface ProviderCodeGeneratorDependencies$instance {
    readonly __tsonic_iface_System_IEquatable_1: never;

    Plugins: IEnumerable_1<IProviderCodeGeneratorPlugin>;
    _Clone_$(): ProviderCodeGeneratorDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: ProviderCodeGeneratorDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const ProviderCodeGeneratorDependencies: {
    new(plugins: IEnumerable_1<IProviderCodeGeneratorPlugin>): ProviderCodeGeneratorDependencies;
};


export type ProviderCodeGeneratorDependencies = ProviderCodeGeneratorDependencies$instance;

export interface ProviderCodeGeneratorPlugin$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IProviderCodeGeneratorPlugin: never;

    GenerateContextOptions(): MethodCallCodeFragment | undefined;
    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
}


export const ProviderCodeGeneratorPlugin: {
    new(): ProviderCodeGeneratorPlugin;
};


export interface __ProviderCodeGeneratorPlugin$views {
    As_IProviderCodeGeneratorPlugin(): IProviderCodeGeneratorPlugin$instance;
}

export interface ProviderCodeGeneratorPlugin$instance extends IProviderCodeGeneratorPlugin$instance {}

export type ProviderCodeGeneratorPlugin = ProviderCodeGeneratorPlugin$instance & __ProviderCodeGeneratorPlugin$views;


