// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Scaffolding
// Assembly: Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { MethodCallCodeFragment } from "../../Microsoft.EntityFrameworkCore.Design/internal/index.js";
import type { DatabaseModel } from "../../Microsoft.EntityFrameworkCore.Scaffolding.Metadata/internal/index.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, IEquatable, Int32, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";

export interface IDatabaseModelFactory$instance {
    Create(connection: DbConnection, options: DatabaseModelFactoryOptions): DatabaseModel;
    Create(connectionString: string, options: DatabaseModelFactoryOptions): DatabaseModel;
}


export type IDatabaseModelFactory = IDatabaseModelFactory$instance;

export interface IProviderCodeGeneratorPlugin$instance {
    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
}


export type IProviderCodeGeneratorPlugin = IProviderCodeGeneratorPlugin$instance;

export interface IProviderConfigurationCodeGenerator$instance {
    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
    GenerateUseProvider(connectionString: string, providerOptions: MethodCallCodeFragment): MethodCallCodeFragment;
    GenerateUseProvider(connectionString: string): MethodCallCodeFragment;
}


export type IProviderConfigurationCodeGenerator = IProviderConfigurationCodeGenerator$instance;

export interface DatabaseModelFactory$instance {
    Create(connectionString: string, options: DatabaseModelFactoryOptions): DatabaseModel;
    Create(connection: DbConnection, options: DatabaseModelFactoryOptions): DatabaseModel;
}


export const DatabaseModelFactory: {
    new(): DatabaseModelFactory;
};


export interface __DatabaseModelFactory$views {
    As_IDatabaseModelFactory(): IDatabaseModelFactory$instance;
}

export type DatabaseModelFactory = DatabaseModelFactory$instance & __DatabaseModelFactory$views;


export interface DatabaseModelFactoryOptions$instance {
    readonly Schemas: IEnumerable<System_Internal.String>;
    readonly Tables: IEnumerable<System_Internal.String>;
}


export const DatabaseModelFactoryOptions: {
    new(tables: IEnumerable<System_Internal.String>, schemas: IEnumerable<System_Internal.String>): DatabaseModelFactoryOptions;
};


export type DatabaseModelFactoryOptions = DatabaseModelFactoryOptions$instance;

export abstract class ProviderCodeGenerator$protected {
    protected readonly Dependencies: ProviderCodeGeneratorDependencies;
}


export interface ProviderCodeGenerator$instance extends ProviderCodeGenerator$protected {
    GenerateContextOptions(): MethodCallCodeFragment | undefined;
    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
    GenerateUseProvider(connectionString: string, providerOptions: MethodCallCodeFragment): MethodCallCodeFragment;
    GenerateUseProvider(connectionString: string): MethodCallCodeFragment;
}


export const ProviderCodeGenerator: {
    new(dependencies: ProviderCodeGeneratorDependencies): ProviderCodeGenerator;
};


export interface __ProviderCodeGenerator$views {
    As_IProviderConfigurationCodeGenerator(): IProviderConfigurationCodeGenerator$instance;
}

export interface ProviderCodeGenerator$instance extends IProviderConfigurationCodeGenerator$instance {}

export type ProviderCodeGenerator = ProviderCodeGenerator$instance & __ProviderCodeGenerator$views;


export interface ProviderCodeGeneratorDependencies$instance {
    Plugins: IEnumerable<IProviderCodeGeneratorPlugin>;
    _Clone_$(): ProviderCodeGeneratorDependencies;
    Equals(obj: unknown): boolean;
    Equals(other: ProviderCodeGeneratorDependencies): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const ProviderCodeGeneratorDependencies: {
    new(plugins: IEnumerable<IProviderCodeGeneratorPlugin>): ProviderCodeGeneratorDependencies;
};


export type ProviderCodeGeneratorDependencies = ProviderCodeGeneratorDependencies$instance;

export interface ProviderCodeGeneratorPlugin$instance {
    GenerateContextOptions(): MethodCallCodeFragment | undefined;
    GenerateProviderOptions(): MethodCallCodeFragment | undefined;
}


export const ProviderCodeGeneratorPlugin: {
    new(): ProviderCodeGeneratorPlugin;
};


export interface __ProviderCodeGeneratorPlugin$views {
    As_IProviderCodeGeneratorPlugin(): IProviderCodeGeneratorPlugin$instance;
}

export interface ProviderCodeGeneratorPlugin$instance extends IProviderCodeGeneratorPlugin$instance {}

export type ProviderCodeGeneratorPlugin = ProviderCodeGeneratorPlugin$instance & __ProviderCodeGeneratorPlugin$views;


