// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.ChangeTracking
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Abstractions

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as Microsoft_EntityFrameworkCore_ChangeTracking_Internal_Internal from "../../Microsoft.EntityFrameworkCore.ChangeTracking.Internal/internal/index.js";
import type { IChangeDetector, IInternalEntry, InternalComplexEntry, InternalEntityEntry, InternalEntryBase, IStateManager } from "../../Microsoft.EntityFrameworkCore.ChangeTracking.Internal/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { DebugView, IInfrastructure_1, IResettableService } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IComplexProperty, IEntityType, IModel, INavigation, INavigationBase, IProperty, IPropertyBase, ITypeBase } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Update_Internal from "../../Microsoft.EntityFrameworkCore.Update/internal/index.js";
import type { IUpdateEntry } from "../../Microsoft.EntityFrameworkCore.Update/internal/index.js";
import type { DbContext, DbSet_1, EntityState, QueryTrackingBehavior } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { HashSet_1_Enumerator, ICollection_1, IComparer_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IEqualityComparer_1, IList_1, IReadOnlyCollection_1, IReadOnlyList_1, ISet_1, List_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_ObjectModel_Internal from "@tsonic/dotnet/System.Collections.ObjectModel/internal/index.js";
import type { ObservableCollection_1 } from "@tsonic/dotnet/System.Collections.ObjectModel/internal/index.js";
import * as System_Collections_Specialized_Internal from "@tsonic/dotnet/System.Collections.Specialized/internal/index.js";
import type { INotifyCollectionChanged, NotifyCollectionChangedEventArgs, NotifyCollectionChangedEventHandler } from "@tsonic/dotnet/System.Collections.Specialized/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { ICollection, IEnumerable, IEqualityComparer, IList } from "@tsonic/dotnet/System.Collections/internal/index.js";
import * as System_ComponentModel_Internal from "@tsonic/dotnet/System.ComponentModel/internal/index.js";
import type { BindingList_1, IListSource, INotifyPropertyChanged, INotifyPropertyChanging, PropertyChangedEventArgs, PropertyChangedEventHandler, PropertyChangingEventArgs, PropertyChangingEventHandler } from "@tsonic/dotnet/System.ComponentModel/internal/index.js";
import type { Expression, Expression_1, LambdaExpression } from "@tsonic/dotnet/System.Linq.Expressions/internal/index.js";
import type { IQueryable, IQueryable_1 } from "@tsonic/dotnet/System.Linq/internal/index.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import type { Task, Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Boolean as ClrBoolean, Enum, EventArgs, EventHandler_1, Func_2, Func_3, HashCode, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable_1, Object as ClrObject, Predicate_1, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export enum CascadeTiming {
    Immediate = 0,
    OnSaveChanges = 1,
    Never = 2
}


export enum ChangeTrackerDebugStringOptions {
    IncludeProperties = 1,
    IncludeNavigations = 2,
    ShortDefault = 0,
    LongDefault = 3
}


export enum LoadOptions {
    None = 0,
    ForceIdentityResolution = 1
}


export interface IDependentKeyValueFactory$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_ChangeTracking_IDependentKeyValueFactory: never;

    CreatePrincipalEquatableKey(entry: IUpdateEntry, fromOriginalValues?: boolean): unknown;
}


export type IDependentKeyValueFactory = IDependentKeyValueFactory$instance;

export interface IDependentKeyValueFactory_1$instance<TKey extends unknown> extends IDependentKeyValueFactory {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_ChangeTracking_IDependentKeyValueFactory_1: never;

    readonly EqualityComparer: IEqualityComparer_1<TKey>;
    CreatePrincipalEquatableKey(entry: IUpdateEntry, fromOriginalValues?: boolean): unknown;
    TryCreateFromCurrentValues(entry: IUpdateEntry, key: TKey | null): boolean;
}


export interface IDependentKeyValueFactory_1$instance<TKey extends unknown> extends IDependentKeyValueFactory$instance {}

export type IDependentKeyValueFactory_1<TKey extends unknown> = IDependentKeyValueFactory_1$instance<TKey>;

export interface IEntityEntryGraphIterator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_ChangeTracking_IEntityEntryGraphIterator: never;

    TraverseGraph<TState extends unknown>(node: EntityEntryGraphNode_1<TState>, handleNode: Func_2<EntityEntryGraphNode_1<TState>, System_Internal.Boolean>): void;
    TraverseGraphAsync<TState extends unknown>(node: EntityEntryGraphNode_1<TState>, handleNode: Func_3<EntityEntryGraphNode_1<TState>, CancellationToken, Task_1<System_Internal.Boolean>>, cancellationToken?: CancellationToken): Task;
}


export type IEntityEntryGraphIterator = IEntityEntryGraphIterator$instance;

export interface IPrincipalKeyValueFactory$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_ChangeTracking_IPrincipalKeyValueFactory: never;

    CreateEquatableKey(entry: IUpdateEntry, fromOriginalValues?: boolean): unknown;
}


export type IPrincipalKeyValueFactory = IPrincipalKeyValueFactory$instance;

export interface IPrincipalKeyValueFactory_1$instance<TKey extends unknown> extends IPrincipalKeyValueFactory {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_ChangeTracking_IPrincipalKeyValueFactory_1: never;

    readonly EqualityComparer: IEqualityComparer_1<TKey>;
    CreateEquatableKey(entry: IUpdateEntry, fromOriginalValues?: boolean): unknown;
    CreateFromCurrentValues(entry: IUpdateEntry): TKey;
    CreateFromKeyValues(keyValues: IReadOnlyList_1<unknown | null>): unknown | null;
    CreateFromRelationshipSnapshot(entry: IUpdateEntry): TKey;
    FindNullPropertyInCurrentValues(entry: IUpdateEntry): IProperty;
    FindNullPropertyInKeyValues(keyValues: IReadOnlyList_1<unknown | null>): IProperty;
}


export interface IPrincipalKeyValueFactory_1$instance<TKey extends unknown> extends IPrincipalKeyValueFactory$instance {}

export type IPrincipalKeyValueFactory_1<TKey extends unknown> = IPrincipalKeyValueFactory_1$instance<TKey>;

export interface ArrayStructuralComparer_1$instance<TElement extends unknown> extends ValueComparer_1<TElement[]> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ArrayStructuralComparer_1: never;

    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

}


export const ArrayStructuralComparer_1: {
    new<TElement extends unknown>(): ArrayStructuralComparer_1<TElement>;
};


export type ArrayStructuralComparer_1<TElement extends unknown> = ArrayStructuralComparer_1$instance<TElement>;

export interface CaseInsensitiveValueComparer$instance extends ValueComparer_1<System_Internal.String> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_CaseInsensitiveValueComparer: never;

    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

}


export const CaseInsensitiveValueComparer: {
    new(): CaseInsensitiveValueComparer;
};


export type CaseInsensitiveValueComparer = CaseInsensitiveValueComparer$instance;

export interface ChangeTracker$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IResettableService$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ChangeTracker: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IResettableService: never;

    AutoDetectChangesEnabled: boolean;
    CascadeDeleteTiming: CascadeTiming;
    readonly Context: DbContext;
    readonly DebugView: DebugView;
    DeleteOrphansTiming: CascadeTiming;
    LazyLoadingEnabled: boolean;
    QueryTrackingBehavior: QueryTrackingBehavior;
    AcceptAllChanges(): void;
    CascadeChanges(): void;
    Clear(): void;
    DetectChanges(): void;
    Entries(): IEnumerable_1<EntityEntry>;
    Entries<TEntity extends (object | null)>(): IEnumerable_1<EntityEntry_1<TEntity>>;
    Equals(obj: unknown | null): boolean;
    GetHashCode(): int;
    HasChanges(): boolean;
    ToString(): string | null;
    TrackGraph(rootEntity: unknown, callback: Action_1<EntityEntryGraphNode>): void;
    TrackGraph<TState extends unknown>(rootEntity: unknown, state: TState, callback: Func_2<EntityEntryGraphNode_1<TState>, System_Internal.Boolean>): void;
}


export const ChangeTracker: {
    new(context: DbContext, stateManager: IStateManager, changeDetector: IChangeDetector, model: IModel, graphIterator: IEntityEntryGraphIterator): ChangeTracker;
};


export interface __ChangeTracker$views {
    As_IResettableService(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IResettableService$instance;
}

export type ChangeTracker = ChangeTracker$instance & __ChangeTracker$views;


export interface CollectionEntry$instance extends NavigationEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_CollectionEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    CurrentValue: IEnumerable | unknown;
    IsModified: boolean;
    FindEntry(entity: unknown): EntityEntry | null;
    GetInternalTargetEntry(entity: unknown): InternalEntityEntry | null;
    Load(): void;
    Load(options: LoadOptions): void;
    LoadAsync(cancellationToken?: CancellationToken): Task;
    LoadAsync(options: LoadOptions, cancellationToken?: CancellationToken): Task;
    Query(): IQueryable;
}


export const CollectionEntry: {
    new(internalEntry: InternalEntityEntry, name: string): CollectionEntry;
    new(internalEntry: InternalEntityEntry, navigationBase: INavigationBase): CollectionEntry;
};


export interface __CollectionEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type CollectionEntry = CollectionEntry$instance & __CollectionEntry$views;


export interface CollectionEntry_2$instance<TEntity extends (object | null), TRelatedEntity extends (object | null)> extends CollectionEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_CollectionEntry_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly EntityEntry: EntityEntry_1<TEntity>;
    FindEntry(entity: unknown): EntityEntry_1<TRelatedEntity> | null;
    FindEntry(entity: unknown): EntityEntry | null;
    Query(): IQueryable_1<TRelatedEntity>;
    Query(): IQueryable;
}


export const CollectionEntry_2: {
    new<TEntity extends (object | null), TRelatedEntity extends (object | null)>(internalEntry: InternalEntityEntry, name: string): CollectionEntry_2<TEntity, TRelatedEntity>;
    new<TEntity extends (object | null), TRelatedEntity extends (object | null)>(internalEntry: InternalEntityEntry, navigationBase: INavigationBase): CollectionEntry_2<TEntity, TRelatedEntity>;
};


export interface __CollectionEntry_2$views<TEntity extends (object | null), TRelatedEntity extends (object | null)> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type CollectionEntry_2<TEntity extends (object | null), TRelatedEntity extends (object | null)> = CollectionEntry_2$instance<TEntity, TRelatedEntity> & __CollectionEntry_2$views<TEntity, TRelatedEntity>;


export interface ComplexCollectionEntry$instance extends MemberEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ComplexCollectionEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    IsModified: boolean;
    GetEnumerator(): IEnumerator_1<ComplexElementEntry>;
    GetOriginalEntry(ordinal: int): ComplexElementEntry;
}


export const ComplexCollectionEntry: {
    new(internalEntry: IInternalEntry, complexProperty: IComplexProperty): ComplexCollectionEntry;
};


export interface __ComplexCollectionEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type ComplexCollectionEntry = ComplexCollectionEntry$instance & __ComplexCollectionEntry$views & { readonly [ordinal: number]: ComplexElementEntry; };


export interface ComplexCollectionEntry_2$instance<TEntity extends (object | null), TElement extends unknown> extends ComplexCollectionEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ComplexCollectionEntry_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly EntityEntry: EntityEntry_1<TEntity>;
    GetOriginalEntry(ordinal: int): ComplexElementEntry_2<TEntity, TElement>;
    GetOriginalEntry(ordinal: int): ComplexElementEntry;
}


export const ComplexCollectionEntry_2: {
    new<TEntity extends (object | null), TElement extends unknown>(internalEntry: IInternalEntry, property: IComplexProperty): ComplexCollectionEntry_2<TEntity, TElement>;
};


export interface __ComplexCollectionEntry_2$views<TEntity extends (object | null), TElement extends unknown> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type ComplexCollectionEntry_2<TEntity extends (object | null), TElement extends unknown> = ComplexCollectionEntry_2$instance<TEntity, TElement> & __ComplexCollectionEntry_2$views<TEntity, TElement> & { readonly [ordinal: number]: ComplexElementEntry_2<TEntity, TElement>; };


export interface ComplexElementEntry$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalComplexEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ComplexElementEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly ComplexCollections: IEnumerable_1<ComplexCollectionEntry>;
    readonly ComplexProperties: IEnumerable_1<ComplexPropertyEntry>;
    readonly CurrentValue: unknown;
    readonly EntityEntry: EntityEntry;
    readonly InternalEntry: InternalComplexEntry;
    IsModified: boolean;
    readonly Metadata: IComplexProperty;
    readonly Properties: IEnumerable_1<PropertyEntry>;
    State: EntityState;
    ComplexCollection(property: IComplexProperty): ComplexCollectionEntry;
    ComplexCollection(propertyName: string): ComplexCollectionEntry;
    ComplexProperty(property: IComplexProperty): ComplexPropertyEntry;
    ComplexProperty(propertyName: string): ComplexPropertyEntry;
    Property(property: IProperty): PropertyEntry;
    Property(propertyName: string): PropertyEntry;
}


export const ComplexElementEntry: {
    new(internalEntry: InternalComplexEntry): ComplexElementEntry;
};


export interface __ComplexElementEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalComplexEntry>;
}

export type ComplexElementEntry = ComplexElementEntry$instance & __ComplexElementEntry$views;


export interface ComplexElementEntry_2$instance<TEntity extends (object | null), TComplexProperty extends unknown> extends ComplexElementEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalComplexEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ComplexElementEntry_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    ComplexCollection<TElement extends unknown>(propertyExpression: Expression_1<Func_2<TComplexProperty, IEnumerable_1<TElement> | null>>): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection<TElement extends unknown>(property: IComplexProperty): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection<TElement extends unknown>(propertyName: string): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection(property: IComplexProperty): ComplexCollectionEntry;
    ComplexProperty<TNestedComplexProperty extends unknown>(propertyExpression: Expression_1<Func_2<TComplexProperty, TNestedComplexProperty>>): ComplexPropertyEntry_2<TEntity, TNestedComplexProperty>;
    ComplexProperty<TNestedComplexProperty extends unknown>(complexProperty: IComplexProperty): ComplexPropertyEntry_2<TEntity, TNestedComplexProperty>;
    ComplexProperty<TNestedComplexProperty extends unknown>(propertyName: string): ComplexPropertyEntry_2<TEntity, TNestedComplexProperty>;
    ComplexProperty(property: IComplexProperty): ComplexPropertyEntry;
    Property<TProperty extends unknown>(propertyExpression: Expression_1<Func_2<TComplexProperty, TProperty | null>>): PropertyEntry_2<TEntity, TProperty>;
    Property<TProperty extends unknown>(property: IProperty): PropertyEntry_2<TEntity, TProperty>;
    Property<TProperty extends unknown>(propertyName: string): PropertyEntry_2<TEntity, TProperty>;
    Property(property: IProperty): PropertyEntry;
}


export const ComplexElementEntry_2: {
    new<TEntity extends (object | null), TComplexProperty extends unknown>(internalEntry: InternalComplexEntry): ComplexElementEntry_2<TEntity, TComplexProperty>;
};


export interface __ComplexElementEntry_2$views<TEntity extends (object | null), TComplexProperty extends unknown> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalComplexEntry>;
}

export type ComplexElementEntry_2<TEntity extends (object | null), TComplexProperty extends unknown> = ComplexElementEntry_2$instance<TEntity, TComplexProperty> & __ComplexElementEntry_2$views<TEntity, TComplexProperty>;


export interface ComplexPropertyEntry$instance extends MemberEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ComplexPropertyEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly ComplexCollections: IEnumerable_1<ComplexCollectionEntry>;
    readonly ComplexProperties: IEnumerable_1<ComplexPropertyEntry>;
    IsModified: boolean;
    readonly Properties: IEnumerable_1<PropertyEntry>;
    ComplexCollection(property: IComplexProperty): ComplexCollectionEntry;
    ComplexCollection(propertyName: string): ComplexCollectionEntry;
    ComplexProperty(property: IComplexProperty): ComplexPropertyEntry;
    ComplexProperty(propertyName: string): ComplexPropertyEntry;
    Property(property: IProperty): PropertyEntry;
    Property(propertyName: string): PropertyEntry;
}


export const ComplexPropertyEntry: {
    new(internalEntry: IInternalEntry, complexProperty: IComplexProperty): ComplexPropertyEntry;
};


export interface __ComplexPropertyEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type ComplexPropertyEntry = ComplexPropertyEntry$instance & __ComplexPropertyEntry$views;


export interface ComplexPropertyEntry_2$instance<TEntity extends (object | null), TComplexProperty extends unknown> extends ComplexPropertyEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ComplexPropertyEntry_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    CurrentValue: TComplexProperty;
    readonly EntityEntry: EntityEntry_1<TEntity>;
    ComplexCollection<TElement extends unknown>(propertyExpression: Expression_1<Func_2<TComplexProperty, IEnumerable_1<TElement> | null>>): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection<TElement extends unknown>(property: IComplexProperty): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection<TElement extends unknown>(propertyName: string): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection(property: IComplexProperty): ComplexCollectionEntry;
    ComplexProperty<TNestedComplexProperty extends unknown>(propertyExpression: Expression_1<Func_2<TComplexProperty, TNestedComplexProperty | null>>): ComplexPropertyEntry_2<TEntity, TNestedComplexProperty>;
    ComplexProperty<TNestedComplexProperty extends unknown>(complexProperty: IComplexProperty): ComplexPropertyEntry_2<TEntity, TNestedComplexProperty>;
    ComplexProperty<TNestedComplexProperty extends unknown>(propertyName: string): ComplexPropertyEntry_2<TEntity, TNestedComplexProperty>;
    ComplexProperty(property: IComplexProperty): ComplexPropertyEntry;
    Property<TProperty extends unknown>(propertyExpression: Expression_1<Func_2<TComplexProperty, TProperty>>): PropertyEntry_2<TEntity, TProperty>;
    Property<TProperty extends unknown>(property: IProperty): PropertyEntry_2<TEntity, TProperty>;
    Property<TProperty extends unknown>(propertyName: string): PropertyEntry_2<TEntity, TProperty>;
    Property(property: IProperty): PropertyEntry;
}


export const ComplexPropertyEntry_2: {
    new<TEntity extends (object | null), TComplexProperty extends unknown>(internalEntry: IInternalEntry, complexProperty: IComplexProperty): ComplexPropertyEntry_2<TEntity, TComplexProperty>;
};


export interface __ComplexPropertyEntry_2$views<TEntity extends (object | null), TComplexProperty extends unknown> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type ComplexPropertyEntry_2<TEntity extends (object | null), TComplexProperty extends unknown> = ComplexPropertyEntry_2$instance<TEntity, TComplexProperty> & __ComplexPropertyEntry_2$views<TEntity, TComplexProperty>;


export interface DetectChangesEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_DetectChangesEventArgs: never;

}


export const DetectChangesEventArgs: {
    new(): DetectChangesEventArgs;
};


export type DetectChangesEventArgs = DetectChangesEventArgs$instance;

export interface DetectedChangesEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_DetectedChangesEventArgs: never;

    readonly ChangesFound: boolean;
}


export const DetectedChangesEventArgs: {
    new(changesFound: boolean): DetectedChangesEventArgs;
};


export type DetectedChangesEventArgs = DetectedChangesEventArgs$instance;

export interface DetectedEntityChangesEventArgs$instance extends DetectedChangesEventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_DetectedEntityChangesEventArgs: never;

    readonly Entry: EntityEntry;
}


export const DetectedEntityChangesEventArgs: {
    new(internalEntityEntry: InternalEntityEntry, changesFound: boolean): DetectedEntityChangesEventArgs;
};


export type DetectedEntityChangesEventArgs = DetectedEntityChangesEventArgs$instance;

export interface DetectEntityChangesEventArgs$instance extends DetectChangesEventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_DetectEntityChangesEventArgs: never;

    readonly Entry: EntityEntry;
}


export const DetectEntityChangesEventArgs: {
    new(internalEntityEntry: InternalEntityEntry): DetectEntityChangesEventArgs;
};


export type DetectEntityChangesEventArgs = DetectEntityChangesEventArgs$instance;

export interface EntityEntry$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly Collections: IEnumerable_1<CollectionEntry>;
    readonly ComplexCollections: IEnumerable_1<ComplexCollectionEntry>;
    readonly ComplexProperties: IEnumerable_1<ComplexPropertyEntry>;
    readonly Context: DbContext;
    readonly CurrentValues: PropertyValues;
    readonly DebugView: DebugView;
    readonly Entity: unknown;
    readonly InternalEntry: InternalEntityEntry;
    readonly IsKeySet: boolean;
    readonly Members: IEnumerable_1<MemberEntry>;
    readonly Metadata: IEntityType;
    readonly Navigations: IEnumerable_1<NavigationEntry>;
    readonly OriginalValues: PropertyValues;
    readonly Properties: IEnumerable_1<PropertyEntry>;
    readonly References: IEnumerable_1<ReferenceEntry>;
    State: EntityState;
    Collection(navigation: INavigationBase): CollectionEntry;
    Collection(propertyName: string): CollectionEntry;
    ComplexCollection(property: IComplexProperty): ComplexCollectionEntry;
    ComplexCollection(propertyName: string): ComplexCollectionEntry;
    ComplexProperty(property: IComplexProperty): ComplexPropertyEntry;
    ComplexProperty(propertyName: string): ComplexPropertyEntry;
    DetectChanges(): void;
    Equals(obj: unknown | null): boolean;
    GetDatabaseValues(): PropertyValues | null;
    GetDatabaseValuesAsync(cancellationToken?: CancellationToken): Task_1<PropertyValues | null>;
    GetHashCode(): int;
    Member(propertyBase: IPropertyBase): MemberEntry;
    Member(propertyName: string): MemberEntry;
    Navigation(navigationBase: INavigationBase): NavigationEntry;
    Navigation(propertyName: string): NavigationEntry;
    Property(property: IProperty): PropertyEntry;
    Property(propertyName: string): PropertyEntry;
    Reference(navigation: INavigationBase): ReferenceEntry;
    Reference(propertyName: string): ReferenceEntry;
    Reload(): void;
    ReloadAsync(cancellationToken?: CancellationToken): Task;
    ToString(): string;
}


export const EntityEntry: {
    new(internalEntry: InternalEntityEntry): EntityEntry;
};


export interface __EntityEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry>;
}

export type EntityEntry = EntityEntry$instance & __EntityEntry$views;


export interface EntityEntry_1$instance<TEntity extends (object | null)> extends EntityEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntry_1: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    Collection<TProperty extends (object | null)>(propertyExpression: Expression_1<Func_2<TEntity, IEnumerable_1<TProperty>>>): CollectionEntry_2<TEntity, TProperty>;
    Collection<TProperty extends (object | null)>(navigation: INavigationBase): CollectionEntry_2<TEntity, TProperty>;
    Collection<TProperty extends (object | null)>(propertyName: string): CollectionEntry_2<TEntity, TProperty>;
    Collection(navigation: INavigationBase): CollectionEntry;
    ComplexCollection<TElement extends unknown>(propertyExpression: Expression_1<Func_2<TEntity, IEnumerable_1<TElement> | null>>): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection<TElement extends unknown>(complexProperty: IComplexProperty): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection<TElement extends unknown>(propertyName: string): ComplexCollectionEntry_2<TEntity, TElement>;
    ComplexCollection(property: IComplexProperty): ComplexCollectionEntry;
    ComplexProperty<TProperty extends unknown>(propertyExpression: Expression_1<Func_2<TEntity, TProperty | null>>): ComplexPropertyEntry_2<TEntity, TProperty>;
    ComplexProperty<TProperty extends unknown>(complexProperty: IComplexProperty): ComplexPropertyEntry_2<TEntity, TProperty>;
    ComplexProperty<TProperty extends unknown>(propertyName: string): ComplexPropertyEntry_2<TEntity, TProperty>;
    ComplexProperty(property: IComplexProperty): ComplexPropertyEntry;
    Property<TProperty extends unknown>(propertyExpression: Expression_1<Func_2<TEntity, TProperty>>): PropertyEntry_2<TEntity, TProperty>;
    Property<TProperty extends unknown>(property: IProperty): PropertyEntry_2<TEntity, TProperty>;
    Property<TProperty extends unknown>(propertyName: string): PropertyEntry_2<TEntity, TProperty>;
    Property(property: IProperty): PropertyEntry;
    Reference<TProperty extends (object | null)>(propertyExpression: Expression_1<Func_2<TEntity, TProperty | null>>): ReferenceEntry_2<TEntity, TProperty>;
    Reference<TProperty extends (object | null)>(navigation: INavigationBase): ReferenceEntry_2<TEntity, TProperty>;
    Reference<TProperty extends (object | null)>(propertyName: string): ReferenceEntry_2<TEntity, TProperty>;
    Reference(navigation: INavigationBase): ReferenceEntry;
}


export const EntityEntry_1: {
    new<TEntity extends (object | null)>(internalEntry: InternalEntityEntry): EntityEntry_1<TEntity>;
};


export interface __EntityEntry_1$views<TEntity extends (object | null)> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry>;
}

export type EntityEntry_1<TEntity extends (object | null)> = EntityEntry_1$instance<TEntity> & __EntityEntry_1$views<TEntity>;


export interface EntityEntryEventArgs$instance extends EventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntryEventArgs: never;

    readonly Entry: EntityEntry;
}


export const EntityEntryEventArgs: {
    new(internalEntityEntry: InternalEntityEntry): EntityEntryEventArgs;
};


export type EntityEntryEventArgs = EntityEntryEventArgs$instance;

export interface EntityEntryGraphNode$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntryGraphNode: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly Entry: EntityEntry;
    readonly InboundNavigation: INavigationBase | null;
    readonly SourceEntry: EntityEntry | null;
    CreateNode(currentNode: EntityEntryGraphNode, internalEntityEntry: InternalEntityEntry, reachedVia: INavigationBase): EntityEntryGraphNode;
}


export const EntityEntryGraphNode: {
    new(entry: InternalEntityEntry, sourceEntry: InternalEntityEntry | null, inboundNavigation: INavigationBase | null): EntityEntryGraphNode;
};


export interface __EntityEntryGraphNode$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry>;
}

export type EntityEntryGraphNode = EntityEntryGraphNode$instance & __EntityEntryGraphNode$views;


export interface EntityEntryGraphNode_1$instance<TState extends unknown> extends EntityEntryGraphNode$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntryGraphNode_1: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    NodeState: TState;
    CreateNode(currentNode: EntityEntryGraphNode, internalEntityEntry: InternalEntityEntry, reachedVia: INavigationBase): EntityEntryGraphNode;
}


export const EntityEntryGraphNode_1: {
    new<TState extends unknown>(entry: InternalEntityEntry, state: TState, sourceEntry: InternalEntityEntry | null, inboundNavigation: INavigationBase | null): EntityEntryGraphNode_1<TState>;
    new<TState extends unknown>(entry: EntityEntry, state: TState, sourceEntry: EntityEntry | null, inboundNavigation: INavigationBase | null): EntityEntryGraphNode_1<TState>;
};


export interface __EntityEntryGraphNode_1$views<TState extends unknown> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<InternalEntityEntry>;
}

export type EntityEntryGraphNode_1<TState extends unknown> = EntityEntryGraphNode_1$instance<TState> & __EntityEntryGraphNode_1$views<TState>;


export interface EntityStateChangedEventArgs$instance extends EntityEntryEventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityStateChangedEventArgs: never;

    readonly NewState: EntityState;
    readonly OldState: EntityState;
}


export const EntityStateChangedEventArgs: {
    new(internalEntityEntry: InternalEntityEntry, oldState: EntityState, newState: EntityState): EntityStateChangedEventArgs;
};


export type EntityStateChangedEventArgs = EntityStateChangedEventArgs$instance;

export interface EntityStateChangingEventArgs$instance extends EntityEntryEventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityStateChangingEventArgs: never;

    readonly NewState: EntityState;
    readonly OldState: EntityState;
}


export const EntityStateChangingEventArgs: {
    new(internalEntityEntry: InternalEntityEntry, oldState: EntityState, newState: EntityState): EntityStateChangingEventArgs;
};


export type EntityStateChangingEventArgs = EntityStateChangingEventArgs$instance;

export interface EntityTrackedEventArgs$instance extends EntityEntryEventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityTrackedEventArgs: never;

    readonly FromQuery: boolean;
}


export const EntityTrackedEventArgs: {
    new(internalEntityEntry: InternalEntityEntry, fromQuery: boolean): EntityTrackedEventArgs;
};


export type EntityTrackedEventArgs = EntityTrackedEventArgs$instance;

export interface EntityTrackingEventArgs$instance extends EntityEntryEventArgs {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntityTrackingEventArgs: never;

    readonly FromQuery: boolean;
    readonly State: EntityState;
}


export const EntityTrackingEventArgs: {
    new(internalEntityEntry: InternalEntityEntry, state: EntityState, fromQuery: boolean): EntityTrackingEventArgs;
};


export type EntityTrackingEventArgs = EntityTrackingEventArgs$instance;

export interface EntryCurrentValueComparer_1$instance<TProperty extends unknown> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_EntryCurrentValueComparer_1: never;

    readonly __tsonic_iface_System_Collections_Generic_IComparer_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;

    Compare(x: IUpdateEntry | null, y: IUpdateEntry | null): int;
    Equals(x: IUpdateEntry | null, y: IUpdateEntry | null): boolean;
    GetHashCode(obj: IUpdateEntry): int;
}


export const EntryCurrentValueComparer_1: {
    new<TProperty extends unknown>(property: IPropertyBase): EntryCurrentValueComparer_1<TProperty>;
};


export type EntryCurrentValueComparer_1<TProperty extends unknown> = EntryCurrentValueComparer_1$instance<TProperty>;

export interface GeometryValueComparer_1$instance<TGeometry extends unknown> extends ValueComparer_1<TGeometry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_GeometryValueComparer_1: never;

    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

}


export const GeometryValueComparer_1: {
    new<TGeometry extends unknown>(): GeometryValueComparer_1<TGeometry>;
};


export type GeometryValueComparer_1<TGeometry extends unknown> = GeometryValueComparer_1$instance<TGeometry>;

export interface ListOfNullableValueTypesComparer_2$instance<TConcreteList extends unknown, TElement extends NonNullable<unknown>> extends ValueComparer_1<IEnumerable_1<Nullable_1<TElement>>>, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<ValueComparer>, System_Collections_Generic_Internal.IEqualityComparer_1<unknown>, System_Collections_Generic_Internal.IEqualityComparer_1<IEnumerable_1<Nullable_1<TElement>>> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ListOfNullableValueTypesComparer_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

    readonly ElementComparer: ValueComparer;
}


export const ListOfNullableValueTypesComparer_2: {
    new<TConcreteList extends unknown, TElement extends NonNullable<unknown>>(elementComparer: ValueComparer): ListOfNullableValueTypesComparer_2<TConcreteList, TElement>;
};


export interface __ListOfNullableValueTypesComparer_2$views<TConcreteList extends unknown, TElement extends NonNullable<unknown>> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<ValueComparer>;
}

export type ListOfNullableValueTypesComparer_2<TConcreteList extends unknown, TElement extends NonNullable<unknown>> = ListOfNullableValueTypesComparer_2$instance<TConcreteList, TElement> & __ListOfNullableValueTypesComparer_2$views<TConcreteList, TElement>;


export interface ListOfReferenceTypesComparer_2$instance<TConcreteList extends unknown, TElement extends (object | null)> extends ValueComparer_1<unknown>, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<ValueComparer>, System_Collections_Generic_Internal.IEqualityComparer_1<unknown> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ListOfReferenceTypesComparer_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

    readonly ElementComparer: ValueComparer;
}


export const ListOfReferenceTypesComparer_2: {
    new<TConcreteList extends unknown, TElement extends (object | null)>(elementComparer: ValueComparer): ListOfReferenceTypesComparer_2<TConcreteList, TElement>;
};


export interface __ListOfReferenceTypesComparer_2$views<TConcreteList extends unknown, TElement extends (object | null)> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<ValueComparer>;
}

export type ListOfReferenceTypesComparer_2<TConcreteList extends unknown, TElement extends (object | null)> = ListOfReferenceTypesComparer_2$instance<TConcreteList, TElement> & __ListOfReferenceTypesComparer_2$views<TConcreteList, TElement>;


export interface ListOfValueTypesComparer_2$instance<TConcreteList extends unknown, TElement extends NonNullable<unknown>> extends ValueComparer_1<IEnumerable_1<TElement>>, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<ValueComparer>, System_Collections_Generic_Internal.IEqualityComparer_1<unknown>, System_Collections_Generic_Internal.IEqualityComparer_1<IEnumerable_1<TElement>> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ListOfValueTypesComparer_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

    readonly ElementComparer: ValueComparer;
}


export const ListOfValueTypesComparer_2: {
    new<TConcreteList extends unknown, TElement extends NonNullable<unknown>>(elementComparer: ValueComparer): ListOfValueTypesComparer_2<TConcreteList, TElement>;
};


export interface __ListOfValueTypesComparer_2$views<TConcreteList extends unknown, TElement extends NonNullable<unknown>> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<ValueComparer>;
}

export type ListOfValueTypesComparer_2<TConcreteList extends unknown, TElement extends NonNullable<unknown>> = ListOfValueTypesComparer_2$instance<TConcreteList, TElement> & __ListOfValueTypesComparer_2$views<TConcreteList, TElement>;


export interface LocalView_1$instance<TEntity extends (object | null)> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_LocalView_1: never;

    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_Specialized_INotifyCollectionChanged: never;
    readonly __tsonic_iface_System_ComponentModel_IListSource: never;
    readonly __tsonic_iface_System_ComponentModel_INotifyPropertyChanged: never;
    readonly __tsonic_iface_System_ComponentModel_INotifyPropertyChanging: never;

    readonly Count: int;
    readonly IsReadOnly: boolean;
    Add(item: TEntity): void;
    Clear(): void;
    Contains(item: TEntity): boolean;
    CopyTo(array: TEntity[], arrayIndex: int): void;
    FindEntry<TKey extends unknown>(keyValue: TKey): EntityEntry_1<TEntity> | null;
    FindEntry<TProperty extends unknown>(propertyName: string, propertyValue: TProperty | null): EntityEntry_1<TEntity> | null;
    FindEntry(propertyNames: IEnumerable_1<System_Internal.String>, propertyValues: IEnumerable_1<unknown | null>): EntityEntry_1<TEntity> | null;
    FindEntry<TProperty extends unknown>(property: IProperty, propertyValue: TProperty | null): EntityEntry_1<TEntity> | null;
    FindEntry(properties: IEnumerable_1<IProperty>, propertyValues: IEnumerable_1<unknown | null>): EntityEntry_1<TEntity> | null;
    FindEntryUntyped(keyValues: IEnumerable_1<unknown | null>): EntityEntry_1<TEntity> | null;
    GetEntries<TProperty extends unknown>(propertyName: string, propertyValue: TProperty | null): IEnumerable_1<EntityEntry_1<TEntity>>;
    GetEntries(propertyNames: IEnumerable_1<System_Internal.String>, propertyValues: IEnumerable_1<unknown | null>): IEnumerable_1<EntityEntry_1<TEntity>>;
    GetEntries<TProperty extends unknown>(property: IProperty, propertyValue: TProperty | null): IEnumerable_1<EntityEntry_1<TEntity>>;
    GetEntries(properties: IEnumerable_1<IProperty>, propertyValues: IEnumerable_1<unknown | null>): IEnumerable_1<EntityEntry_1<TEntity>>;
    GetEnumerator(): IEnumerator_1<TEntity>;
    OnCollectionChanged(e: NotifyCollectionChangedEventArgs): void;
    OnPropertyChanged(e: PropertyChangedEventArgs): void;
    OnPropertyChanging(e: PropertyChangingEventArgs): void;
    Remove(item: TEntity): boolean;
    Reset(): void;
    ToBindingList(): BindingList_1<TEntity>;
    ToObservableCollection(): ObservableCollection_1<TEntity>;
}


export const LocalView_1: {
    new<TEntity extends (object | null)>(set: DbSet_1<TEntity>): LocalView_1<TEntity>;
};


export type LocalView_1<TEntity extends (object | null)> = LocalView_1$instance<TEntity>;

export interface MemberEntry$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_MemberEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    CurrentValue: IEnumerable | unknown;
    readonly EntityEntry: EntityEntry;
    readonly InternalEntry: IInternalEntry;
    IsModified: boolean;
    readonly Metadata: IComplexProperty | IPropertyBase;
    Equals(obj: unknown | null): boolean;
    GetHashCode(): int;
    ToString(): string | null;
}


export const MemberEntry: (abstract new(internalEntry: IInternalEntry, metadata: IPropertyBase) => MemberEntry) & {
};


export interface __MemberEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type MemberEntry = MemberEntry$instance & __MemberEntry$views;


export interface NavigationEntry$instance extends MemberEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_NavigationEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    readonly InternalEntityEntry: InternalEntityEntry;
    IsLoaded: boolean;
    Load(): void;
    Load(options: LoadOptions): void;
    LoadAsync(cancellationToken?: CancellationToken): Task;
    LoadAsync(options: LoadOptions, cancellationToken?: CancellationToken): Task;
    Query(): IQueryable;
}


export const NavigationEntry: (abstract new(internalEntry: InternalEntityEntry, name: string, collection: boolean) => NavigationEntry) & (abstract new(internalEntry: InternalEntityEntry, navigationBase: INavigationBase, collection: boolean) => NavigationEntry) & {
};


export interface __NavigationEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type NavigationEntry = NavigationEntry$instance & __NavigationEntry$views;


export interface ObservableCollectionListSource_1$instance<T extends (object | null)> extends ObservableCollection_1<T> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ObservableCollectionListSource_1: never;

    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IList_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyList_1: never;
    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IList: never;
    readonly __tsonic_iface_System_Collections_Specialized_INotifyCollectionChanged: never;
    readonly __tsonic_iface_System_ComponentModel_IListSource: never;
    readonly __tsonic_iface_System_ComponentModel_INotifyPropertyChanged: never;

}


export const ObservableCollectionListSource_1: {
    new<T extends (object | null)>(): ObservableCollectionListSource_1<T>;
    new<T extends (object | null)>(collection: IEnumerable_1<T>): ObservableCollectionListSource_1<T>;
    new<T extends (object | null)>(list: List_1<T>): ObservableCollectionListSource_1<T>;
};


export type ObservableCollectionListSource_1<T extends (object | null)> = ObservableCollectionListSource_1$instance<T>;

export interface ObservableHashSet_1$instance<T extends unknown> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ObservableHashSet_1: never;

    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IReadOnlyCollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_ISet_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_Specialized_INotifyCollectionChanged: never;
    readonly __tsonic_iface_System_ComponentModel_INotifyPropertyChanged: never;
    readonly __tsonic_iface_System_ComponentModel_INotifyPropertyChanging: never;

    readonly Comparer: IEqualityComparer_1<T>;
    readonly Count: int;
    readonly IsReadOnly: boolean;
    Add(item: T): boolean;
    Clear(): void;
    Contains(item: T): boolean;
    CopyTo(array: T[], arrayIndex: int): void;
    CopyTo(array: T[]): void;
    CopyTo(array: T[], arrayIndex: int, count: int): void;
    ExceptWith(other: IEnumerable_1<T>): void;
    GetEnumerator(): HashSet_1_Enumerator<T>;
    IntersectWith(other: IEnumerable_1<T>): void;
    IsProperSubsetOf(other: IEnumerable_1<T>): boolean;
    IsProperSupersetOf(other: IEnumerable_1<T>): boolean;
    IsSubsetOf(other: IEnumerable_1<T>): boolean;
    IsSupersetOf(other: IEnumerable_1<T>): boolean;
    OnCollectionChanged(e: NotifyCollectionChangedEventArgs): void;
    OnPropertyChanged(e: PropertyChangedEventArgs): void;
    OnPropertyChanging(e: PropertyChangingEventArgs): void;
    Overlaps(other: IEnumerable_1<T>): boolean;
    Remove(item: T): boolean;
    RemoveWhere(match: Predicate_1<T>): int;
    SetEquals(other: IEnumerable_1<T>): boolean;
    SymmetricExceptWith(other: IEnumerable_1<T>): void;
    TrimExcess(): void;
    UnionWith(other: IEnumerable_1<T>): void;
}


export const ObservableHashSet_1: {
    new<T extends unknown>(): ObservableHashSet_1<T>;
    new<T extends unknown>(comparer: IEqualityComparer_1<T>): ObservableHashSet_1<T>;
    new<T extends unknown>(collection: IEnumerable_1<T>): ObservableHashSet_1<T>;
    new<T extends unknown>(collection: IEnumerable_1<T>, comparer: IEqualityComparer_1<T>): ObservableHashSet_1<T>;
};


export type ObservableHashSet_1<T extends unknown> = ObservableHashSet_1$instance<T>;

export interface PropertyEntry$instance extends MemberEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_PropertyEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    IsModified: boolean;
    IsTemporary: boolean;
    OriginalValue: unknown;
}


export const PropertyEntry: {
    new(internalEntry: IInternalEntry, property: IProperty): PropertyEntry;
};


export interface __PropertyEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type PropertyEntry = PropertyEntry$instance & __PropertyEntry$views;


export interface PropertyEntry_2$instance<TEntity extends (object | null), TProperty extends unknown> extends PropertyEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_PropertyEntry_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    CurrentValue: TProperty;
    readonly EntityEntry: EntityEntry_1<TEntity>;
}


export const PropertyEntry_2: {
    new<TEntity extends (object | null), TProperty extends unknown>(internalEntry: IInternalEntry, property: IProperty): PropertyEntry_2<TEntity, TProperty>;
};


export interface __PropertyEntry_2$views<TEntity extends (object | null), TProperty extends unknown> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type PropertyEntry_2<TEntity extends (object | null), TProperty extends unknown> = PropertyEntry_2$instance<TEntity, TProperty> & __PropertyEntry_2$views<TEntity, TProperty>;


export interface PropertyValues$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_PropertyValues: never;

    readonly ComplexCollectionProperties: IReadOnlyList_1<IComplexProperty>;
    readonly InternalEntry: InternalEntryBase;
    readonly Properties: IReadOnlyList_1<IProperty>;
    readonly StructuralType: ITypeBase;
    Clone(): PropertyValues;
    Equals(obj: unknown | null): boolean;
    get_Item(propertyName: string): unknown | null;
    get_Item(property: IProperty): unknown | null;
    get_Item(complexProperty: IComplexProperty): IList | null;
    GetHashCode(): int;
    GetValue<TValue extends unknown>(propertyName: string): TValue;
    GetValue<TValue extends unknown>(property: IProperty): TValue;
    set_Item(propertyName: string, value: unknown | null): void;
    set_Item(property: IProperty, value: unknown | null): void;
    set_Item(complexProperty: IComplexProperty, value: IList | null): void;
    SetValues(obj: unknown): void;
    SetValues(propertyValues: PropertyValues): void;
    SetValues<TProperty extends unknown>(values: IDictionary_2<System_Internal.String, TProperty>): void;
    ToObject(): unknown;
    ToString(): string | null;
    TryGetValue<TValue extends unknown>(propertyName: string, value: TValue): boolean;
}


export const PropertyValues: (abstract new(internalEntry: InternalEntryBase) => PropertyValues) & {
};


export type PropertyValues = PropertyValues$instance;

export interface ReferenceEntry$instance extends NavigationEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ReferenceEntry: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    IsModified: boolean;
    readonly TargetEntry: EntityEntry | null;
    GetTargetEntry(): InternalEntityEntry | null;
    Load(): void;
    Load(options: LoadOptions): void;
    LoadAsync(cancellationToken?: CancellationToken): Task;
    LoadAsync(options: LoadOptions, cancellationToken?: CancellationToken): Task;
    Query(): IQueryable;
}


export const ReferenceEntry: {
    new(internalEntry: InternalEntityEntry, name: string): ReferenceEntry;
    new(internalEntry: InternalEntityEntry, navigation: INavigationBase): ReferenceEntry;
};


export interface __ReferenceEntry$views {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type ReferenceEntry = ReferenceEntry$instance & __ReferenceEntry$views;


export interface ReferenceEntry_2$instance<TEntity extends (object | null), TProperty extends (object | null)> extends ReferenceEntry$instance, Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ReferenceEntry_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IInfrastructure_1: never;

    CurrentValue: TProperty;
    readonly EntityEntry: EntityEntry_1<TEntity>;
    Query(): IQueryable_1<TProperty>;
    Query(): IQueryable;
}


export const ReferenceEntry_2: {
    new<TEntity extends (object | null), TProperty extends (object | null)>(internalEntry: InternalEntityEntry, name: string): ReferenceEntry_2<TEntity, TProperty>;
    new<TEntity extends (object | null), TProperty extends (object | null)>(internalEntry: InternalEntityEntry, navigation: INavigation): ReferenceEntry_2<TEntity, TProperty>;
};


export interface __ReferenceEntry_2$views<TEntity extends (object | null), TProperty extends (object | null)> {
    As_IInfrastructure_1(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IInfrastructure_1$instance<IInternalEntry>;
}

export type ReferenceEntry_2<TEntity extends (object | null), TProperty extends (object | null)> = ReferenceEntry_2$instance<TEntity, TProperty> & __ReferenceEntry_2$views<TEntity, TProperty>;


export interface ValueComparer$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ValueComparer: never;

    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

    readonly EqualsExpression: LambdaExpression;
    readonly HashCodeExpression: LambdaExpression;
    readonly ObjectEqualsExpression: LambdaExpression;
    readonly SnapshotExpression: LambdaExpression;
    readonly Type: Type;
    Equals(left: unknown | null, right: unknown | null): boolean;
    ExtractEqualsBody(leftExpression: Expression, rightExpression: Expression): Expression;
    ExtractHashCodeBody(expression: Expression): Expression;
    ExtractSnapshotBody(expression: Expression): Expression;
    GetHashCode(instance: unknown | null): int;
    Snapshot(instance: unknown | null): unknown | null;
}


export const ValueComparer: (abstract new(equalsExpression: LambdaExpression, hashCodeExpression: LambdaExpression, snapshotExpression: LambdaExpression) => ValueComparer) & {
    readonly HashCodeAddMethod: MethodInfo;
    readonly ToHashCodeMethod: MethodInfo;
    readonly BoolIdentity: Expression_1<Func_2<System_Internal.Boolean, System_Internal.Boolean>>;
    Add(hash: HashCode, code: int): HashCode;
    CreateDefault<T extends unknown>(favorStructuralComparisons: boolean): ValueComparer;
    CreateDefault(type: Type, favorStructuralComparisons: boolean): ValueComparer;
    GetGenericSnapshotMethod(type: Type): MethodInfo;
};


export type ValueComparer = ValueComparer$instance;

export interface ValueComparer_1$instance<T extends unknown> extends ValueComparer {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_ChangeTracking_ValueComparer_1: never;

    readonly __tsonic_iface_System_Collections_Generic_IEqualityComparer_1: never;
    readonly __tsonic_iface_System_Collections_IEqualityComparer: never;

    readonly EqualsExpression: Expression_1<Func_3<T | null, T | null, System_Internal.Boolean>>;
    readonly HashCodeExpression: Expression_1<Func_2<T, System_Internal.Int32>>;
    readonly ObjectEqualsExpression: LambdaExpression;
    readonly SnapshotExpression: Expression_1<Func_2<T, T>>;
    readonly Type: Type;
    Equals(left: unknown | null, right: unknown | null): boolean;
    Equals(left: T | null, right: T | null): boolean;
    GetHashCode(instance: unknown | null): int;
    GetHashCode(instance: T): int;
    Snapshot(instance: unknown | null): unknown | null;
    Snapshot(instance: T): T;
}


export const ValueComparer_1: {
    new<T extends unknown>(favorStructuralComparisons: boolean): ValueComparer_1<T>;
    new<T extends unknown>(equalsExpression: Expression_1<Func_3<T | null, T | null, System_Internal.Boolean>>, hashCodeExpression: Expression_1<Func_2<T, System_Internal.Int32>>): ValueComparer_1<T>;
    new<T extends unknown>(equalsExpression: Expression_1<Func_3<T | null, T | null, System_Internal.Boolean>>, hashCodeExpression: Expression_1<Func_2<T, System_Internal.Int32>>, snapshotExpression: Expression_1<Func_2<T, T>>): ValueComparer_1<T>;
    CreateDefaultEqualsExpression<T extends unknown>(): Expression_1<Func_3<T | null, T | null, System_Internal.Boolean>>;
    CreateDefaultHashCodeExpression<T extends unknown>(favorStructuralComparisons: boolean): Expression_1<Func_2<T, System_Internal.Int32>>;
    CreateDefaultSnapshotExpression<T extends unknown>(favorStructuralComparisons: boolean): Expression_1<Func_2<T, T>>;
};


export type ValueComparer_1<T extends unknown> = ValueComparer_1$instance<T>;

export abstract class ValueComparerExtensions$instance {
    static IsDefault(valueComparer: ValueComparer): boolean;
}


export type ValueComparerExtensions = ValueComparerExtensions$instance;
