// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Storage.Json
// Assembly: Microsoft.EntityFrameworkCore

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { IDiagnosticsLogger_1 } from "../../Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal_Internal from "../../Microsoft.EntityFrameworkCore.Storage.Internal/internal/index.js";
import type { ICompositeJsonValueReaderWriter, IJsonConvertedValueReaderWriter } from "../../Microsoft.EntityFrameworkCore.Storage.Internal/internal/index.js";
import type { ValueConverter } from "../../Microsoft.EntityFrameworkCore.Storage.ValueConversion/internal/index.js";
import type { DbLoggerCategory_Query } from "../../Microsoft.EntityFrameworkCore/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions/internal/index.js";
import type { JsonReaderState, JsonTokenType, Utf8JsonReader, Utf8JsonWriter } from "@tsonic/dotnet/System.Text.Json/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Char, DateOnly, DateTime, DateTimeOffset, Decimal, Double, Enum, Guid, IEquatable_1, Int16, Int32, Int64, Nullable_1, Object as ClrObject, SByte, Single, String as ClrString, TimeOnly, TimeSpan, Type, UInt16, UInt32, UInt64, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IJsonValueReaderWriterSource$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Json_IJsonValueReaderWriterSource: never;

    FindReaderWriter(type: Type): JsonValueReaderWriter | null;
}


export type IJsonValueReaderWriterSource = IJsonValueReaderWriterSource$instance;

export interface Utf8JsonReaderManager$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_Utf8JsonReaderManager: never;

    readonly Data: JsonReaderData;
    CurrentReader: Utf8JsonReader;
    readonly QueryLogger: IDiagnosticsLogger_1<DbLoggerCategory_Query> | null;
    CaptureState(): void;
    MoveNext(): JsonTokenType;
    Skip(): void;
}


export const Utf8JsonReaderManager: {
    new(data: JsonReaderData, queryLogger: IDiagnosticsLogger_1<DbLoggerCategory_Query> | null): Utf8JsonReaderManager;
};


export type Utf8JsonReaderManager = Utf8JsonReaderManager$instance;

export interface JsonBoolReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Boolean> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonBoolReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): boolean;
    ToJsonTyped(writer: Utf8JsonWriter, value: boolean): void;
}


export const JsonBoolReaderWriter: {
    new(): JsonBoolReaderWriter;
    readonly Instance: JsonBoolReaderWriter;
};


export type JsonBoolReaderWriter = JsonBoolReaderWriter$instance;

export interface JsonByteArrayReaderWriter$instance extends JsonValueReaderWriter_1<byte[]> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonByteArrayReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): byte[];
    ToJsonTyped(writer: Utf8JsonWriter, value: byte[]): void;
}


export const JsonByteArrayReaderWriter: {
    readonly Instance: JsonByteArrayReaderWriter;
};


export type JsonByteArrayReaderWriter = JsonByteArrayReaderWriter$instance;

export interface JsonByteReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Byte> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonByteReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): byte;
    ToJsonTyped(writer: Utf8JsonWriter, value: byte): void;
}


export const JsonByteReaderWriter: {
    readonly Instance: JsonByteReaderWriter;
};


export type JsonByteReaderWriter = JsonByteReaderWriter$instance;

export interface JsonCastValueReaderWriter_1$instance<TConverted extends unknown> extends JsonValueReaderWriter_1<TConverted>, Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonCastValueReaderWriter_1: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Internal_ICompositeJsonValueReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TConverted;
    ToJsonTyped(writer: Utf8JsonWriter, value: TConverted): void;
}


export const JsonCastValueReaderWriter_1: {
    new<TConverted extends unknown>(providerReaderWriter: JsonValueReaderWriter): JsonCastValueReaderWriter_1<TConverted>;
};


export interface __JsonCastValueReaderWriter_1$views<TConverted extends unknown> {
    As_ICompositeJsonValueReaderWriter(): Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance;
}

export type JsonCastValueReaderWriter_1<TConverted extends unknown> = JsonCastValueReaderWriter_1$instance<TConverted> & __JsonCastValueReaderWriter_1$views<TConverted>;


export interface JsonCharReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Char> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonCharReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): char;
    ToJsonTyped(writer: Utf8JsonWriter, value: char): void;
}


export const JsonCharReaderWriter: {
    readonly Instance: JsonCharReaderWriter;
};


export type JsonCharReaderWriter = JsonCharReaderWriter$instance;

export interface JsonCollectionOfNullableStructsReaderWriter_2$instance<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>> extends JsonValueReaderWriter_1<IEnumerable_1<Nullable_1<TElement>>>, Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonCollectionOfNullableStructsReaderWriter_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Internal_ICompositeJsonValueReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): IEnumerable_1<Nullable_1<TElement>>;
    ToJsonTyped(writer: Utf8JsonWriter, value: IEnumerable_1<Nullable_1<TElement>>): void;
}


export const JsonCollectionOfNullableStructsReaderWriter_2: {
    new<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>>(elementReaderWriter: JsonValueReaderWriter_1<TElement>): JsonCollectionOfNullableStructsReaderWriter_2<TConcreteCollection, TElement>;
};


export interface __JsonCollectionOfNullableStructsReaderWriter_2$views<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>> {
    As_ICompositeJsonValueReaderWriter(): Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance;
}

export type JsonCollectionOfNullableStructsReaderWriter_2<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>> = JsonCollectionOfNullableStructsReaderWriter_2$instance<TConcreteCollection, TElement> & __JsonCollectionOfNullableStructsReaderWriter_2$views<TConcreteCollection, TElement>;


export interface JsonCollectionOfReferencesReaderWriter_2$instance<TConcreteCollection extends unknown, TElement extends (object | null)> extends JsonValueReaderWriter_1<unknown>, Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonCollectionOfReferencesReaderWriter_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Internal_ICompositeJsonValueReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): unknown;
    ToJsonTyped(writer: Utf8JsonWriter, value: unknown | null): void;
}


export const JsonCollectionOfReferencesReaderWriter_2: {
    new<TConcreteCollection extends unknown, TElement extends (object | null)>(elementReaderWriter: JsonValueReaderWriter): JsonCollectionOfReferencesReaderWriter_2<TConcreteCollection, TElement>;
};


export interface __JsonCollectionOfReferencesReaderWriter_2$views<TConcreteCollection extends unknown, TElement extends (object | null)> {
    As_ICompositeJsonValueReaderWriter(): Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance;
}

export type JsonCollectionOfReferencesReaderWriter_2<TConcreteCollection extends unknown, TElement extends (object | null)> = JsonCollectionOfReferencesReaderWriter_2$instance<TConcreteCollection, TElement> & __JsonCollectionOfReferencesReaderWriter_2$views<TConcreteCollection, TElement>;


export interface JsonCollectionOfStructsReaderWriter_2$instance<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>> extends JsonValueReaderWriter_1<IEnumerable_1<TElement>>, Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonCollectionOfStructsReaderWriter_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Internal_ICompositeJsonValueReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): IEnumerable_1<TElement>;
    ToJsonTyped(writer: Utf8JsonWriter, value: IEnumerable_1<TElement>): void;
}


export const JsonCollectionOfStructsReaderWriter_2: {
    new<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>>(elementReaderWriter: JsonValueReaderWriter_1<TElement>): JsonCollectionOfStructsReaderWriter_2<TConcreteCollection, TElement>;
};


export interface __JsonCollectionOfStructsReaderWriter_2$views<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>> {
    As_ICompositeJsonValueReaderWriter(): Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance;
}

export type JsonCollectionOfStructsReaderWriter_2<TConcreteCollection extends unknown, TElement extends NonNullable<unknown>> = JsonCollectionOfStructsReaderWriter_2$instance<TConcreteCollection, TElement> & __JsonCollectionOfStructsReaderWriter_2$views<TConcreteCollection, TElement>;


export interface JsonConvertedValueReaderWriter_2$instance<TModel extends unknown, TProvider extends unknown> extends JsonValueReaderWriter_1<TModel>, Microsoft_EntityFrameworkCore_Storage_Internal_Internal.IJsonConvertedValueReaderWriter$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonConvertedValueReaderWriter_2: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Internal_ICompositeJsonValueReaderWriter: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Internal_IJsonConvertedValueReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TModel;
    ToJsonTyped(writer: Utf8JsonWriter, value: TModel): void;
}


export const JsonConvertedValueReaderWriter_2: {
    new<TModel extends unknown, TProvider extends unknown>(providerReaderWriter: JsonValueReaderWriter_1<TProvider>, converter: ValueConverter): JsonConvertedValueReaderWriter_2<TModel, TProvider>;
};


export interface __JsonConvertedValueReaderWriter_2$views<TModel extends unknown, TProvider extends unknown> {
    As_ICompositeJsonValueReaderWriter(): Microsoft_EntityFrameworkCore_Storage_Internal_Internal.ICompositeJsonValueReaderWriter$instance;
    As_IJsonConvertedValueReaderWriter(): Microsoft_EntityFrameworkCore_Storage_Internal_Internal.IJsonConvertedValueReaderWriter$instance;
}

export type JsonConvertedValueReaderWriter_2<TModel extends unknown, TProvider extends unknown> = JsonConvertedValueReaderWriter_2$instance<TModel, TProvider> & __JsonConvertedValueReaderWriter_2$views<TModel, TProvider>;


export interface JsonDateOnlyReaderWriter$instance extends JsonValueReaderWriter_1<DateOnly> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonDateOnlyReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): DateOnly;
    ToJsonTyped(writer: Utf8JsonWriter, value: DateOnly): void;
}


export const JsonDateOnlyReaderWriter: {
    readonly Instance: JsonDateOnlyReaderWriter;
};


export type JsonDateOnlyReaderWriter = JsonDateOnlyReaderWriter$instance;

export interface JsonDateTimeOffsetReaderWriter$instance extends JsonValueReaderWriter_1<DateTimeOffset> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonDateTimeOffsetReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): DateTimeOffset;
    ToJsonTyped(writer: Utf8JsonWriter, value: DateTimeOffset): void;
}


export const JsonDateTimeOffsetReaderWriter: {
    readonly Instance: JsonDateTimeOffsetReaderWriter;
};


export type JsonDateTimeOffsetReaderWriter = JsonDateTimeOffsetReaderWriter$instance;

export interface JsonDateTimeReaderWriter$instance extends JsonValueReaderWriter_1<DateTime> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonDateTimeReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): DateTime;
    ToJsonTyped(writer: Utf8JsonWriter, value: DateTime): void;
}


export const JsonDateTimeReaderWriter: {
    readonly Instance: JsonDateTimeReaderWriter;
};


export type JsonDateTimeReaderWriter = JsonDateTimeReaderWriter$instance;

export interface JsonDecimalReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Decimal> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonDecimalReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): decimal;
    ToJsonTyped(writer: Utf8JsonWriter, value: decimal): void;
}


export const JsonDecimalReaderWriter: {
    readonly Instance: JsonDecimalReaderWriter;
};


export type JsonDecimalReaderWriter = JsonDecimalReaderWriter$instance;

export interface JsonDoubleReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Double> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonDoubleReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): double;
    ToJsonTyped(writer: Utf8JsonWriter, value: double): void;
}


export const JsonDoubleReaderWriter: {
    readonly Instance: JsonDoubleReaderWriter;
};


export type JsonDoubleReaderWriter = JsonDoubleReaderWriter$instance;

export interface JsonFloatReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Single> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonFloatReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): float;
    ToJsonTyped(writer: Utf8JsonWriter, value: float): void;
}


export const JsonFloatReaderWriter: {
    readonly Instance: JsonFloatReaderWriter;
};


export type JsonFloatReaderWriter = JsonFloatReaderWriter$instance;

export interface JsonGuidReaderWriter$instance extends JsonValueReaderWriter_1<Guid> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonGuidReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): Guid;
    ToJsonTyped(writer: Utf8JsonWriter, value: Guid): void;
}


export const JsonGuidReaderWriter: {
    readonly Instance: JsonGuidReaderWriter;
};


export type JsonGuidReaderWriter = JsonGuidReaderWriter$instance;

export interface JsonInt16ReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Int16> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonInt16ReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): short;
    ToJsonTyped(writer: Utf8JsonWriter, value: short): void;
}


export const JsonInt16ReaderWriter: {
    readonly Instance: JsonInt16ReaderWriter;
};


export type JsonInt16ReaderWriter = JsonInt16ReaderWriter$instance;

export interface JsonInt32ReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Int32> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonInt32ReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): int;
    ToJsonTyped(writer: Utf8JsonWriter, value: int): void;
}


export const JsonInt32ReaderWriter: {
    readonly Instance: JsonInt32ReaderWriter;
};


export type JsonInt32ReaderWriter = JsonInt32ReaderWriter$instance;

export interface JsonInt64ReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.Int64> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonInt64ReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): long;
    ToJsonTyped(writer: Utf8JsonWriter, value: long): void;
}


export const JsonInt64ReaderWriter: {
    readonly Instance: JsonInt64ReaderWriter;
};


export type JsonInt64ReaderWriter = JsonInt64ReaderWriter$instance;

export interface JsonNullReaderWriter$instance extends JsonValueReaderWriter_1<unknown> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonNullReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): unknown;
    ToJsonTyped(writer: Utf8JsonWriter, value: unknown | null): void;
}


export const JsonNullReaderWriter: {
    readonly Instance: JsonNullReaderWriter;
};


export type JsonNullReaderWriter = JsonNullReaderWriter$instance;

export interface JsonReaderData$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonReaderData: never;

    CaptureState(manager: Utf8JsonReaderManager): void;
    CreateReader(): Utf8JsonReader;
    ReadBytes(bytesConsumed: int, state: JsonReaderState): Utf8JsonReader;
}


export const JsonReaderData: {
    new(buffer: byte[]): JsonReaderData;
    new(stream: Stream): JsonReaderData;
};


export type JsonReaderData = JsonReaderData$instance;

export interface JsonSByteReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.SByte> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonSByteReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): sbyte;
    ToJsonTyped(writer: Utf8JsonWriter, value: sbyte): void;
}


export const JsonSByteReaderWriter: {
    readonly Instance: JsonSByteReaderWriter;
};


export type JsonSByteReaderWriter = JsonSByteReaderWriter$instance;

export interface JsonSignedEnumReaderWriter_1$instance<TEnum extends NonNullable<unknown> & number> extends JsonValueReaderWriter_1<TEnum> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonSignedEnumReaderWriter_1: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TEnum;
    ToJsonTyped(writer: Utf8JsonWriter, value: TEnum): void;
}


export const JsonSignedEnumReaderWriter_1: {
    readonly Instance: <TEnum extends NonNullable<unknown> & number>() => JsonSignedEnumReaderWriter_1<TEnum>;
};


export type JsonSignedEnumReaderWriter_1<TEnum extends NonNullable<unknown> & number> = JsonSignedEnumReaderWriter_1$instance<TEnum>;

export interface JsonStringReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.String> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonStringReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): string;
    ToJsonTyped(writer: Utf8JsonWriter, value: string): void;
}


export const JsonStringReaderWriter: {
    readonly Instance: JsonStringReaderWriter;
};


export type JsonStringReaderWriter = JsonStringReaderWriter$instance;

export interface JsonTimeOnlyReaderWriter$instance extends JsonValueReaderWriter_1<TimeOnly> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonTimeOnlyReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TimeOnly;
    ToJsonTyped(writer: Utf8JsonWriter, value: TimeOnly): void;
}


export const JsonTimeOnlyReaderWriter: {
    readonly Instance: JsonTimeOnlyReaderWriter;
};


export type JsonTimeOnlyReaderWriter = JsonTimeOnlyReaderWriter$instance;

export interface JsonTimeSpanReaderWriter$instance extends JsonValueReaderWriter_1<TimeSpan> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonTimeSpanReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TimeSpan;
    ToJsonTyped(writer: Utf8JsonWriter, value: TimeSpan): void;
}


export const JsonTimeSpanReaderWriter: {
    readonly Instance: JsonTimeSpanReaderWriter;
};


export type JsonTimeSpanReaderWriter = JsonTimeSpanReaderWriter$instance;

export interface JsonUInt16ReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.UInt16> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonUInt16ReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): ushort;
    ToJsonTyped(writer: Utf8JsonWriter, value: ushort): void;
}


export const JsonUInt16ReaderWriter: {
    readonly Instance: JsonUInt16ReaderWriter;
};


export type JsonUInt16ReaderWriter = JsonUInt16ReaderWriter$instance;

export interface JsonUInt32ReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.UInt32> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonUInt32ReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): uint;
    ToJsonTyped(writer: Utf8JsonWriter, value: uint): void;
}


export const JsonUInt32ReaderWriter: {
    readonly Instance: JsonUInt32ReaderWriter;
};


export type JsonUInt32ReaderWriter = JsonUInt32ReaderWriter$instance;

export interface JsonUInt64ReaderWriter$instance extends JsonValueReaderWriter_1<System_Internal.UInt64> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonUInt64ReaderWriter: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): ulong;
    ToJsonTyped(writer: Utf8JsonWriter, value: ulong): void;
}


export const JsonUInt64ReaderWriter: {
    readonly Instance: JsonUInt64ReaderWriter;
};


export type JsonUInt64ReaderWriter = JsonUInt64ReaderWriter$instance;

export interface JsonUnsignedEnumReaderWriter_1$instance<TEnum extends NonNullable<unknown> & number> extends JsonValueReaderWriter_1<TEnum> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonUnsignedEnumReaderWriter_1: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TEnum;
    ToJsonTyped(writer: Utf8JsonWriter, value: TEnum): void;
}


export const JsonUnsignedEnumReaderWriter_1: {
    readonly Instance: <TEnum extends NonNullable<unknown> & number>() => JsonUnsignedEnumReaderWriter_1<TEnum>;
};


export type JsonUnsignedEnumReaderWriter_1<TEnum extends NonNullable<unknown> & number> = JsonUnsignedEnumReaderWriter_1$instance<TEnum>;

export interface JsonValueReaderWriter$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonValueReaderWriter: never;

    readonly ConstructorExpression: Expression;
    readonly ValueType: Type;
    FromJson(manager: Utf8JsonReaderManager, existingObject?: unknown | null): unknown;
    FromJsonString(json: string, existingObject?: unknown | null): unknown;
    ToJson(writer: Utf8JsonWriter, value: unknown): void;
    ToJsonObjectString(propertyName: string, value: unknown | null): string;
    ToJsonString(value: unknown): string;
}


export const JsonValueReaderWriter: {
    CreateFromType(readerWriterType: Type | null): JsonValueReaderWriter | null;
};


export type JsonValueReaderWriter = JsonValueReaderWriter$instance;

export interface JsonValueReaderWriter_1$instance<TValue extends unknown> extends JsonValueReaderWriter {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonValueReaderWriter_1: never;

    readonly ValueType: Type;
    FromJson(manager: Utf8JsonReaderManager, existingObject?: unknown | null): unknown;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TValue;
    ToJson(writer: Utf8JsonWriter, value: unknown): void;
    ToJsonTyped(writer: Utf8JsonWriter, value: TValue): void;
}


export const JsonValueReaderWriter_1: (abstract new<TValue extends unknown>() => JsonValueReaderWriter_1<TValue>) & {
};


export type JsonValueReaderWriter_1<TValue extends unknown> = JsonValueReaderWriter_1$instance<TValue>;

export interface JsonValueReaderWriterSource$instance extends IJsonValueReaderWriterSource$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonValueReaderWriterSource: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_Json_IJsonValueReaderWriterSource: never;

    readonly Dependencies: JsonValueReaderWriterSourceDependencies;
    FindReaderWriter(type: Type): JsonValueReaderWriter | null;
}


export const JsonValueReaderWriterSource: {
    new(dependencies: JsonValueReaderWriterSourceDependencies): JsonValueReaderWriterSource;
};


export interface __JsonValueReaderWriterSource$views {
    As_IJsonValueReaderWriterSource(): IJsonValueReaderWriterSource$instance;
}

export type JsonValueReaderWriterSource = JsonValueReaderWriterSource$instance & __JsonValueReaderWriterSource$views;


export interface JsonValueReaderWriterSourceDependencies$instance {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonValueReaderWriterSourceDependencies: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    _Clone_$(): JsonValueReaderWriterSourceDependencies;
    Equals(obj: unknown | null): boolean;
    Equals(other: JsonValueReaderWriterSourceDependencies | null): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const JsonValueReaderWriterSourceDependencies: {
    new(): JsonValueReaderWriterSourceDependencies;
};


export type JsonValueReaderWriterSourceDependencies = JsonValueReaderWriterSourceDependencies$instance;

export interface JsonWarningEnumReaderWriter_1$instance<TEnum extends NonNullable<unknown> & number> extends JsonValueReaderWriter_1<TEnum> {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Storage_Json_JsonWarningEnumReaderWriter_1: never;

    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown | null): TEnum;
    ToJsonTyped(writer: Utf8JsonWriter, value: TEnum): void;
}


export const JsonWarningEnumReaderWriter_1: {
    readonly Instance: <TEnum extends NonNullable<unknown> & number>() => JsonWarningEnumReaderWriter_1<TEnum>;
};


export type JsonWarningEnumReaderWriter_1<TEnum extends NonNullable<unknown> & number> = JsonWarningEnumReaderWriter_1$instance<TEnum>;

