// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Migrations.Operations
// Assembly: Microsoft.EntityFrameworkCore.Relational

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { Annotatable, Annotation, IAnnotatable, IAnnotation, IReadOnlyAnnotatable } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Internal from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { ICheckConstraint, IForeignKeyConstraint, IMutableAnnotatable, IPrimaryKeyConstraint, ITableIndex, IUniqueConstraint } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { ReferentialAction } from "../../Microsoft.EntityFrameworkCore.Migrations/internal/index.js";
import type { IEnumerable, IReadOnlyDictionary, List } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Boolean as ClrBoolean, Func, Int32, Int64, Nullable, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";

export interface IAlterMigrationOperation$instance {
    readonly OldAnnotations: IMutableAnnotatable;
}


export type IAlterMigrationOperation = IAlterMigrationOperation$instance;

export interface ITableMigrationOperation$instance {
    readonly Schema: string;
    readonly Table: string;
}


export type ITableMigrationOperation = ITableMigrationOperation$instance;

export interface AddCheckConstraintOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Sql: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AddCheckConstraintOperation: {
    new(): AddCheckConstraintOperation;
    CreateFrom(checkConstraint: ICheckConstraint): AddCheckConstraintOperation;
};


export interface __AddCheckConstraintOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type AddCheckConstraintOperation = AddCheckConstraintOperation$instance & __AddCheckConstraintOperation$views;


export interface AddColumnOperation$instance extends ColumnOperation$instance {
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AddColumnOperation: {
    new(): AddColumnOperation;
};


export interface __AddColumnOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type AddColumnOperation = AddColumnOperation$instance & __AddColumnOperation$views;


export interface AddForeignKeyOperation$instance extends MigrationOperation$instance {
    Columns: string[];
    Name: string;
    OnDelete: ReferentialAction;
    OnUpdate: ReferentialAction;
    PrincipalColumns: string[];
    get PrincipalSchema(): string | undefined;
    set PrincipalSchema(value: string);
    PrincipalTable: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AddForeignKeyOperation: {
    new(): AddForeignKeyOperation;
    CreateFrom(foreignKey: IForeignKeyConstraint): AddForeignKeyOperation;
};


export interface __AddForeignKeyOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type AddForeignKeyOperation = AddForeignKeyOperation$instance & __AddForeignKeyOperation$views;


export interface AddPrimaryKeyOperation$instance extends MigrationOperation$instance {
    Columns: string[];
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AddPrimaryKeyOperation: {
    new(): AddPrimaryKeyOperation;
    CreateFrom(primaryKey: IPrimaryKeyConstraint): AddPrimaryKeyOperation;
};


export interface __AddPrimaryKeyOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type AddPrimaryKeyOperation = AddPrimaryKeyOperation$instance & __AddPrimaryKeyOperation$views;


export interface AddUniqueConstraintOperation$instance extends MigrationOperation$instance {
    Columns: string[];
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AddUniqueConstraintOperation: {
    new(): AddUniqueConstraintOperation;
    CreateFrom(uniqueConstraint: IUniqueConstraint): AddUniqueConstraintOperation;
};


export interface __AddUniqueConstraintOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type AddUniqueConstraintOperation = AddUniqueConstraintOperation$instance & __AddUniqueConstraintOperation$views;


export interface AlterColumnOperation$instance extends ColumnOperation$instance {
    OldColumn: ColumnOperation;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AlterColumnOperation: {
    new(): AlterColumnOperation;
};


export interface __AlterColumnOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_IAlterMigrationOperation(): IAlterMigrationOperation$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export interface AlterColumnOperation$instance extends IAlterMigrationOperation$instance {}

export type AlterColumnOperation = AlterColumnOperation$instance & __AlterColumnOperation$views;


export interface AlterDatabaseOperation$instance extends DatabaseOperation$instance {
    readonly OldDatabase: DatabaseOperation;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AlterDatabaseOperation: {
    new(): AlterDatabaseOperation;
};


export interface __AlterDatabaseOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_IAlterMigrationOperation(): IAlterMigrationOperation$instance;
}

export interface AlterDatabaseOperation$instance extends IAlterMigrationOperation$instance {}

export type AlterDatabaseOperation = AlterDatabaseOperation$instance & __AlterDatabaseOperation$views;


export interface AlterSequenceOperation$instance extends SequenceOperation$instance {
    Name: string;
    OldSequence: SequenceOperation;
    Schema: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AlterSequenceOperation: {
    new(): AlterSequenceOperation;
};


export interface __AlterSequenceOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_IAlterMigrationOperation(): IAlterMigrationOperation$instance;
}

export interface AlterSequenceOperation$instance extends IAlterMigrationOperation$instance {}

export type AlterSequenceOperation = AlterSequenceOperation$instance & __AlterSequenceOperation$views;


export interface AlterTableOperation$instance extends TableOperation$instance {
    OldTable: TableOperation;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const AlterTableOperation: {
    new(): AlterTableOperation;
};


export interface __AlterTableOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_IAlterMigrationOperation(): IAlterMigrationOperation$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export interface AlterTableOperation$instance extends IAlterMigrationOperation$instance {}

export type AlterTableOperation = AlterTableOperation$instance & __AlterTableOperation$views;


export interface ColumnOperation$instance extends MigrationOperation$instance {
    ClrType: Type;
    get Collation(): string | undefined;
    set Collation(value: string);
    get ColumnType(): string | undefined;
    set ColumnType(value: string);
    get Comment(): string | undefined;
    set Comment(value: string);
    get ComputedColumnSql(): string | undefined;
    set ComputedColumnSql(value: string);
    get DefaultValue(): unknown | undefined;
    set DefaultValue(value: unknown);
    get DefaultValueSql(): string | undefined;
    set DefaultValueSql(value: string);
    IsFixedLength: Nullable<System_Internal.Boolean>;
    IsNullable: boolean;
    IsRowVersion: boolean;
    IsStored: Nullable<System_Internal.Boolean>;
    IsUnicode: Nullable<System_Internal.Boolean>;
    MaxLength: Nullable<System_Internal.Int32>;
    Name: string;
    Precision: Nullable<System_Internal.Int32>;
    Scale: Nullable<System_Internal.Int32>;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const ColumnOperation: {
};


export interface __ColumnOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type ColumnOperation = ColumnOperation$instance & __ColumnOperation$views;


export interface CreateIndexOperation$instance extends MigrationOperation$instance {
    Columns: string[];
    get Filter(): string | undefined;
    set Filter(value: string);
    IsDescending: boolean[];
    IsUnique: boolean;
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const CreateIndexOperation: {
    new(): CreateIndexOperation;
    CreateFrom(index: ITableIndex): CreateIndexOperation;
};


export interface __CreateIndexOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type CreateIndexOperation = CreateIndexOperation$instance & __CreateIndexOperation$views;


export interface CreateSequenceOperation$instance extends SequenceOperation$instance {
    ClrType: Type;
    Name: string;
    Schema: string;
    StartValue: long;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const CreateSequenceOperation: {
    new(): CreateSequenceOperation;
};


export interface __CreateSequenceOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type CreateSequenceOperation = CreateSequenceOperation$instance & __CreateSequenceOperation$views;


export interface CreateTableOperation$instance extends TableOperation$instance {
    readonly CheckConstraints: List<AddCheckConstraintOperation>;
    readonly Columns: List<AddColumnOperation>;
    readonly ForeignKeys: List<AddForeignKeyOperation>;
    get PrimaryKey(): AddPrimaryKeyOperation | undefined;
    set PrimaryKey(value: AddPrimaryKeyOperation);
    readonly UniqueConstraints: List<AddUniqueConstraintOperation>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const CreateTableOperation: {
    new(): CreateTableOperation;
};


export interface __CreateTableOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type CreateTableOperation = CreateTableOperation$instance & __CreateTableOperation$views;


export interface DatabaseOperation$instance extends MigrationOperation$instance {
    get Collation(): string | undefined;
    set Collation(value: string);
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DatabaseOperation: {
};


export interface __DatabaseOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DatabaseOperation = DatabaseOperation$instance & __DatabaseOperation$views;


export interface DeleteDataOperation$instance extends MigrationOperation$instance {
    KeyColumns: string[];
    get KeyColumnTypes(): string[] | undefined;
    set KeyColumnTypes(value: string[]);
    KeyValues: Array<Array<(unknown | undefined)>>;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DeleteDataOperation: {
    new(): DeleteDataOperation;
};


export interface __DeleteDataOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DeleteDataOperation = DeleteDataOperation$instance & __DeleteDataOperation$views;


export interface DropCheckConstraintOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropCheckConstraintOperation: {
    new(): DropCheckConstraintOperation;
};


export interface __DropCheckConstraintOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DropCheckConstraintOperation = DropCheckConstraintOperation$instance & __DropCheckConstraintOperation$views;


export interface DropColumnOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropColumnOperation: {
    new(): DropColumnOperation;
};


export interface __DropColumnOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DropColumnOperation = DropColumnOperation$instance & __DropColumnOperation$views;


export interface DropForeignKeyOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropForeignKeyOperation: {
    new(): DropForeignKeyOperation;
};


export interface __DropForeignKeyOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DropForeignKeyOperation = DropForeignKeyOperation$instance & __DropForeignKeyOperation$views;


export interface DropIndexOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropIndexOperation: {
    new(): DropIndexOperation;
};


export interface __DropIndexOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DropIndexOperation = DropIndexOperation$instance & __DropIndexOperation$views;


export interface DropPrimaryKeyOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropPrimaryKeyOperation: {
    new(): DropPrimaryKeyOperation;
};


export interface __DropPrimaryKeyOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DropPrimaryKeyOperation = DropPrimaryKeyOperation$instance & __DropPrimaryKeyOperation$views;


export interface DropSchemaOperation$instance extends MigrationOperation$instance {
    Name: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropSchemaOperation: {
    new(): DropSchemaOperation;
};


export interface __DropSchemaOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DropSchemaOperation = DropSchemaOperation$instance & __DropSchemaOperation$views;


export interface DropSequenceOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropSequenceOperation: {
    new(): DropSequenceOperation;
};


export interface __DropSequenceOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type DropSequenceOperation = DropSequenceOperation$instance & __DropSequenceOperation$views;


export interface DropTableOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropTableOperation: {
    new(): DropTableOperation;
};


export interface __DropTableOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DropTableOperation = DropTableOperation$instance & __DropTableOperation$views;


export interface DropUniqueConstraintOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const DropUniqueConstraintOperation: {
    new(): DropUniqueConstraintOperation;
};


export interface __DropUniqueConstraintOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type DropUniqueConstraintOperation = DropUniqueConstraintOperation$instance & __DropUniqueConstraintOperation$views;


export interface EnsureSchemaOperation$instance extends MigrationOperation$instance {
    Name: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const EnsureSchemaOperation: {
    new(): EnsureSchemaOperation;
};


export interface __EnsureSchemaOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type EnsureSchemaOperation = EnsureSchemaOperation$instance & __EnsureSchemaOperation$views;


export interface InsertDataOperation$instance extends MigrationOperation$instance {
    Columns: string[];
    get ColumnTypes(): string[] | undefined;
    set ColumnTypes(value: string[]);
    Schema: string;
    Table: string;
    Values: Array<Array<(unknown | undefined)>>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const InsertDataOperation: {
    new(): InsertDataOperation;
};


export interface __InsertDataOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type InsertDataOperation = InsertDataOperation$instance & __InsertDataOperation$views;


export interface MigrationOperation$instance extends Annotatable {
    IsDestructiveChange: boolean;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const MigrationOperation: {
};


export interface __MigrationOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type MigrationOperation = MigrationOperation$instance & __MigrationOperation$views;


export interface RenameColumnOperation$instance extends MigrationOperation$instance {
    Name: string;
    NewName: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const RenameColumnOperation: {
    new(): RenameColumnOperation;
};


export interface __RenameColumnOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type RenameColumnOperation = RenameColumnOperation$instance & __RenameColumnOperation$views;


export interface RenameIndexOperation$instance extends MigrationOperation$instance {
    Name: string;
    NewName: string;
    Schema: string;
    Table: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const RenameIndexOperation: {
    new(): RenameIndexOperation;
};


export interface __RenameIndexOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type RenameIndexOperation = RenameIndexOperation$instance & __RenameIndexOperation$views;


export interface RenameSequenceOperation$instance extends MigrationOperation$instance {
    Name: string;
    NewName: string;
    get NewSchema(): string | undefined;
    set NewSchema(value: string);
    Schema: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const RenameSequenceOperation: {
    new(): RenameSequenceOperation;
};


export interface __RenameSequenceOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type RenameSequenceOperation = RenameSequenceOperation$instance & __RenameSequenceOperation$views;


export interface RenameTableOperation$instance extends MigrationOperation$instance {
    Name: string;
    NewName: string;
    get NewSchema(): string | undefined;
    set NewSchema(value: string);
    Schema: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const RenameTableOperation: {
    new(): RenameTableOperation;
};


export interface __RenameTableOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type RenameTableOperation = RenameTableOperation$instance & __RenameTableOperation$views;


export interface RestartSequenceOperation$instance extends MigrationOperation$instance {
    Name: string;
    Schema: string;
    StartValue: Nullable<System_Internal.Int64>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const RestartSequenceOperation: {
    new(): RestartSequenceOperation;
};


export interface __RestartSequenceOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type RestartSequenceOperation = RestartSequenceOperation$instance & __RestartSequenceOperation$views;


export interface SequenceOperation$instance extends MigrationOperation$instance {
    IncrementBy: int;
    IsCyclic: boolean;
    MaxValue: Nullable<System_Internal.Int64>;
    MinValue: Nullable<System_Internal.Int64>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const SequenceOperation: {
};


export interface __SequenceOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type SequenceOperation = SequenceOperation$instance & __SequenceOperation$views;


export interface SqlOperation$instance extends MigrationOperation$instance {
    Sql: string;
    SuppressTransaction: boolean;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const SqlOperation: {
    new(): SqlOperation;
};


export interface __SqlOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
}

export type SqlOperation = SqlOperation$instance & __SqlOperation$views;


export interface TableOperation$instance extends MigrationOperation$instance {
    get Comment(): string | undefined;
    set Comment(value: string);
    Name: string;
    Schema: string;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const TableOperation: {
};


export interface __TableOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type TableOperation = TableOperation$instance & __TableOperation$views;


export interface UpdateDataOperation$instance extends MigrationOperation$instance {
    Columns: string[];
    get ColumnTypes(): string[] | undefined;
    set ColumnTypes(value: string[]);
    KeyColumns: string[];
    get KeyColumnTypes(): string[] | undefined;
    set KeyColumnTypes(value: string[]);
    KeyValues: Array<Array<(unknown | undefined)>>;
    Schema: string;
    Table: string;
    Values: Array<Array<(unknown | undefined)>>;
    AddAnnotation(name: string, value: unknown): IAnnotation;
    AddAnnotation(name: string, value: unknown): Annotation;
    AddAnnotations(annotations: IEnumerable<IAnnotation>): void;
    AddAnnotations(annotations: IReadOnlyDictionary<System_Internal.String, unknown>): void;
    AddRuntimeAnnotation(name: string, value: unknown): IAnnotation;
    AddRuntimeAnnotation(name: string, value: unknown): Annotation;
    AnnotationsToDebugString(indent?: int): string;
    FindAnnotation(name: string): IAnnotation | undefined;
    FindAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotation(name: string): IAnnotation | undefined;
    FindRuntimeAnnotation(name: string): Annotation | undefined;
    FindRuntimeAnnotationValue(name: string): unknown | undefined;
    GetAnnotations(): IEnumerable<IAnnotation>;
    GetOrAddRuntimeAnnotationValue<TValue, TArg>(name: string, valueFactory: Func<TArg, TValue>, factoryArgument: TArg): TValue;
    GetRuntimeAnnotations(): IEnumerable<IAnnotation>;
    RemoveAnnotation(name: string): IAnnotation | undefined;
    RemoveAnnotation(name: string): Annotation | undefined;
    SetAnnotation(name: string, value: unknown): void;
}


export const UpdateDataOperation: {
    new(): UpdateDataOperation;
};


export interface __UpdateDataOperation$views {
    As_IAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IAnnotatable$instance;
    As_IReadOnlyAnnotatable(): Microsoft_EntityFrameworkCore_Infrastructure_Internal.IReadOnlyAnnotatable$instance;
    As_IMutableAnnotatable(): Microsoft_EntityFrameworkCore_Metadata_Internal.IMutableAnnotatable$instance;
    As_ITableMigrationOperation(): ITableMigrationOperation$instance;
}

export type UpdateDataOperation = UpdateDataOperation$instance & __UpdateDataOperation$views;


